### ISSUE TITLE
🐛 Missing `null` state message when a user has experiences but no experiences with linked skills

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#10198]
## 🐛 Bug

Missing null state message when a user has experiences but no experiences with linked skills.

## 🦋 Expected Behaviour

There should be a message for the null state.

## 📋 Steps to Reproduce

1. As a user with an admin role, navigate to `/admin/users/:user-id/profile#career-timeline-section`
2. Ensure the user's page who is being visited has at least one experience but none of the experiences can have linked skills
3. Click the "By Skills" tab
4. Observe empty space

## 📸 Screenshot

<img width="1318" alt="Screen Shot 2024-04-26 at 11 49 02" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/b8132813-0afb-4d73-b6cb-a2bdf5db5e1b">

## 🙋‍♀️ Proposed Solution

Replace `null` with a message in `apps/web/src/components/UserProfile/ExperienceSection.tsx`. Message could be something like: No skills have been linked to any experiences.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/db7cbc07a3aba75a8157b53333a8fe8921b0fd43/apps/web/src/components/UserProfile/ExperienceSection.tsx#L196

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] message renders for the `null` state

**Comment by substrae** [comment]
@mnigh 

If I'm understanding this correctly after our chat yesterday, this state is only possible when viewing a user through the user table who hasn't applied to a job and hasn't linked any skills to experiences via their profile interface. Theoretically, that means that only users who can view the "All users" table will ever see this state (which should mean Sys Admins because Community users can only see users who have applied to their pools, right?). I'm okay with your suggestion if that's the case.
