### ISSUE TITLE
✨ Create a strict "report only" Content Security Policy

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10420]
## ✨ Feature

Content Security Policy ([CSP](https://developer.mozilla.org/en-US/docs/Glossary/CSP)) is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross-Site Scripting ([XSS](https://developer.mozilla.org/en-US/docs/Glossary/Cross-site_scripting)) and data injection attacks. These attacks are used for everything from data theft, to site defacement, to malware distribution.Content Security Policy ([CSP](https://developer.mozilla.org/en-US/docs/Glossary/CSP)) is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross-Site Scripting ([XSS](https://developer.mozilla.org/en-US/docs/Glossary/Cross-site_scripting)) and data injection attacks. These attacks are used for everything from data theft, to site defacement, to malware distribution.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

We could setup a very strict [report only policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#testing_your_policy) which will report on all resources we need to consider for the policy. The next step would be to review that report (found in the warning console) and apply an appropriate policy to every one. 

## ✅ Acceptance Criteria

- [ ] Set prod Nginx config with a strict but "report only" header
- [ ] Ensure policy violations are logging

## 🛑 Blockers

```[tasklist]
### Blocked By
```

**Comment by mnigh** [comment]
This library might be helpful: https://github.com/spatie/laravel-csp

**Comment by petertgiles** [comment]
I will submit a Jira ticket to get the IMTD perspective

**Comment by petertgiles** [comment]
AZ-20272 submitted

**Comment by petertgiles** [comment]
IMTD has confirmed that the F5 shouldn't change or interfere with CSP headers that we may generate from our webserver.

**Comment by petertgiles** [comment]
I will remove reporting endpoint requirement and we'll start with just viewing console logs

**Comment by esizer** [comment]
Added a strict report only. Turns out, it isn't that bad since almost all resources from us (`talent.canada.ca`). We only really need to worry about some svg images, inline styles and Google fonts.

I'd probably reccomend we implement the following in prod (still as a report only with a report endpoint) and leave it like that for a bit until we are confident there are no vilations.

- `style-src fonts.googleapis.com 'unsafe-inline'` Safer to avoid `unsafe-inline` and either remove inline styles or add a nonce
- `font-src fonts.gstatic.com 'self'`
- `img-src data:image` But safer to do a hash or avoid `data:` images)
- `default-src 'self'`

Full Header inm nginx:

`Added a strict report only. Turns out, it isn't that bad since almost all resources from us (`talent.canada.ca`). We only really need to worry about some svg images, inline styles and Google fonts.

I'd probably reccomend we implement the following in prod (still as a report only with a report endpoint) and leave it like that for a bit until we are confident there are no vilations.

- `style-src fonts.googleapis.com 'unsafe-inline'` Safer to avoid `unsafe-inline` and either remove inline styles or add a nonce
- `font-src fonts.googleapis.com 'self'`
- `img-src data:image` But safer to do a hash or avoid `data:` images)
- `default-src 'self'`

Full Header inm nginx:

`add_header Content-Security-Policy  "default-src 'self'; font-src fonts.googleapis.com 'self'; style-src fonts.googleapis.com 'nonce-1234' 'self'; img-src 'nonce-1234' 'self';";``

**Comment by esizer** [comment]
> Should there be a PR attached to this issue?

I was going to bring that up and ask about next steps in stand up :sweat_smile: Do we want to add this header in or use this more as a spike for the real policy?

**Comment by petertgiles** [comment]
TODO: I'll write up an issue

**Comment by petertgiles** [comment]
#10614
