### ISSUE TITLE
🐛 notify config env missing default values

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#10633]
## 🐛 Bug

The notify config env is missing default values.

## 🦋 Expected Behaviour

If there are no values set, only GC Notify should fail, not the in-app notifications.

## 🕵️ Details

https://github.com/GCTC-NTGC/gc-digital-talent/blob/c2de193c35012e15b5606d3eebc0a659aabdec9d/api/config/notify.php#L18-L39

## 📋 Steps to Reproduce

1. Remove all `GCNOTIFY_TEMPLATE_*` keys from `api/.env`
2. `make refresh-api`
3. Trigger a notification
4. Observe both email and in-app notifications not creating an email or in-app notification

## 🙋‍♀️ Proposed Solution

- Add empty string to notify config env `template` default values. For example:  `'test_email' => env('GCNOTIFY_TEMPLATE_TEST_EMAIL', '')`

- add `$e->getMessage()` to:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/88b8489143ab034a39e0aeb18f0ffc1744b343c1/api/app/Observers/PoolObserver.php#L43
https://github.com/GCTC-NTGC/gc-digital-talent/blob/88b8489143ab034a39e0aeb18f0ffc1744b343c1/api/app/Observers/PoolCandidateObserver.php#L49

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] If there are no values set, only GC Notify emails fail to send
- [ ] add error message to log in `PoolObserver` and `PoolCandidateObserver`

**Comment by petertgiles** [comment]
@mnigh I wasn't able to replicate this.  Is it possible that you're testing off on a branch before we switched all GCNotify emails to queued notifications?

When I tried it, I got the in-app notification and the GCNotify email hasn't even tried to send yet because I never started queue working.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/64f38a95-1b2b-462c-aa3f-95b940a8d79f)
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/9c3c30fd-a568-4eb1-b016-1aef856350af)

It looks like the missing template ID was serialized as an empty string OK:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/fadae71c-9156-4bb4-b9dc-16ddf800703a)

**Comment by petertgiles** [comment]
@mnigh Thanks for the huddle.  Yeah, this can be replicated by commenting out the environment variable from the .env file.  I agree with the proposed solution to add a default value of an empty string to avoid crashing the notification creation.
