### ISSUE TITLE
🐛 Broken stories

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#10770]
## 🐛 Bug

Some stories are broken, finally uncovered now that Chromatic works again

## 🕵️ Details

https://61e099a1bb1465003a73d3ce-bzvcuoosib.chromatic.com/?path=/story/pages-pools-indexpoolpage-components-pooltable--default
https://61e099a1bb1465003a73d3ce-bzvcuoosib.chromatic.com/?path=/story/pages-searchrequests-requestpage-components-requestform--default

## 📋 Steps to Reproduce

1. Go to links

## 📸 Screenshot

Different environment like review or local exposes missing fields, use that to find clues

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/06b7b5c2-b940-4d18-9562-86dc38c38e27)

## 🙋‍♀️ Proposed Solution

Probably just need to add missing values to the two stories

## ✅ Acceptance Criteria

- [ ] The above stories work again, PoolTable and RequestForm
- [ ] With that, I think Storybook should have no more errors

**Comment by mnigh** [comment]
Some thoughts:

The `PoolTable` story is broken because the `me` query doesn't include `poolBookmarks`.

The `RequestForm` story is broken (see: https://github.com/GCTC-NTGC/gc-digital-talent/issues/10768) because the `communities` are not mocked (and can't be, based on how the component is currently written) in storybook. A solution for now would be to change `communities.find` to `communities?.find` anywhere in RequestForm.tsx
