### ISSUE TITLE
🐛 Screening and assessment filter count does not reset

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#11043]
## 🐛 Bug

After applying filters to the screening and filters page and then resetting it, the number in the button that counts the number of filters applied does not reset.

## 🦋 Expected Behaviour

Filter button count always reflects the current number of filters applied.

## 📋 Steps to Reproduce

1. Login as admin `admin@test.com`
2. Navigate to a screening and assessment page for a pool
3. Apply some filters
4. Then, reset the filters
5. Observe the button counter does not reset

## 📸 Screenshot

![2024-07-24_15-06](https://github.com/user-attachments/assets/5072c1c4-265b-4860-b2cc-d83f6d601959)

## 🙋‍♀️ Proposed Solution

Should be able to look into how we do it with the tables... maybe? :sweat_smile: 

## ✅ Acceptance Criteria

- [ ] Filter button count on Screening and Assessment page accurately reflects the currently applied filters

**Comment by esizer** [comment]
Seems like this might be more than just the filter count not resetting. I took a quick look and it appears we are treating operational requirement as an array even though it is a single value. 



![Image](https://github.com/user-attachments/assets/6b1458b3-ffee-4ddb-a06e-67c1577ccb40)

**Comment by yonikid15** [comment]
I think the Work preferences needs to be a ComboBox (MultiSelect) or a RadioGroup @Jerryescandon?
On the PoolCandidateTables we used the RadioGroup, should we switch to that? 
![image](https://github.com/user-attachments/assets/eb2e0bbd-d51e-4f7b-89b9-831476afaae8)


Also, for the filter number not resetting I think it's due to forgetting to remove the expriryStatus, suspendedStatus, and the poolId from the [FormValues](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/apps/web/src/components/AssessmentStepTracker/types.ts#L1-L12).

**Comment by Jerryescandon** [comment]
-  Definitely NOT a RadioGroup.
- Either a checkbox group or a combobox (multiselect) would be the ideal.

We should update the PoolCandidatesTable too

**Comment by yonikid15** [comment]
Oops sorry I meant to say CheckboxGroup :laughing: The PoolCandidatesTable's filter dialog uses a CheckboxGroup.
