### ISSUE TITLE
🔤 Filename for single candidate profile & application

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#11445]
## 🔤 Copy

Update the Filename for the single candidate profile and application (snapshot) downloads.

For profile the new filename should be (regardless of the language of the file):

`firstname lastname - Profile - Profil`

Example: **Gray O'Byrne - Profile - Profil.docx**

For the application the new filename should be  (regardless of the language of the file):

`firstname lastname - Application - Candidature`

## ✅ Acceptance Criteria

- [ ] New filenames for individual Profile download
- [ ] New filenames for individual Application (snapshot) download
- [ ] New filenames for anonymous application downloads (last name replaced with initial)
- [ ] Sanitize name strings for legal filename characters
- [ ] Test resulting files with downloading and pruning - ensure spaces in filenames are okay - replace with underscores if not

**Comment by esizer** [comment]
Just a heads up, it is generally good practice to avoid spaces in file names. While it is generally safe to have them, there could be issues with portability and save some users headaches if they want to do anything with the file other than reading it.

Also, since we know the language the user was using when requesting the file, should we only include one language in the filename? Or is it due to the file possibly being sent to users who speak different languages?
