### ISSUE TITLE
🐛 When sorting Pools by Publishing Date, null dates should appear at bottom when sorting descending

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#11535]
## 🐛 Bug

Currently, when you sort Pools by Publishing Date descending, unpublished pools appear at the top, THEN recently published pools, THEN pools published a long time ago. This isn't very useful, since when sorting by published, I'm likely to want to know which ones were published most recently. All the unpublished pools get in the way of finding those.

## 🦋 Expected Behaviour

Unpublished pools (NULL date) should appear at the end of the list when sorting by publish date descending.

QUESTION: should NULLs _always_ appear at the end of the list, whether sorting by ascending _or_ descending?

## 📋 Steps to Reproduce

1. Log in as admin
2. go to pools table
3. Sort by publish date
4. Observe that you have to pass all the unpublished pools before getting to recently published pools

## ✅ Acceptance Criteria

- [ ] When sorting pools by publish_date descending, null dates appear at end of the list
- [ ] QUESTION: maybe? When sorting pools by publish_date descending, null dates still appear at end of the list

**Comment by esizer** [comment]
Just a heads up on this one since I ran into it previously. This is determined at the database level and we don't have much control over it at the graphql level so it might be tricky since `lighthouse-php` doesn't expose this level of control.

The [default behavior in postrgres is to treat null as larger than all other values](https://www.postgresql.org/docs/current/queries-order.html#:~:text=By%20default%2C%20null%20values%20sort,independently%20for%20each%20sort%20column.) so will always appear at the top of the list when sorting descending unless specified otherwise.

**Comment by vd1992** [comment]
@esizer 

Do you have any ideas for how to approach this? Table sort would also be out of the question as internal sort is false for all server-driven tables.

**Comment by petertgiles** [comment]
Yeah, I'm not sure where to go with this one either.  When writing raw SQL it's easy enough to add [a NULLS LAST option](https://www.postgresql.org/docs/current/queries-order.html) but since we're using the lighthouse @orderBy directive we don't have that level of control.  I guess we could write a custom scope for the ordering?  That seems pretty like a heavy-handed solution to a fairly minor annoyance though.
![Image](https://github.com/user-attachments/assets/530f72d8-69b1-4b83-a4d6-f5b67ea31dd9)

**Comment by petertgiles** [comment]
I spent some more time looking at this and thinking about it.  I feel like we run into this "can only order by physical columns" limitation a lot.  I wonder if we should consider writing our own ordering directive?  We could add explicit null ordering to it. It would also  be nice to be able to specify expressions (limited to preset ones!) or scopes in a query.

The only short-term solutions I can think of are adding another custom ordering scope like the two already existing ones or add a calculated column to the database whose value is `coalesce(published_at, 2999-12-31)`.  I think I prefer the first.

**Comment by petertgiles** [comment]
Why don't they just filter out the draft status?
![image](https://github.com/user-attachments/assets/4bd62fe2-fa2a-4591-86e3-91e42ae1a34d)
