### ISSUE TITLE
✨ Send user browser and operating system information in support form for Freshdesk ticket creation

### ISSUE THREAD

**Issue by marc-donofrio** [GCTC-NTGC/gc-digital-talent#12072]
## ✨ Feature

After troubleshooting with freshdesk support, we determined that our custom help form blocks the automatic data collection needed to troubleshoot user issues with the platform and sign ins.

This data is usually displayed in the ticket header and does this automatically without the need to leverage the API labels.

### Data missing
- Browser version
- OS version

## 🕵️ Details

Here is what it looks like using the default help form:
![image](https://github.com/user-attachments/assets/ff3a51e8-6690-4a62-ae6b-dcf13b914ac4)

default help form: https://gctalent-talentgc.freshdesk.com/en/support/home

## 🙋‍♀️ Proposed Solution

> We can try seeing if we can forward the user agent header to freshdesk?

Does not work.

> Possibly custom fields?

Yes.

> We are already sending last-visited link, so we need to confer with @marc-donofrio to figure out why he's not seeing it. Should we send it in a different field?

No, Page URL is fine as is.

> We can try overriding the user-agent header our server sends with what it got from the user.

Does not work.

> If we send the browser and os version in custom fields, they won't appear how Marc expects them, but the info will be available.

That is fine with Marc.

> Don't bother asking Freshdesk if they can change their API.

Did anyway and they have no plans to change their API.

## ✅ Acceptance Criteria

- [ ] Freshdesk ticket submissions include User Agent string in custom field **User Agent**

**Comment by mnigh** [comment]
> We can try seeing if we can forward the user agent header to freshdesk?

I tried this and it did not result in the browser and operating system information rendering on the ticket (not a surprise, but see chat summary for confirmation).

> We can try overriding the user-agent header our server sends with what it got from the user.
> 
> If we send the browser and os version in custom fields, they won't appear how Marc expects them, but the info will be available.

I will confer with @marc-donofrio about this next and see what he thinks is useful.

> Don't bother asking Freshdesk if they can change their API.

I did any way, but we shouldn't hold out hope.

## Chat summary
me: i would like to know how to send the User-Agent data through a create ticket request via the api (https://developers.freshdesk.com/api/#create_ticket) so that the browser and operating system data show up in the UI for tickets like they do if being created via the freshdesk form.

freshdesk agent: I'm afraid that we wouldn't be able to pass the User metadata on the API payload to showcase the browser operating system and the freshdesk forms since the use case is that the ticket is being created by the API call and not the Support portal.

me: hi siddharth, thanks for your quick response. is there any way that freshdesk would expose those fields to the api in the near future?
something like adding an attribute to the POST request /api/v2/tickets that would be user_agent?

freshdesk agent: Noted, Matt. I will have this chat converted to a ticket and request the additional details over email and raise this with the product team to check the feasibility of this feature request.

**Comment by mnigh** [comment]
After discussion with @marc-donofrio, we will:

- create a custom field in Freshdesk called **User Agent**
- push [User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) string to Freshdesk custom field **User Agent**
