### ISSUE TITLE
Testing - Automated Github actions testing

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1265]
There is a need for more automated testing.  A good place to add some testing could be Github actions testing.  End-to-end testing there is not possible but some testing should be possible.

### To Do
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/1762

**Comment by patcon** [comment]
Fwiw GitHub Actions _can_ run e2e tests with cypress :) I set it up in another project and it works wonderfully:

https://github.com/compdemocracy/polis/blob/dev/.github/workflows/cypress-tests.yml

- we spin up the site in CI with `docker-compose up --detach`
- we run chrome headlessly, directly on GitHub Actions environment. Example: https://github.com/compdemocracy/polis/pull/1235
- video captures of all tests are saved as artifacts: https://github.com/compdemocracy/polis/actions/runs/1650968787

I've been messing around with the docker builds as I bide my time, so that hopefully I can borrow some of my scaffolding from that project :)

**Comment by tristan-orourke** [comment]
@patcon Maybe it's not well named, but right now we're using the `infrastructure` label to very specifically mean "relating to our Azure cloud hosted server infrastructure". I think `tests` and maybe `tooling` are appropriate for this one.

**Comment by petertgiles** [comment]
with #2719 and others I think this is done

**Comment by gobyrne** [comment]
Other devs (Matt & Brinda) agree with Peter. Closing
