### ISSUE TITLE
Node - permission denied

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1641]
It seems that node does not like to be run as root.  I think this is one of the issues @patcon is running into in PR #1449 as well.  It seems to not affect docker on a regular windows file system but does appear on a WSL or Apple file system.  I think our maintenance container should be updated to not run regular commands as root.

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/955063f5-67dd-463e-af96-3b6776751d6e)

**Comment by patcon** [comment]
to be clear, it seems to work locally on "docker for mac", but just gets complicated with edge-cases when running docker in CI environments. it's weird. something to do with docker shared volumes and mount types (but only with npm <7.x).

Any one of these would address the issue:
- pinning npm < 7.x resolves things without abandoning nvm
- using a docker image with specific node version (instead of nvm) resolves things
- somehow winding back use of shared volumes (seemingly a non-starter with our current dev process, though possible with some of the vscode flows mentioned here: https://code.visualstudio.com/docs/remote/containers)
- never running local scripts in CI resolves (this would seem increasingly limiting)

**Comment by petertgiles** [comment]
@patcon I think I like option #2.  Since it's a controlled environment I think it makes sense to bake in the version of node and npm on container creation.  Trying to run nvm without an interactive shell is real hassle.  It also really speeds up script runs since it doesn't have to test node and npm on every run.

I also really like the idea of VS code dev containers and have been playing around with them for a bit.  I'll work on a PR for that after this issue is closed.

**Comment by patcon** [comment]
Mind if I take a run at this? I think I've mostly gone through the steps while troubleshooting the CI environment :)

**Comment by petertgiles** [comment]
Haha, I was working on this on Friday and got a big chunk done, too.  You can finish it off if you want though.  I just pushed my branch called feature/optimize-maint-container so you can either use that and add to it or just review it for ideas.  I was going to remove devcontainer.json file since I'm not ready to included that in a PR yet.  And I wanted to add an environment variable to the container for workspace root and use that instead of all the relative paths in the scripts.

**Comment by patcon** [comment]
heh don't lemme step on your toes. i'll stick with review :) thanks peter!

**Comment by petertgiles** [comment]
Alright, no problem, I'll finish it off.  Not gonna lie, I'll probably crib a few things from your draft PR before submitting it. 😉  I like how you've made the failures quicker and have the switching between dev and prod.

**Comment by petertgiles** [comment]
I finished my code and was doing testing and ran into a big issue.  With a non-root user you're really dependent on the file ownership and permissions of the volume mounts.  When testing on Windows with WSL the files come in owned by the user that owns them in WSL, so UID 1000 for me.  In the script I can chown the work directories to www-data so that the PHP container can do its logging and stuff.  When testing on Windows on the native file system all the files come in owned by root.  So I can't do anything with them!  I think that strategy will only work if we're not using the files on the volume mounts directly and copy in our files to work with.  I think I might go back to running as root and see if I can find a workaround for npm.

**Comment by patcon** [comment]
Ah shoot. Well, since the "run as own user" is complicated, maybe we could just build a node base image? As I mentioned, `node:14.18.2-bullseye` works fine with nothing else changed in scripts.

But I know you mentioned we use ubuntu, so using `node:14.18.2-bullseye` doesn't work. That image is the equivalent of `debian:latest` with node v14.18.2 installed on it.

So while nodejs doesn't maintain an official node build for ubuntu, they mention in the issue queue that it's easy to use their build configs for ubuntu. This is because they base it off another base image called [`buildpack-deps`](https://hub.docker.com/_/buildpack-deps/), which _does_ offer an ubuntu flavour.

So we could use their debian template:
https://github.com/nodejs/docker-node/blob/main/Dockerfile-debian.template

Which is normally used to generate a bullseye (debian:latest) dockerfile like this:
https://github.com/nodejs/docker-node/blob/main/14/bullseye/Dockerfile

But instead have it use `FROM buildpack-deps:focal-curl` as the base image. (aka `FROM buildpack-deps:20.04-curl` bc focal = 20.04)

The above might sound complicated, but it's really just search-replace `s/bullseye/20.04-curl/g` and maybe some other minor troubleshooting. Then we're essentially building our own `node:14.18.2-focal` from the official node templates.

I'll give it a quick shot to see if it's as straight-forward as I'm thinking :)

**Comment by patcon** [comment]
K, it's here the dockerfile for ubuntu focal 20.04, if that's helpful: https://github.com/patcon/docker-node-ubuntu-test/tree/ubuntu/14/focal

(It's built from the original `update.sh` script in that repo, in case there's a need to update it later.)

```
docker build . --tag node:14.18.2-focal
```

Would be nice if ubuntu docker images maintained a "slim" variant for docker like debian does, but alas.

```
950mb node:14.18.2-bullseye
850mb node:14.18.2-focal <===
200mb node:14.18.2-bullseye-slim
120mb node:14.18.2-alpine
```

Our `infrastructure_maintenance` might look tiny at 250mb, but it's missing nodejs itself

No worries if this doesn't seem like the right approach!

**Comment by petertgiles** [comment]
I did some testing with one of the official node images (node:14.18.2-bullseye) but unfortunately I'm seeing the same issues with running node as root as I did with the Ubuntu image.  @patcon, are you using MacOS?  I would expect this issue to appear for you.  I'm seeing it with Windows with WSL2.  For example, the talentsearch `npm run h2-build` and `npm run dev`.  I think they both use npx which I bet is the issue.
![image](https://user-images.githubusercontent.com/8978655/148567026-d502be3b-9126-4f9a-8758-2b5b03b7f5e9.png)
I feel like we're getting closer!  Oh well, no rush - it's just tooling.

**Comment by patcon** [comment]
Everything works for me locally using my local Docker for Mac, it's just running Docker in GitHub Actions environment where it fails according to the criteria I mentioned above :) Checking `node:14.18.2-bullseye` now! (I suspect generally this issue is with an npm version and a certain type of volume mounting)

If you have a minute, for sanity, try removing `--upgrade-npm` from all `nvm` commands in `maintenance/scripts/setup.sh`. That should keep npm below 7.x, and if the error goes away, then we'll know we're talking about the same issue :)

**Comment by petertgiles** [comment]
Hmm, very interesting!  I pulled down the `node:14.18.2-bullseye` image again and left it at its default npm version of 6.14.15.  The `npm install` failed (log attached) but maybe that's due to having lockfilev2?  The `npm run h2-build` and `npm run dev` ran successfully though.

What does that mean?  Does npm 8 work differently under root than npm 6?  Or am I installing it wrong?  I'm running `RUN npm install -g npm@latest` in the dockerfile.

[2022-01-07T21_45_34_733Z-debug.zip](https://github.com/GCTC-NTGC/gc-digital-talent/files/7831553/2022-01-07T21_45_34_733Z-debug.zip)
.

**Comment by petertgiles** [comment]
When running in a rootless container there are so many permissions issues but when running as root there are node issues.  I think using the `php` container for maintenance and debugging is the right way to go though.  I've been stuck on this for a while so I'm going to throw it back for now.

**Comment by patcon** [comment]
Cool thanks! Feel free to share strategies you tried, or link to any dangling branch you were pushing to

I'll pick this up soon

**Comment by petertgiles** [comment]
Good luck!  My first try was feature/optimize-maint-container and then my second try was feature/another-try-at-containers.  I think using a separate maintenance container is a not great because of the file ownership and permissions conflicts between that container and the php container.  The permissions of files in a bind mount are really dependent on the underlying filesystem (Windows, Linux, Mac).  I think using the php container as an all-in-one environment for development is more reliable.    I found when running the container as root I was getting all kinds of node errors.  I think this is the right approach but I couldn't get it to work.  When running rootless then you were at the mercy of whatever file permissions you ended up with in the container.  If you were running the container on Windows then everything came up owned by root and you were stuck.  But at least node ran happily. 😔

I think using nvm is not great either.  Since it's a shell extension it doesn't work well for running automated scripts and you have to do things like source a profile file on login.  Since the container is a controlled environment I like the approach of manually loading in the exact version of node needed on image build, like my second attempt.  Not having to run `nvm use` in every script is a nice time saver too.

Another part of the puzzle is how to get the files inside the container.  If the script "created" the files somehow inside the container then you could control the ownership rather than relying on the underlying filesystem in a bind mount.  And file mounts are slow.  What if the working folders (node_modules, vendor, etc) were actually volume mounts?  That would speed it up and make them less vulnerable to permissions issues.  And the caches would survive image rebuilds.  Could we have a docker file that wold create the container and clone the files directly into its own filesystem?  This would be like the vscode devcontainers, right?  Lots of ideas....
