### ISSUE TITLE
Chromatic flags every PR

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1761]
The new Chromatic flow automatically notices any UI changes and blocks the PR until you manually approve the change.  It looks like we have a few unstable dates in our faked data and so it has flagged every dependebot PR this morning.  The faker should be updated so that every piece of data is generated the same way every time.

**Comment by patcon** [comment]
Ah shoot, it def wasn't intended to block based on those features we're not using :/

I believe I'd disabled the "UI Review" feature on my project, and that check didn't show up. @tristan-orourke should be able to disable it on the Chromatic project he set up as well. FAQ item here: https://www.chromatic.com/docs/review#can-i-disable-ui-review-if-id-prefer-not-to-use-it

![Screenshot_20220117-100115](https://user-images.githubusercontent.com/305339/149793055-9a4a086e-7aed-4708-9d3c-6ee402288d1f.png)

The "UI Review" check (a team review feature on their platform) should disappear, but "UI Test" should be there and show the number of changes in the italics text. (I have `autoAcceptChanges: true` set in workflow config, so that these detected diffs don't prevent the "UI Test" checks from returning "success")

**Comment by patcon** [comment]
(Removing visual noise in dates is still a great idea so that this "X changes detected" info can tip us to unexpected changes)

**Comment by petertgiles** [comment]
My bad, it doesn't actually block the PR.  You can ignore it and merge the PR anyway.  That's what I'm doing this morning. :-)  It does make me think, though.  Now that the PRs are getting "richer" with more checks and context that maybe we shouldn't be handling dependencies with 50 dependebot PRs every Monday.  There must be a better way.

**Comment by patcon** [comment]
Cool! Just wanted to clarify that "UI Test" (the per-component diffs on their platform) are different from "UI Review" (more advanced review interface/workflow on their platform).

- https://www.chromatic.com/docs/test
- https://www.chromatic.com/docs/review

I'm not totally clear in the distinction, but I think "review" is a whole multi-party process on their platform (with sign-offs rules for multiple people, analogous to GitHub's PR process) whereas "test" is just a single approve/disapprove toggle for each component.

So we can disable "UI Review" and still get the great diff viewing and warnings and even fails (if we do `authAcceptChanges: false`). Just a single approval for everyone on each component.

(This is my best working understanding, but I might be wrong!)
