### ISSUE TITLE
Merge static content on talent.canada.ca with rest of app

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1863]
# Description
We want to merge the content currently at talent.canada.ca with the rest of the app. The static content can remain unchanged, and should become the site landing page.

The talentsearch landing page can be removed. /search, /request and /en|fr/search and /en|fr/request should still direct to talentsearch, but other urls should direct to static content folder. (frontend/public?)

Links for Terms & Conditions and Privacy Policy, in talentsearch and in admin, should point to the static content pages.

**Comment by patcon** [comment]
No urgency on this, but: Thoughts on using a simple node express app to serve static files (and maybe even proxy routes to other apps as needed)? Would our staging environment allow this?

The idea would be to keep apache/nginx config dead simple (just point it to this slim expressJS app used for routing) and instead handle routing, proxy and even header-setting logic more in that app layer instead of more arcane nginx/apache config.

The bonus is that it later supports dynamic data (e.g. envvars set at _runtime_, rather than hardcoded at docker's _build time_) to be swapped in during the serving of static content. Some one container image could be deployed to all environments, without rebuilding for each. For e.g., say there's an oauth client ID or a subdomain that differs between staging and prod, if that's hardcoded during docker build, then the same container can't be deployed in both envs. But if the config is swapped in to replace a token like `__SERVER_DATA__` by this simple express app (while it's serving the static files), then that can be set as needed via envvars.

Explained here (we're not using create-react-app, but they're just authoritative docs): https://create-react-app.dev/docs/title-and-meta-tags/#injecting-data-from-the-server-into-the-page

**Comment by tristan-orourke** [comment]
@patcon I think that sounds great, but we don't currently have approval to install Node in our production server. Its PHP or static files, for now.
