### ISSUE TITLE
All - Create fancy 404 pages

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#1904]
El Jerbo (AND BROOKE) will provide some fancy design here

### Normal Mode

<img width="934" alt="Screen Shot 2022-10-06 at 4 05 29 PM" src="https://user-images.githubusercontent.com/305339/194348987-030d4a5f-995f-45fd-9580-cf0e40780e66.png">

### Dark Mode

![Image](https://user-images.githubusercontent.com/100953238/194360869-25dbddec-e62b-46bc-bf8f-ab3311b44030.png)

[Wireframe](https://www.figma.com/file/fsUTEm09c40qponRarmdGD/404-page?node-id=208%3A702)

## Acceptance Criteria
- [ ] "Report missing pages" goes to support page `/en|fr/support`. No special treatment or pre-filled things. 
- [ ] Homepage goes to homepage.
- [ ] host at /en/not-found and /fr/not-found (avoid 404)
- [ ] routing sends unknown urls to this page
- [ ] dark mode works

**Comment by petertgiles** [comment]
@Jerryescandon

**Comment by patcon** [comment]
To clarify: this will prob involve apache config changes as well

**Comment by patcon** [comment]
@Jerryescandon Since it will redirect from a page that didn't exist, could the design optionally include the link we came from, so users have more info to correct issue or communicate?

Some benefits:
- allows users to spot a typo ("oh, i didn't copy the full url")
- helps with user support ("yes, i'm on the error page now, but I'm not sure where I was when things went wrong. I clicked a button and now I'm on example.com/404")

Dev consideration: It might need to be fetched differently depending on whether redirect was executed by react app (can store in history push state) or apache.

**Comment by patcon** [comment]
Oh hey, the above assumes that we're redirecting to a page like `/not-found` or `/404`, but maybe that's not the best way to do it. Might still be helpful to show the url, but less important if not redirecting.

http://talent.canada.ca/some-non-existent-page => http://talent.canada.ca/not-found

At first, I was thinking a 404 url redirect might make it easier to keep bad links out of search engines, but could prob just use <head> meta tags to keep them unindexed. (potential acceptance criteria)

The only benefit to redirects that I can think of is that it might be helpful for analytics, since they'd show up very prominently in Google Analytics, and we could see spikes and maybe trace path.

Another Q: Is "report missing page" just a link to email with pre-filled subject (and maybe the page url)? Or are you imagining something else?

**Comment by Jerryescandon** [comment]
> * allows users to spot a typo ("oh, i didn't copy the full url")

We would definitely need to make all links more readable (by humans) for this to take effect.
But I agree that the best use of 404 is to assist with tech support, building those things into the page is a good start.

**Comment by BrookeCameron** [comment]
https://www.figma.com/file/fsUTEm09c40qponRarmdGD/404-page?node-id=208%3A702 

404 page!! will be demoing at sprint!
