### ISSUE TITLE
Toast notification when completing last required form

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1933]
# Description
We want to listen on the current state of application profile, and when it goes from being incomplete to being complete we want to display a toast notification saying as much.

We don't know which page the user will be on when this happens, so we want the toast to work consistently whether they're on the main profile page or any of the forms. In fact, the toast itself should persist when navigating between them.

Remember, triggering a toast is easy. Ensure our <Toast> component is somewhere in your component hierarchy (probably near the root, shared between the entire SPA), and then call:
```javascript
import { toast } from "react-toastify";
toast.success("my message");
```

Where and how to listen for the application status change is left to the implementer.

# Acceptance Criteria
- [ ] No storybook necessary
- [ ] Jest tests
  - [ ]  ???

**Comment by tristan-orourke** [comment]
Might be easier to run this on each submission?

**Comment by tristan-orourke** [comment]
Needs copy for the final success notification @Jerryescandon

**Comment by vd1992** [comment]
@tristan-orourke 
I was trying to give this some thought to think of how it would even look. 

The when is simple enough, upon form submit the user is redirected to the profile page with a success toast, so that is when this would trigger. 
Might need to watch how multiple toasts occurring (submit success + profile completion success) look. Whether it looks weird.

The how is much trickier, the requirements I think
- trigger the one time upon completing the set of required info, so does not repeat upon editing earlier info or adding something optional
- tracking of profile info completion, so as to tell what the last form is, given a user may fill in random order, the bottom form may not be the last
- the last form state must be known in whichever form it exists, so it could be any, and on successful completion maybe override the normal toast

Possible methods
Form State
- some state that exists, that is carried into all forms, enabling a form to tell if it is the last one to fill
- requires appending stuff to all forms

Session Check
- store complete/not locally for user, check upon loading Profile page whether this value can be flipped to true
- function runs upon state flip, so onChange, won't repeat, and then clears local session info
- requires storage local/session side which could introduce tricky bugs

**Comment by RVany** [comment]
Meet with Brinda
- We don't need a new component!

**Comment by Jerryescandon** [comment]
"All required fields are complete.
You can now **change your status**. "
