### ISSUE TITLE
Check Nonce in id_token response

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2086]
Similarly to how we must include a random `state` string in our request and verify that it comes back the same, we must include a random `nonce` string in our request and verify that it comes back the same in the id_token.

https://openid.net/specs/openid-igov-openid-connect-1_0-03.html#rfc.section.2.1

**Comment by tristan-orourke** [comment]
This will involve the file `frontend\admin\app\Http\Controllers\AuthController.php` (probably exclusively)

**Comment by petertgiles** [comment]
@tristan-orourke From the openid doc it seems like the nonce has to be generated in the browser and then verified in the browser when the ID token comes back.  I think this isn't just an AuthController update.  I'm not clear yet how the nonce gets from the browser to SiC.  Do we just call http://localhost/admin/login?nonce=12345 and then forward that on?

**Comment by vd1992** [comment]
reading further down in the document to section 3.1 there is some stuff about the nonce being pulled out of the ID Token
https://openid.net/specs/openid-igov-openid-connect-1_0-03.html#rfc.section.3.1

this article might be relevant but it's with a bit of a different environment
https://codeburst.io/openid-connect-client-by-example-76caf6dae55e

So I'll try to start things off by including Id_Token in the Auth Container and Client Provider stuff since it isn't even present there at the moment.
Somewhere there a nonce needs to be generated

**Comment by vd1992** [comment]
will delete previous work in \authcontroller
add id tokens variables elsewhere
