### ISSUE TITLE
Add a Display Name field to the experience interface

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2139]
New issue from discussions in #2124 and #1925.  Each type of experience has a different way of titling itself in a list.   Can we add a field to the experience interface to simplify API requests for a list of experiences?

**Comment by tristan-orourke** [comment]
> Hopefully this can be implemented by logic in the models and not need to change the underlying database structure of the experience tables.

For sure! We can use [Laravel Accessors](https://laravel.com/docs/9.x/eloquent-mutators#defining-an-accessor) to add virtual properties to the models.
The only hiccough I can think of is if this field needs to be localized, I'm not sure how to handle that. Do any of the display names involve dates? Otherwise we're probably fine, since users fill out experiences in the language of their choice.

**Comment by tristan-orourke** [comment]
According to [new designs](https://github.com/GCTC-NTGC/gc-digital-talent/issues/1925#issuecomment-1054640559), each experience block may have multiple versions of the display name, and some of them involve text that should be localized ("at", "issued by"). So now I'm leaning towards keeping this on the frontend.

**Comment by petertgiles** [comment]
Good enough for me.  Let's not pursue this.
