### ISSUE TITLE
Put together Onboarding docs

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2145]
📝 Ongoing **Call Notes:** http://go.talent.c4nada.ca/onboarding-notes
✅ Experimental **Trello On-Board:** http://go.talent.c4nada.ca/onboarding
💬 **Slack channel:** [`#org-onboarding`](https://app.slack.com/client/T5ZFRSQ3V/C036N7GKEH3)

# Description
Put together the list of everything involved in onboarding a new dev.
Put together the list of everything involved in onboarding a new gov employee.
Put these somewhere easy to reference and use.

### To Dos
- optional: about CDS onboarding (found via CTRL+F "onboard" in github repo's [blog directory](https://github.com/cds-snc/digital-canada-ca/tree/main/content/en/blog/posts))
  - [ ] read [Making a great first impression: Onboarding matters](https://digital.canada.ca/2019/07/29/making-a-great-first-impression-onboarding-matters/) (June 2019)
  - [ ] read [How we’re trying to make virtual onboarding better](https://digital.canada.ca/2021/06/09/how-were-trying-to-make-virtual-onboarding-better/) (July 2021)
  - [ ] review https://github.com/cds-snc/talent website

**Comment by patcon** [comment]
Demo: https://go.talent.c4nada.ca/onboarding

**Comment by patcon** [comment]
cc: @vd1992 (who's also taking personal notes on the onboarding experience)

**Comment by vd1992** [comment]
before grabbing an issue, maybe the Docker + run (current) project locally step should be put there, the readme instructions were pretty good in getting things up and running
maybe just a small aside from how enabling virtualization is an on-boot thing that may vary slightly based off your PC

**Comment by vd1992** [comment]
also, make sure to have some resource to keep track of passwords, you're going to have a lot of them!

**Comment by patcon** [comment]
Added some links to the top of this issue. I've been queueing up discussion items in the notes doc, for our next cowork call to work on this :)

Noting that there's a part of this that is "forever" work, since our onboarding is kinda a living document that will always be under update (yes?) but maybe we could set a solid endpoint for this ticket? Here are some proposed todos that we could use to close this :)

> ### [Proposed] To Dos
> - [ ] build MVP Trello On-Board
> - [ ] document (contribution process, etc)
> - [ ] get feedback from two existing employees
>   - [ ] incorporate feedback
> - [ ] success: run first new hire through the onboarding tool
>   - [ ] incorporate feedback
> - [ ] stretch goal: create version-controlled backup of trello, to better track changes
>   - reference: https://github.com/edgi-govdata-archiving/overview/issues/171
>   - trello backup tools exist. yml would be best, for cleaner diffs
>   - auto-commit to a github repo. workflow to run. daily schedule?
> - [ ] ... something else?

How's the above look? If looks alright, I can move into issue body (happy to tentatively put it up there and tweak/cull it later!)

**Comment by esizer** [comment]
## Summary

I'm going to put together some thoughts on the onboarding process while doing my best to remember that it is a WIP. Overall impressions is that it is fairly well thought out and easy to follow. Most of my concerns are with order and clarity.

## Slack Channels

The first few cards are a perfect introduction and it seems the major missing bit is a general overview of Slack. When getting up to speed I was added to a few slack channels but unsure of what ones to join myself. Based on the card description, it seems the intent is to add some clarity to this. Key would be to highlight the key channels such as `#devfam`.

## Optional Tasks

When first going through the tasks, the labels were all collapsed for me and it took a while for me to realize that some tasks were optional and labelled as such. I believe this is default behaviour for Trello afaik but for those who may not have experience with Trello or just bad at it like myself, maybe include a card near the start that links to the [Trello 101](https://trello.com/en/guide/trello-101#what-is-a-board) page? This may be overkill, especially if this is the only use of Trello new employees will experience.

## Order of Operations

The major one here which I believe @vd1992 mentioned is that the board tasks you with grabbing an issue *before* you have the repo cloned and running locally. It may be beneficial to move this to near the bottom of the list. Something more along the lines of following which is the order I completed outside of getting a walkthrough of the code before doing onboarding:

 1. Join the GitHub organization
 2. Set up ZenHub
 3. Read all the project READMEs (previously Grab your first GitHub issue)
 4. Review our Definitions of Done & Ready 
 5. Review our Style Guide
 6. Get a walkthrough of the code
 7. Take the Docker for a test-drive
 8. Learn about our Hydrogen command-line tool
 9. Previously Grab your first GitHub issue

IMO, this order helps get an understanding of the codebase and workflow before anyone starts to decide what their first task will be. I naturally skipped task to grab an issue and reviewed the code and READMEs to get a better understanding before I felt comfortable enough o assess what I could work on initially.

## Clarity of Tasks/Issues

Some tasks, at least for myself, lacked clarity or resulted in some issues. This is most likely just a side effect of it being a WIP but I will mention the cards I had challenges with to call attention to the ones that may need to be looked at.

### Request for Equipment

I do not believe this is an issue with the teams on boarding, rather my experience with onboarding at the government in general. The process of requesting and receiving the equipment was smooth and nearly effortless. However, once I received the equipment I was, and admittedly still am, completely clueless on how to setup/operate it. I've been trying to seek help from other government employees and the IT help desk but past opening Outlook and reading the boilerplate welcome email, I haven't really gotten anywhere. 

I'm not sure if this is the responsibility of this team or not, but maybe a list of what to do when you get the equipment could be helpful.

### Inviting Someone to Apply

This is a great task and awesome to encourage new hires to do in hopes of growing the team. Though, I do believe it might be too early in the process for new hires, maybe just adding the "Optional" label to this would be appropriate.

### Password Management

Having a password management strategy is an excellent idea and I think we could add some suggestions for this. I personally use LastPass and maybe we can recommend some applications to encourage some sort of best practice.

### GC Devops League

This could be an issue with my reading comprehension or inability to understand how slack works to this day but, I have yet to find a way to actually join this slack channel. It should be emphasized that after using slack for 6-7 years I still have trouble with basic functionality like threads so it may just be a me issue.

### Apply for Coworking/Sign telework agreement

I see there are labelled as a WIP but since they are also not labelled as optional, I feel like I am missing something crucial and am not sure what to do here. I think before the next use, these cards should be resolved or marked as optional (if that is the case).

### Broken Links

 - Team Member README
 - Join our Gather office

**Comment by mnigh** [comment]
> Put these somewhere easy to reference and use.

@tristan-orourke i see some really great insights from both @vd1992 and @esizer in this issue. Has there been any more thought into where **somewhere** might be? 😉

**Comment by patcon** [comment]
based on convo in retro: my thought was that labels for "audience" might allow all the cards to be in one place (with one thoughtful order) for both GoC internal tasks and public ones to be in one system and not split between

**Comment by esizer** [comment]
Is this still something we are working on? It is fairly out of date and hasn't seen any movement in nearly a year 😅

**Comment by tristan-orourke** [comment]
> Is this still something we are working on? It is fairly out of date and hasn't seen any movement in nearly a year

That's because no one wants to work on it (especially me) not because it shouldn't be done...

**Comment by mnigh** [comment]
> > Is this still something we are working on? It is fairly out of date and hasn't seen any movement in nearly a year
> 
> That's because no one wants to work on it (especially me) not because it shouldn't be done...

Maybe a GitHub issue is not the right place for it though? From a coding perspective, we have `README.md` and `CONTRIBUTING.md` files in this repository to get someone started. The other onboarding information seems more HR-related and this repository is likely not the appropriate vehicle for its dissemination.

**Comment by vd1992** [comment]
Well, closing due to lack of progress and possibly not best place to track it
