### ISSUE TITLE
Refactor Docker

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/gc-digital-talent#2217]
Some loose thoughts as I think on this:

- inspiration of style will be https://github.com/compdemocracy/polis/blob/dev/docker-compose.yml
- we want to do e2e testing. this would be simpler with a more "conventional" docker setup, that we could run in GitHub Actions environment
- docker conventions of note
  - one process per container (php, apache, etc)
  - one dockerfile per section? (admin/talent/common)
    - potentially multistage build for static builds, ie single dockerfile (for react build)
- stretch goals (prob not in this PR)
  - deploy container image artifacts to github container repo
    - this would allow the containers to be built once, and then pulled into other jobs (no rebuild) for parallelized testing or other stuff
    - demo: https://github.com/g0v-network/polis/blob/dev/.github/workflows/release-docker-images.yml
      - https://github.com/orgs/g0v-network/packages?repo_name=polis
- great feature on smaller docker images: https://symflower.com/en/company/blog/2022/complete-guide-on-shrinking-container-images/

## Prior Art
(Potentially useful when this is revived)

- https://github.com/GCTC-NTGC/gc-digital-talent/pull/2451
- https://github.com/GCTC-NTGC/gc-digital-talent/pull/2945

### To Do
- [x] https://github.com/GCTC-NTGC/gc-digital-talent/issues/2324
  - [x] read peter's [docker manifesto](https://talent-cloud.slack.com/files/U02J583KLGP/F038HCD796E/docker_manifesto.md)
    - [x] @petertgiles  🙃 
    - [x] @patcon 
    - [x] @brindasasi 
    - [x] @JamesHuf 
    - [x] @gggrant 
    - [x] @RVany
    - [ ] others? [add yourself]
  - [x] schedule time -- @petertgiles [FRI MAR 25 @ 2-3pm]
  - [x] invite all interesteds [from thread](https://talent-cloud.slack.com/archives/CB424V61J/p1648129419092389) -- @petertgiles 
  - [x] do the call! -- all
- [x] optional: summarize goals as decided?
- [ ] optional: split out tasks/tickets/accept-criteria (nearterm, longterm, etc)
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/2327

**Comment by petertgiles** [comment]
Result of planning session 2022-03-25:

# Docker Manifesto

## Goals
1. An easy way for new hires/contributors to get a working state
2. A reliable way for existing developers to reset their working state
~3. A reliable way for owners to deploy updates to production servers~ (not necessarily a problem with docker, deployment right now has nothing to do with docker)
4. A useful platform for automation

## Priority Requirements
1. Must work on Windows, Mac, Linux
2. Must work on Github Actions

## Secondary Requirements
1. Should conform to Docker best-practices
2. Should require few or no other dependencies
3. Good integration with VS Code

## Nice-to-haves
1. Support constrained environments like TBS Azure VMs, Codespaces, GitPod
2. VS Code DevContainers
3. Easy way for Windows developers to use WSL2
4. One-click (or few-clicks) to check out and set up a branch for review.
5. Support for debugging PHP and Typescript
6. No build-time vertical setting changes - need single deployment artifact, but not a blocker since we can build multiple artifacts

## Questions About Approach
- One container per project? - yes, seems good
	- Does frontend get one container for one per-subproject? - one for all of frontend is probably fine (maybe admin on its own?)
	- Do we need two docker files per project?  One with dev dependencies for development and one without for deployment to production. - containers are just for dev, could use flags/options to control
- Docker Compose is only used for development, right?  Production deployment should not use the compose file? - not using docker in production, could be interesting though
- We should try to get rid of file mounts for node_modules, vendor, and storage to help speed up runtime and cache between branches and use volumes? - need to have a good experience figured out to enable this - task runner? - but would improve performance
	- How do we avoid caching issues with volumes when switching branches? - should be pretty quick
- Project containers should fully bootstrap themselves up on build - will probably be some stuff that can't be done this way, like auth - there should be a stage 2 including seeders, auth, etc
	- How do we avoid layer caching issues when building a new container?
	- How do we get auth secrets over to the api project on setup?
	- Can we get ride of the infrastructure folder and have each project set up their own container independently?
- How to solve the never-ending .env file issues?  Validation on setup? - Try to minimize Docker's use of .env files, have docker copy in .env files, try to reduce number of .env variables inside files, check out node convict
- Do we use containers with root user or rootless containers? - just use root, should be solvable
	- Filesystem binds in Windows will come in owned by root but not on Mac or Linux.
	- Can we get node to run as root properly?
- Can we get rid of the maintenance container? - yes probably, use devconatiner, makefiles, etc to help dev experience
	- Would we shell into the container of each project to run things like `php artisan` or `npm run watch`?
	- If we have node_modules etc bound to internal volumes is there even anything we could do outside each container?
	- What role would a vs code devcontainer have?
- What role does the php container have if each project has its own container? - get rid of infrastucture folder and have a separate frontend routing folder, apache routing
	- Do we need to have a infrastructure folder then?
	- How do we handle top-level htaccess/routing stuff without it?
- Can we get rid of the maintenance scripts and just teardown/rebuild a container every time?
- How can we support people not using VS Code - makefiles inside containers?

**Comment by patcon** [comment]
@petertgiles in backlog refinement, others wanted to know if we could easily handle https://github.com/GCTC-NTGC/gc-digital-talent/issues/2327 -- seemed easy enough, so added it to todos above :)

**Comment by patcon** [comment]
minimal base image for ubuntu that may be helpful in future (but likely not): https://github.com/phusion/baseimage-docker

**Comment by patcon** [comment]
hyperlink gifts from @petertgiles --

- list of all docker blog posts: https://nickjanetakis.com/blog/tag/docker-tips-tricks-and-tutorials
- https://github.com/nickjj/docker-web-framework-examples/blob/master/phoenix/docker-compose.yml
- watch files pattern: https://nickjanetakis.com/blog/best-practices-around-production-ready-web-apps-with-docker-compose
- avoid mounting node_modules: https://nickjanetakis.com/blog/docker-tip-75-how-to-avoid-node-modules-in-your-volume-mounts

**Comment by patcon** [comment]
lazy share: https://doc.traefik.io/traefik/providers/docker/ (re: docker watch ⌚ )

**Comment by brindasasi** [comment]
check with Tristan when you start working on it @patcon

**Comment by tristan-orourke** [comment]
A way to handle live reloading within docker containers: https://betterprogramming.pub/live-reloading-with-docker-compose-for-efficient-development-356d50e91e39

**Comment by petertgiles** [comment]
> A way to handle live reloading within docker containers

For sure, this is part of my motivation to combine our webpack builds.

**Comment by mnigh** [comment]
@petertgiles are we still looking to refactor docker?

**Comment by tristan-orourke** [comment]
No, this isn't something we're really thinking about anymore.
