### ISSUE TITLE
Spike - Investigate how to avoid passing tokens in query parameters

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2376]
# Description
During the login process there is a GET request that contains the access token, id token and refresh token in the URL query string.    Having this information in a query string makes it more likely to be logged and observed by an attacker. We've been recommended to pass these tokens in a POST request body instead.

This is not currently an option because our frontend code is hosted as static files. We should investigate a workaround or alternative.

**Comment by gggrant** [comment]
Timebox: 3 days.

**Comment by petertgiles** [comment]
I did a bit of googling and thinking about this and considered some ideas - from simple to disruptive.

- Can we keep the redirect the same but add the tokens somewhere else other than url parameters?  It sounds like it is not possible to add headers to a redirect but maybe cookies?  Are cookies reliable enough?  Do many people have cookies disabled?

- What if the backend saved the tokens but did not pass them in the redirect but just notified the frontend that they were there.  The frontend would then have to make another request to get them.  Probably not too hard to implement but it adds non-standard complexity to an already complex process.

- It sounds like the "proper" way to authenticate an SPA is not to go through a backend but have everything in the frontend application.  Since it is a public client we would not use the client secret but instead use the PKCE extension.  This would be a pretty bit refactor!

- If we decided to switch to a pure frontend auth system would be want to home-brew it or use an existing library?  We tend to do the former on this project but this may be a complex enough system to lean on a mature dependency if we can find one and integrate it with urql.

**Comment by brindasasi** [comment]
team to take a look at this comment today and provide suggestions

**Comment by tristan-orourke** [comment]
If we switched to frontend flow with PKCE, I think it would make sense to use a library if possible. Just took a quick look - it seems hard to find much, but I did find this https://www.npmjs.com/package/@bity/oauth2-auth-code-pkce

**Comment by petertgiles** [comment]
This is the one I was looking at.: https://github.com/authts/oidc-client-ts .  It seems like it's a fork of this mature but dormant project: https://github.com/IdentityModel/oidc-client-js .

**Comment by tristan-orourke** [comment]
Asked Security for a suggestions:

> We were asked to find a way to avoid passing an access token via url query parameters.

> We currently do this because we wanted to use Oauth 2.0 Authorization Code Flow, allowing us to keep a client secret on our backend server, but part of our app lives in a client-side Single Page Application (SPA). Currently when the server has retrieved an auth code, it redirects to the client SPA with the token in a url query parameter. We’re unsure how else to pass the token from the backend server to the SPA.

>
> An alternative is to implement authorization entirely on the client SPA, using Authorization Code Flow with Proof Key for Code Exchange (PKCE) ([auth0.com](http://auth0.com/)). In this oauth flow, PKCE replaces use of a client secret, which can’t be stored securely in the frontend SPA. In my previous reading, this oauth flow was considered less secure than the Auth Code flow using a client secret.

>
> Aoun, Tony We want to ask your security advice: would it be preferable to implement frontend Authorization with PKCE, over our current approach of retrieving an access token using a client secret but then passing the token in a url query parameter?

**Comment by tristan-orourke** [comment]
Received this response:
> The issue with passing any kind of authentication token in a URL query string is that it can get logged by intermediary devices and someone that has access to those logs may be able to obtain and re-use the tokens.  The easiest way to avoid this is to not put anything sensitive in the URL query string, but sometimes that is unavoidable.  A compensating control for this is making it harder to re-use that token that is passed, so that the impact of someone accessing it or using it is less.  This could be done by reducing the time the token is valid (i.e. if used to generate another access token, the validity length of this token could be reduced), or by requiring other data than just the token for it to be used by someone else.
> 
> Hope this helps provide some clarity on the issue and possible mitigations.

**Comment by brindasasi** [comment]
we use short tokens ( 5 mins)  and should be ok for now. But we feel front end auth with PKCE would be longer term solution. @petertgiles to create a new issue for that.

**Comment by brindasasi** [comment]
we would create a new issue to continue with PKCE
