### ISSUE TITLE
ITP Homepage

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#2419]
We got it back from Vincent Design.
Copy changes requested by ESDC.

It's back with Vincent Design now.

**Comment by gobyrne** [comment]
Still some work remaining before it goes to dev:

In terms of what’s missing, we know what to do with the “Apply now” and “Call Us” buttons, but here are the other things:

1. Mobile View. Essentially, what does the page look like on a small screen? Ideally we would have asked Vincent design for this as well, but it’s pretty easy for our designers to do it. We will assign it to one of our designers to be completed in time for your review before the next sprint starts. Mobile view mostly re-arranges the content to fit well on a narrower display. The actually content shouldn’t change.
2. Learn more buttons. There are two “Learn More” buttons in sections discussing the apprenticeship program. These will either need to be removed or we will need to know what they link to. If they should open “pop ups” or a separate page, we will need to know what content goes inside.
3. Placeholder text (lorem ipsum). There are still 2 places with placeholder text that need to get filled in.
4. New text. Vincent design added a little bit of new text for the sections that got changes. This text needs a review.

**Comment by MCommonda** [comment]
Areas under Review:

**Who Is the Apprenticeship for:**

The priority is to identify and to hire based on passion and potential, rather than for credentials. Apprentices will be selected based on meeting the following requirements:
•	Self-declaration as First Nations (status or non-status), Inuit, or Métis
•	Minimum of a high school diploma or GED
•	Demonstration of required behavioural competencies, through work and life experience, as outlined in the Treasury Board Secretariat’s job competency profile
•	A demonstrated interest in the area of IT (either personally or professionally)
•	A commitment to learn, both on the job and through online or in-person instruction.
A national area of selection for the appointment process will be used. Apprentices are considered full-time term employees subject to all applicable supports and measures within the Public Services Employment Act.

If you are an Indigenous person from Canada with a passion in the area of IT, then this Apprenticeship is for you!

**Learn More (button appears two times throughout the homepage)**
(The function of this button can be a pop-up as well that can include the latest FAQ content)
-	Will ask Brooke to come up with a design that incorporates the VD aesthetics found throughout the page


**IT Apprenticeship Program + The Indigenous Talent Portal 
	How It Works**

We are working hard to ensure that the IT Apprenticeship Program is a safe space for Indigenous Peoples. 
1.	 Self-Identify (Or Self-Declare?)
a.	Applicants are asked to self-Identify via the Honesty Pledge which was designed by the Indigenous community. 
b.	Non-Indigenous people can identify as allies, and will be directed to opportunities which are available to everyone via (do we insert link to GC talent and/or GC Jobs here? – need to confirm)

2.	Provide Information about yourself
a.	We want to learn about you and about your interest/passion fin the area of IT!
b.	We’ll invite you to create a profile which will be saved and submitted as your actual application.

3.	Submit your Profile as your Application
a.	You be prompted to confirm the information you provided.
b.	Upon submission, a team member will contact you within 3-5 business days.


**Remove Call-us Button**



**Add contact info and text to create pop-up for Contact Us buttons**

"Please send your CV and cover letter explaining your passion for IT and why you're interested in joining the program to: [esdc.pda-iap.esdc@hrsdc-rhdcc.gc.ca](mailto:esdc.pda-iap.esdc@hrsdc-rhdcc.gc.ca). A team member will contact you in 3-5 business days."

We want to let you know that in the meantime, updates are being made on this site that will allow Indigenous Peoples who are interested in joining the IT Apprenticeship Program to apply online. 

Thank you for your interest in this Program. We look forward to hearing from you!"

**Comment by MCommonda** [comment]
Also needed is a mobile view of the Homepage. Meeting with Brooke @BrookeCameron today to discuss.
