### ISSUE TITLE
nodejs version

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#2629]
Project currently uses a version of nodejs, 14, that is on Maintenance LTS and will be [end of life in a year from now](https://nodejs.org/en/about/releases/) (2024-04-30).

### Questions
1. Is there any reason (e.g. production server image being inflexible), to stay on this version (14) or can we update to Active LTS (16) or Current (18)?
2. Is there any way to use a global environment variable for these values so that there is a single source of truth?
3. Is there any way to pull this value from somewhere we can actually get the latest stable version of nodejs instead of a statically coded value?

### Files

- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/infrastructure/maintenance-container/Dockerfile#L11,L12
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/infrastructure/deploy.sh#L67
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/auth/package.json#L4
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/admin/package.json#L20
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/talentsearch/package.json#L20
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/indigenousapprenticeship/package.json#L20
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/common/package.json#L40
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/auth/.nvmrc#L1
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/.nvmrc#L1
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/admin/.nvmrc#L1
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/talentsearch/.nvmrc#L1
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/indigenousapprenticeship/.nvmrc#L1
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/common/.nvmrc#L1

**Comment by vd1992** [comment]
between this, the react upgrade, and now jest upgrade
a refactor/upgrade sprint cycle might be something to have in the cards

**Comment by patcon** [comment]
This is generally a great idea!

(1) The more test coverage we have, the better I feel about this. But can't hurt to try. I suspect there would be some pain of upgrading packages, but that's the price.
(3) I don't think we actually want to do this, as we want to have the version "pinned" in version control, and not floating or upgrading until we officially ask for that. Docker images are tagged with less specific versions (e.g., "node:14" instead of "node:14.1.2") but that is more for experimentation and local dev, and imho letting the versions float isn't as "helpful" as it might seem :)

(2) In theory, `nvm use` looks backward up through the tree until it finds an `.nvmrc` file, so no reason we can't just keep it in root dir.
    - With docker, there are some complications, since docker currently uses nvm for versions. And docker doesn't see stuff in root dir, because it's outside its "build context" (aka, all the files sent to docker). There are some work-arounds (moving build context or just copying gitignored files into build context before running docker commands), but probably better to just wait because...
    - In #2217, we're trying to get away from using nvm in docker container, as it should be in the image itself. After that, it will need to be specified once in each Dockerfile, but could be pulled up into ARG passed in from `docker-compose.yml`.

We can probably get this down to .nvmrc in the root (more as "documentation" and helpful for when ppl want to run commands locally), and once in docker-compose.yml (but still mentioned in each node-related Dockerfile as a default, though technically overridden). Having it in each package.json could probably be removed, and we'd maybe just lose some warnings that have been helpful sometimes.

**Comment by tristan-orourke** [comment]
1. I agree that there's nothing keeping us from upgrading to 16.
2. Defining a version in one place is definitely better.
3. Using latest instead of a static value seems like a recipe for confusion/errors.

**Comment by tristan-orourke** [comment]
Break 1 and 2 into seperate issues, ignore 3.

**Comment by mnigh** [comment]
As requested by @tristan-orourke, 1 and 2 broken into separate issues:

- #2757
- #2758
