### ISSUE TITLE
Restrict how graphql errors appear to users

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2815]
We probably do not want to show the full graphql error exception message to uses. 

Question: what SHOULD errors in production show? I can think of a few broad error messages that would be reasonable: you're not logged in, you don't have permission to do that, your input is malformed, your request is malformed, etc. We could capture errors in a [Lighthouse error handler](https://lighthouse-php.com/master/digging-deeper/error-handling.html#registering-error-handlers) and transform the message into whatever we want.

Question: do we still want to make the full error message available in the console, just not display it to users? Do we consider that dangerous? (We need to look at a selection of error messages that actually come back right now.)

Question: if we are creating new error messages on the backend, do we need to translate them? Do we just return it both in english and french, and allow the frontend to pick which to display?

**Comment by tristan-orourke** [comment]
Jerbo: just show users error codes maybe?

**Comment by mnigh** [comment]
@esizer was this resolved with the `useErrorMessages` hook as part of https://github.com/GCTC-NTGC/gc-digital-talent/pull/4597?

**Comment by esizer** [comment]
> @esizer was this resolved with the `useErrorMessages` hook as part of #4597?

Unfortunately not, we need to have our client outside of the router so `react-router` can't automatically handle these types of errors. We would need to throw the errors where they occur rather than let the `errorExchange` handle all of them. Of course, when we throw an error, the page will be replaced by the `errorElement` so it is not a blanket fix when we just want to show something like a toast.

Though, we do have a mechanism in place to send error codes from the API and use that code to display a properly localized message to a user in:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/4301e14957ce079fcc5cc6844015ba4d71bf2371/api/app/Rules/PoolPublished.php#L38-L46

https://github.com/GCTC-NTGC/gc-digital-talent/blob/4301e14957ce079fcc5cc6844015ba4d71bf2371/packages/i18n/src/messages/apiMessages.ts#L170-L175

https://github.com/GCTC-NTGC/gc-digital-talent/blob/4301e14957ce079fcc5cc6844015ba4d71bf2371/packages/client/src/components/ClientProvider/ClientProvider.tsx#L166-L171

As well as logging the error in:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/4301e14957ce079fcc5cc6844015ba4d71bf2371/packages/client/src/components/ClientProvider/ClientProvider.tsx#L184-L193

**Comment by tristan-orourke** [comment]
This is still sort-of the case, but as @esizer outlined, we have a strategy now for passing error codes to the frontend. I'll close this, and if we notice any errors popping up for users which need a friendlier message, we can address them specifically with this pattern.
