### ISSUE TITLE
Admin - Flash of "Not Authorized" on reload

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2868]
Whenever I refresh the page while logged in I get a brief flash of the "Not Authorized" error message and then the page loads.  It doesn't actually prevent me from doing anything but I imagine a regular user would find it a bit disconcerting.  I also imagine the message would stay on the screen longer for slower connections.
![Peek 2022-05-24 13-29.gif](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/5493cd6f-b072-4f31-89e7-50b5a70a4235)

**Comment by patcon** [comment]
Yeah, I noticed this, and thought maybe it was just noticeable for me due to the slowness of my local queries (though maybe comparable to a slow internet connection?)

Related, I was looking into how `auth0-react` handles its login state via it's useAuth0 hooks, as I would assume their patterns are pretty safe and worth emulating. They've got quite a few auth flows accommodated in their libs, so it's a bit to untangle. Didn't finish grokking, but I really love their component and hook APIs :)

They seem to manage various pieces of state (secure and insecure) in a few places, not just one: incl sessions, local storage, cookies, and in-memory cache, and even using web workers (*see below for neat trivia on this last thing). It's hard to tease apart which tactics are used together at the same time. 

But one thing I noticed is that they store a simple insecure cookie for `auth0.xxxxxx.isLoggedIn=true` that I suspect might deal with this flicker (and is removed if tokens stop validating)

The have a client object stored in their AuthContext that seems to handle all the complicated work.

Anyhow, it was enlightening looking at their library a bit, and felt neat to get potential approaches from them

---

Also, wondering if the useSWR hook (that I mentioned in #devspam on Slack) could address this for us. It aggressively caches responses based on a unique cached key (string, array, obj), and they serves cache first, then updates when the new response arrives. If we piped our graphql fetcher functions through it, and let it cache responses based on the data POSTed to /graphql, it could reduced our having to load our UI in cascades of renders with the various graphql calls :thinking_face:

(*re: web workers. Apparently web workers run in an inaccessible background process that the browser JS can only interact with through a developer-defined postMessage interface. And so it's a good place to hide refresh_tokens -- the worker can keep refreshing and passing the access_token forward. Even if JS code or a browser ext is compromised, it can only get access_tokens, not the longer-lived refresh_token. But I digress...!)

**Comment by petertgiles** [comment]
I think it's because of how the routing works.  Check here: https://github.com/GCTC-NTGC/gc-digital-talent/blob/b3a9f74ba7307c05e915afd6b3378aa8b72cbd34/frontend/admin/src/js/components/PoolDashboard.tsx#L67 .  Every time the user navigates to a new route it does a check for logged in and roles.  Since roles are not saved locally the router always returns the "Not Authorized" component until the role is verified.  I think we need to either cache the roles or suspend routing until the role is verified.  Or both!

**Comment by patcon** [comment]
I've been scoping out how auth is handled in react-router sample projects and tutorials, and also how auth0 manages itself via components. The key seems to be a `useAuth` hook, which we have no equivalent of (we keep our auth in the AuthorizationContainer and AuthenticationContainer)

## auth0-react
- has a `useAuth0` hook with an API that is surely very well-thought-out and well-exercised: https://auth0.github.io/auth0-react/modules.html#useAuth0
- this hook has an `isLoading` return value might be helpful here, but `isLoading` might not be used for a simple "isAuthenticated" check
- for `useAuth0`, there's A LOT going on behind the hook, since auth0 supports so much. but importantly, it seems to use a non-sensitive cookie for preserving `isAuthenticated` state, which might be helpful for us to make this check really quick (I personally feel really bolstered by the idea of stealing minimal patterns from established libraries that reflect a lot of learning.)

## react-router protected route tutorial
- video: https://www.youtube.com/watch?v=oUZjO00NkhY
- code: https://github.com/gitdagray/react_protected_routes
- makes use of a dead-simple `useAuth` hook: https://github.com/gitdagray/react_protected_routes/blob/main/src/components/RequireAuth.js#L5
- more generally, auth patterns are interesting and feel really simple -- very component-centric. some refactoring to have `react-router` like interfaces might allow us to move in this direction. e.g., turning our navigate helper function (which is not hook compatible right now) into a `useNavigate` hook that could easily be wrapped into a `<Navigate />` component

For starters, I recommend we create a `useAuth` hook (that's maybe informed by `useAuth0`) and remove all our use of AuthenticationContext and AuthorizationContext through the app. This will then be a great place to start storing more advanced logic for login status.

**Comment by tristan-orourke** [comment]
@patcon I know there's a lot of great info you've shared here, which I'll need to take some more time to process, but for now my first thought is...

Instead of only storing tokens in localStorage, and always getting user info from the API, we could also store that user info (the stuff we return in a Context) in sessionStorage. We could easily use it in our own State-While-Revalidate strategy.
