### ISSUE TITLE
Refactor ProfilePage to avoid network errors in Storybook

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2885]
Network error messages in the Profile Page story is making for an ugly story on chromatic, and causing false snaphsot positives.

ProfilePage should render the `<MyStatusForm>` component instead of `<MyStatusApi>`. The api layer for `<MyStatusForm>` should be lifted into a ProfileContainer component.

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/c4b5cdfd-4ce5-4724-a465-340579f0b5f4)

# Acceptance Criteria

- [ ] Data for `<MyStatusForm>` can be passed into the ProfilePage component, for use in stories. 
- [ ] Network errors no longer appear in stories.
- [ ] This refactor does not change the live page at all.

**Comment by petertgiles** [comment]
I'm not sure when it started.  I noticed it when rolling back from Storybook 6.5 to 6.4.

**Comment by tristan-orourke** [comment]
Shouldn't our storybook stories not be making network requests?

**Comment by petertgiles** [comment]
Yep, this is why we put the form in an inner component and the network stuff in an outer component.  This is probably going to be a refactoring job.

**Comment by vd1992** [comment]
Judging by files that constantly appear on the diff
Should just be:
/talentsearch's ProfilePage, specifically the `<Status>` component 
/admin's SingleSearchRequest, specifically `<SingleSearchRequestAPI>` component

that will need to be refactored?

**Comment by patcon** [comment]
urql also allows mocking responses, in case we'd prefer not to change architecture of components for stories/tests: https://formidable.com/open-source/urql/docs/advanced/testing/#response-success

Generally, providers/context strikes me as the place to make things more testable/mockable. As I'm coming to understand, React hooks and their use of injectable context through providers (like used here from urql) is now the "officially blessed" way to do this sort of work, rather than rejigging components to be separated presentation vs data
