### ISSUE TITLE
Role Selection page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2926]
[
![image](https://user-images.githubusercontent.com/8978655/171277915-559daeac-ee14-4b03-9bc9-7586d52d0edd.png)
](https://www.figma.com/file/UDWAkiGXMt9YGbrfsuSzmr/Interface---Registration-and-login?node-id=85%3A2216)

## Questions:
- What does a page (non-modal) version of this look like?
- What is the URL of a page version of this?
- What does a "navigate based on roles" version of this page look like?
- What if a user is logged in with no roles?

## User Acceptance Criteria
- [ ] A user with a single role bypasses this page and is redirected to the only possible location
- [ ] A user with the ADMIN role can navigate to /admin/dashboard
- [ ] A user with the APPLICANT role can navigate to /user/dashboard

**Comment by mnigh** [comment]
### Questions
1. What happens if a user logs in, reaches this page and then refreshes the page or leaves their browser: would they need to restart the log in process from scratch or would they continue to see this page until taking an action?
2. What if a user reaches this page and does not want to take any of the actions but instead, would like to navigate away, for example, to the login page?

**Comment by mnigh** [comment]
@tristan-orourke is this a feature that is still planned?

**Comment by tristan-orourke** [comment]
Not as far as I know. Closed for no longer planned.
