### ISSUE TITLE
Bug - first click from search to Request page results in blank page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2930]
# Description
Steps to reproduce
1. Go to https://talent.canada.ca/en/talent/search
2. Click Request (doesn't seem to matter what the filters are)
3. See blank page
4. Click refresh. Correct page loads (and still with the correct filters set!)

**Comment by petertgiles** [comment]
Would be good to start this with a cypress test.

**Comment by vd1992** [comment]
Replicated
This pops up in the console

![image](https://user-images.githubusercontent.com/40485260/171276413-20c708c3-a041-4376-b021-98f382bd72c4.png)

**Comment by vd1992** [comment]
And this from browsing to it in Edge

![image](https://user-images.githubusercontent.com/40485260/171277731-a21aa4e8-4cc8-4026-ad96-71b278b3b791.png)

**Comment by vd1992** [comment]
I was messing around with it to see what I could do (and learn in the process)

Seems like the error results from `filter` being set null state-wise when you press "Request Candidates" on /search page. That immediately breaks the page even though you are leaving it. Refreshing it re-renders the /request page. 
I tried this out, so that a null `filter` doesn't break everything instead returns nothing.

It... seems to have worked. At least it looks that way for me

![image](https://user-images.githubusercontent.com/40485260/171297871-fc2f18e3-152f-4ae4-b950-f7ed55a2a169.png)
