### ISSUE TITLE
Accessible loading spinner component

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#2953]
Re-ticketed from #2862 

- consider leveraging a third-party component to help get best-practices for free

Examples:
- https://carbondesignsystem.com/components/loading/accessibility/
- https://carbondesignsystem.com/patterns/loading-pattern/
- can also add accessibility to a non-accessible third-party component

cc: @esizer (i think you shared another link in zoom chat?)

**Comment by esizer** [comment]
So, I was working on #2862 and have a solution presented in #2957.

It is fairly subjective but this is where I land on the issue.

## Fullscreen Loaders

These do not need to be special in anyway. Users are already used to pages taking some time to load and not really odd for them to come to a page and have them loading for a second. How I handled this was just by adding a generic loading spinner. No announcements or anything, it is purely presentational for visual users to see something while the page loads.

Once it is finished loading, one of three things could be presented to a user:

1. The actual content they requested
2. An Error message
3. A Not found message

### Actual Content

This is the expected scenario so nothing is really done except for displaying the content requested.

### Error Message / Not Found

This is not expected so we display the error message with `aria-live="polite"` to announce the error/not found message to the user.

## Inline Loaders

These types of loaders occur when something on the larger page is loading. We have an example of this in the search form. These need to be "noisy" to properly announce what is happening to users. This is where you want an `aria-live` to let the user know what is happening on the page.

Right now, [our inline spinner](https://github.com/GCTC-NTGC/gc-digital-talent/blob/0edff526b25f97e30b104bd4cf70d6114f426f70/frontend/talentsearch/src/js/components/Spinner/Spinner.tsx) is not inherently noisy. We typically apply the `aria-live` on the container to encapsulate both the pending "loading" message as well as the result once the loading is done.

Is this the proper decision? I'm not sure since it is subjective, that is just the reasoning of why I did it the way that I did.

**Comment by tristan-orourke** [comment]
Add props to our main Loading Spinner component to allow it to be:
- inline, if its not for the entire page
- active, if we want to to announce via aria-live
