### ISSUE TITLE
Spike - Decide how to handle "Profile Snapshots"

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3105]
# Description

At the moment when a user submits an application to a pool, we must create a snapshot of their profile.

Requirements for "snapshots":
- At the moment when an applicant applies to a pool - however their profile looks at that moment, that is what Pool Managers need to see when they review the application.
- That "snapshot" needs to be saved for 5 years for auditability purposes
- After 5 years, the snapshot should be able to be deleted
- We may want to be able to show the snapshot to the applicant as well

*Not* required:
- Pool Managers will not need to replace their snapshot with a more recent version or "update" it. We keep the snapshot from the moment of application, that's it.

## Possible solutions

*Option 1*: We can manually create a copy of the profile, and store it along with the Application/PoolCandidate object. 
Pros:
- We did this for Talent Cloud. Its definitely possible.
- Conceptually simple. Each application has one snapshot object.
Cons:
- The function to actually do this will be quite complex, and therefore potentially buggy. Especially difficult is recreating relationships in the duplicate object: ie we need to create a copy of each Experience, and each ExperienceSkill pivot, and ensure the new items are linked together properly.
Questions:
- Do we store the new data in the same tables as the originals? 
- Should we factor out the Applicant object into a separate table from the User, to avoid creating phantom User entities? How much work will that be?

*Option 2*: We turn the tables that store application data into "temporal tables". This allows us to track each change that happens to an object, and retrieve it from any time. eg  https://github.com/gazugafan/laravel-temporal
Pros:
- once the table changes are in place, no extra work is required to create snapshots
- it should be simple to retrieve snapshots at arbitrary times, meaning we could "update" the snapshots if we want. All we need to store with an Application is a timestamp.
Cons:
- we've never done anything like this before. Implementation temporal tables may have a hidden cost
Questions:
- Does this require a postgres extension we need to worry about in production?

**Comment by patcon** [comment]
There's also an SQL standard for "AS OF" that might be helpful. The wiki article mentions the databases that implement it:
https://en.wikipedia.org/wiki/SQL:2011#Support_in_DBMS

DoltDB isn't mentioned, but it also implements it: https://www.dolthub.com/blog/2020-03-20-querying-historical-data-with-as-of/

**Comment by petertgiles** [comment]
Option 1.1...  Could we just use the application as the snapshot instead of trying to bolt a separate snapshot onto the side of an application?  The process of submitting an application becomes the actual process of snapshotting the user profile to create an application.  It's a little more transparent that CMO is actually reviewing the "snapshot" itself rather than us saving an artifact that probably matches because we saved it at the same time.

I think conceptually this is easier for the applicant and for CMO to understand.  "This is my live profile" and "This is my application from two weeks ago".  It will have most of the downsides of option 1 but I think is easier to understand and manage.  

It will have a fairly loose coupling between user and application.  That means that we're duplicating so many fields between the two.  :-1:   But it also means that we have the freedom to let them diverge where it makes sense.  :+1: 

> Especially difficult is recreating relationships in the duplicate object: ie we need to create a copy of each Experience, and each ExperienceSkill pivot, and ensure the new items are linked together properly.

I think this will be a blocker for any kind of temporal table solution.  

It also reminds me that we'll need the client to understand the limits of any kind of "live" solution.  For example, if the name of a skill is updated after an application is submitted the new name will appear on any subsequent review of the application.  If that's a problem I think the only solution is to just save a document like a PDF or a JSON blob.

**Comment by brindasasi** [comment]
While temporal tables are catchy , I'm skeptical on the complications of implementation and maintenance. I could be wrong. 
I would think JSON is good enough for this use case. 
Easy to convert & parse for Applicant view and pool managers view later on. 
This way , we don't really need to know what has been in there and what has been changed. dump in , dump out.  
I don't like PDF , because it adds complexity in formatting ( in my exp ) and it doesn't give a web page view feel for the user. Json can be feed into a file ,web page , component whatever we want.

**Comment by patcon** [comment]
> > Especially difficult is recreating relationships in the duplicate object: [...]
> I think this will be a blocker for any kind of temporal table solution.

@petertgiles sorry, just trying to process your thoughtful comment: isn't the quoted text about Option 1, the _non_-temporal table option? (I'm not particularly a booster of temporal table approach, mind you!)

> I would think JSON is good enough for this use case.

+1 I love the simplicity of just dumping JSON snapshots into a single column in some table (new or existing).

In most all cases, won't it would probably become tougher to render the data visually as our components evolved? Assuming so, what's the failover mode?maybe we could version subsets of the JSON object (peppering the JSON object with version metadata) and so the app can know when a current component can't be used to render it, and then we just show the admin a json representation. This would be for "old" snapshots, for e.g., if an admin came to look at one from last month, and we'd changed the way the component worked, maybe the component could know that "oh, this data I'm getting is from an older version with a breaking change, so I'll just show a monospaced JSON representation".

Given how minimally admins seem to have use for snapshots (mostly due diligence when application first received) maybe this is the right amount of maintenance of old data rendering ability -- aka none

## Open Question 
1. Better for client to submit the data via create operation, or server to do it on trigger from existing application submission operation?
    - Pro for client-side: client has already built/processed a representation of the data that drives the UI.
    - Pro for server-side: errors in this important audit feature get logged on server side rather than logging to user's browser console.

**Comment by petertgiles** [comment]
> isn't the quoted text about Option 1, the _non_-temporal table option

Yes, you're right.  In the original comment it is highlighted as a difficulty of option 1.  I agree with that idea and also think it will be a blocker for option 2.

> It feels like this rendering (PDF, app UI, etc) will get more complicated as we go on.

I agree with this, too.  However, I think we should lean into maintaining the ability to render these snapshots rather than trying to distance ourselves from it.  My suggestion was to promote the snapshot to a first-class model as the pool application itself.

**Comment by patcon** [comment]
> I think we should lean into maintaining the ability to render these snapshots 

Correct me if I'm wrong, but it would seem that in this case the data we pass into the component must either (1) never change shape in a way that breaks backward compatibility, (2) components much contain logic to process past shapes that are "breaking", or (3) we version components when the shape changes, and keep the old ones around? (I will admit there's a brittleness here that makes me want to minimize its impact :) )

And also am I recalling correctly that snapshots are only needed when application is submitted, and then never looked at again? My intuition is that we'll likely discover this debt of rendering past versions not worth managing, so it feels like the quickest approach of JSON helps us discover if that's true of not, without adding scheme management burden to that learning. (My understanding is that temporal tables also involves less schema management, but there's def other complexity there :) )

**Comment by petertgiles** [comment]
I agree with all the implications that you're identifying for each approach.  This is a good conversation to frame out the possible options.  I think the next step is to really drill into client requirements now that we've done a bit of brainstorming.

**Comment by patcon** [comment]
Helpful summary of 4 audit trail options:
https://medium.com/techtofreedom/4-common-designs-of-audit-trail-tracking-data-changes-in-databases-c894b7bb6d18

(Ours seem to be options 2 & 3 from that article :) )

**Comment by tristan-orourke** [comment]
Light Database approach (store JSON)
Pros
	- easy to create
	- easy to use as long as profile component doesn't change

Cons
	- if we want to update the profile view, do we have to maintain old version?
	- We have no type protection on what is stored

Questions
	- Can we pass the json blob through the GraphQL api, to guarantee it adheres to expected types?


Full Database approach (store snapshots in full tables)
Pros
	- Schema is accurate to snapshots
	- We have accurate types, we can be confident that frontend components wont break
	- If profiles change, then our options are:
		- maintain multiple versions of things (data/tables, components)
		- migrate old snapshots into new format
			- Is this okay with auditors? If its not okay, we just store the json also
	- Might force us to more conservative with breaking changes to api/database
	- easier to run analytics on

Cons
	- Creating a snapshot is a complicated operation
	- Updating shape of profile data may require migrating snapshot data

**Comment by tristan-orourke** [comment]
After talking with @gobyrne one more time, here are the product owner priorities:
- When reviewing applications to decide whether to enter them into the pool, admins must be able to view **most** snapshots using the [same UI as the profile](https://www.figma.com/proto/b6lDM86QCJQ6iaAh7qrTYH/Admin-v4-(Direct-Intake)?node-id=2501%3A3744&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1618%3A6064). That includes the fancy view of skills and experience.
- Once an application has been screened in or out, we no longer care about maintaining a pretty view of the snapshot. JSON is perfectly fine for audit purposes.
- It is acceptable if occasionally a snapshot has to be reviewed as JSON.
- Besides the above, we should prioritize whatever is easiest to build and maintain.

Given the above, we settled on:
- saving JSON snapshots
- attempting to render JSON snapshots with the same UI we use for viewing current profiles on admin dashboard
- catching exceptions, and falling back to displaying the pure JSON
