### ISSUE TITLE
Set up Analytics for IAP

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3219]
# Description

Upgrade the existing GA account from v3 to v4 and apply to the app as well as TC-report.
Share analytics about the IAP page with IAP team.

## Background.

The IAP team has requested the ability to track page views. 

First, we should check if Azure already provides traffic analytics from which we could create reports for them.

If that is not possible, we should [set up a Google Analytics account](https://support.google.com/analytics/answer/10759417). From a cursory look at the [account structure](https://support.google.com/analytics/answer/9679158), we may want to create a separate "property" for IAP.

We will want to configure this to collect minimal data, and then add the necessary script to the IAP landing page.

In the future, we will likely want to set this up on all our pages (probably under different "properties" if using Google Analytics), but we can start with a minimal implementation, just on the IAP homepage.

**Comment by tristan-orourke** [comment]
Should be possible to use Azure Monitor Logs and KQL to generate a report which shows the number of unique visitors to a page over time.

**Comment by patcon** [comment]
Considerations:
- @mnigh: If site is located off-network, not supposed to collect IP info. Simple setting in Google Analytics to disable. Does not think it's currently disabled as it should be on tc-report.
  - CDS does this. quite widely. required for them because running on AWS.TBS website has digital recommendations
  - @patcon: concern is less about where site is hosted (IMTD vs AWS) and more about where analytics data is hosted (Azure vs Google).

Azure:
- assumption: metrics and logs data somewhere, but no visual interface we can easily give access to. not tough to see them when have access, but getting access to azure is painful
  - if using azure, hard for IAP folks to be in "explore" mode. i.e. they need to know exactly what to ask us for advance, and maybe they don't know yet.
- Explorable dashboard of GA might allow for **more insight**, beyond what a simepl "generated report" (that we could create for them) might off

- @esizer mentioned that "setting some setting to unsafe loading" is what allows google analytics tracking code to be loaded easily in react app.
- patcon mentioned that there's a react library that helps google analytics load the "right" way. likely not a problem to do it the quick way if we want to avoid another package. https://github.com/react-ga/react-ga

## Potential To Do
- [ ] figure out who has access (some details in https://go.talent.c4nada.ca/inventory, maybe needs update)

Google Analytics:
- should probably not have

Open Questions:
- what does IMTD use for analytics?

**Comment by patcon** [comment]
Note that Universal Analytics (v4) is only _deprecated_ in favour of v5. From the GA dashboard banner:

> Universal Analytics will no longer process new data in standard properties beginning **July 1, 2023**. Prepare now by setting up and switching over to a Google Analytics 4 property.

So we still have a year, if there's any trouble with v5. (and we don't need to upgrade tc-report urgently, if we don't want)

**Comment by esizer** [comment]
> Update: Note that Universal Analytics (v4) is only _deprecated_ in favour of v5. From the GA dashboard banner:

I can't read, thought it was 2022 😜

**Comment by tristan-orourke** [comment]
Azure equivalent to GA: https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview. Add Insights to code with https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript?tabs=snippet

**Comment by brindasasi** [comment]
In order to add instrumentation in the code , I should be able to create an Application Insights resource in portal.azure.com and get the connection string of it. 
I don't have  permission to do that currently and I've requested access via jira (AZ-13533 ). 
Until then this is blocked.

**Comment by brindasasi** [comment]
Got the access as below : 
 
Morin, Philippe on 2022-08-02 8:47 AM 
 
	I've created app Insight "TalentCloud" and linked it to a new log analytics workspace "TalentAppInsights". Both located in your talent_2_paas RG. Depending how much data you gather, there is a cost for ingesting and retaining data. By default you get 30 days free retention. If that's not enough, we can increase it.
 
I've given you log analytics contributor role to your workspace and contributor role to AppInsights.

**Comment by patcon** [comment]
Pls consider updating https://go.talent.c4nada.ca/inventory for azure
