### ISSUE TITLE
Spike - Investigate how to interrupt navigation away from unsaved form

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3264]
# Description
In some cases, like where there is a particularly long/complex form for users to fill out, if a form has unsaved data we may want to interrupt any attempt to navigate away with an Alert, asking the user if they're sure they want to leave unsaved changes.

**Comment by esizer** [comment]
Took a quick look at this and could not find an easy way to do this with `universal-router`. However, `react-router` supported it out of the box in `v5` and plans to support it in an upcoming version of `v6` using `<Prompt />` component.

However, even though they plan to support it, since the common use case for this is to prevent data loss on forms, the recommendation is to do exactly what we do. They recommend storing form state and repopulate based on stored state when returning.

REF: https://github.com/remix-run/react-router/issues/8139#issuecomment-954427837

**Comment by gobyrne** [comment]
Closing since we want to use react-router anyway. Related #3017
