### ISSUE TITLE
Screen readers read out phone numbers as number

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3316]
### Description
Screen readers read out phone numbers as a single number rather than individual digits.

### Acceptance Criteria
- [ ] split the number into chunks and putting that into an [aria-label].
- [ ] Screen reader reads out phone numbers as individual numbers. 
- [ ] Ensure numbers with an extention (ext) is read as e-x-t.

**Comment by esizer** [comment]
Solution?

https://jhalabi.com/blog/accessibility-phone-number-formatting#:~:text=A%20US%20phone%20number%20is,number%20as%20a%20math%20equation.

**Comment by mnigh** [comment]
> Solution?
> 
> https://jhalabi.com/blog/accessibility-phone-number-formatting#:~:text=A%20US%20phone%20number%20is,number%20as%20a%20math%20equation.

Which one: a `tel:` link or the `aria-label` with each number separated with a space?

**Comment by esizer** [comment]
> Which one: a `tel:` link or the `aria-label` with each number separated with a space?

Preferably, both. Though, I think the `aria-label` would have the highest level of compatibility even if it is a little odd.

**Comment by mnigh** [comment]
If we explode the phone string, we need to account for extension (ext) so that it remains readable by a screen reader.

**Comment by MaddyDaigle** [comment]
See issue #3313 .

The solution for this issue is similar.  Have aria-label with the proper way to read out the text followed by hiding the "regular" text from the screen reader user.

The only thing - I don't think you'll be able to use a "span" as the container for this situation, since the element needs to be focusable.

<div aria-label="613 999 9999"><span aria-hidden="true">(613) 999-9999</span></div>
