### ISSUE TITLE
Setting up React-Router

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3533]
Related to #3017

Use React Router for one page, without refactoring the whole app to use it.

# Acceptance Criteria

- [ ] Profile About-Me page uses React Router to control its rendering
- [ ] Links to the about me page still work
- [ ] Links on the About Me page to pages not using react-router work
- [ ] Rest of app is unaffected
- [ ] Prompt the user for confirmation if they try to the leave the page with unsaved changes in the form.

**Comment by patcon** [comment]
Was really interested in this, so clocked so evening hours and got a spike working 🎉 
https://github.com/GCTC-NTGC/gc-digital-talent/compare/main...patcon:gc-digital-talent:react-router-spike-v2

Realized it wasn't as hard to do the full admin app as I thought. Mostly  looks like additions because we can't remove all our helpers until we also migrate the other apps.

Most of the routing now happens here: (no legacy routes for now)
https://github.com/GCTC-NTGC/gc-digital-talent/compare/main...patcon:gc-digital-talent:react-router-spike-v2#diff-6cd43a91e81c996c8362d077f7d99869b2c16eafa395fe62796e3fd484a797caR125

I'm seeing how we should be able to refactor components to make more use of `useParams()` if we want :)

Auth seems really clean using `<RequireAuth />` component. I feel that stories can get more parity with live components since we can use `<MemoryRouter />` story decorators to "trick" any component into thinking it's living on a specific url with specific params. As I understand, this is a really great way to write minimal stories that don't need much special maintenance.

**Comment by esizer** [comment]
Lot's of great stuff coming in `6.4.0`

[Loaders](https://reactrouter.com/en/dev/route/loader) and [Actions](https://reactrouter.com/en/dev/route/action) seems like something that could be extremely useful for us. They seem to basically be porting over `@remix/run` functionality to `react-router`

Ref: https://reactrouter.com/en/dev/start/overview

**Comment by patcon** [comment]
Could prob even put this behind a feature flag, if all the id's passing into components were made optional. useLocation could be swapped conditionally in @common/helpers/router, and navigate set conditionally in components.

This task would pair well with a bunch of dead-simple cypress tests that just tested all the ways of navigating from each page. So if all the tests exercising connectivity continued to work, then we could confidently know the migration worked.

**Comment by tristan-orourke** [comment]
Decided to go straight for the whole thing with #3017
