### ISSUE TITLE
Make API user set per-unit-test

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#3642]
## Description
Policies aren't really being tested and probably ought to be
Implementing them is complicated by https://github.com/GCTC-NTGC/gc-digital-talent/blob/9bc07b61b5ec5461ccf6f7616f798ea604ada264/api/phpunit.xml#L30

Remove that and set env on a per test file basis where not required, enabling policy testing

## Acceptance Criteria
- [ ] remove the env lin in the .xml file
- [ ] resolve broken tests by adding "setenv" stuff per file

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by tristan-orourke** [comment]
The best way to run requests as a particular user in phpunit tests is to use the [`actingAs` helper](https://laravel.com/docs/5.2/testing#sessions-and-authentication).

For example:
```php
$adminResponse = $this->actingAs($admin, 'api')->graphQL($query);
$applicantResponse = $this->actingAs($applicant, 'api')->graphQL($query);
```
Note that we must specify that we're actingAs a user according to the 'api' guard. Our graphql requests use the 'api' guard, as specified in `api/config/lighthouse.php`, while our general Laravel app still uses the 'web' guard by default, as specified in `api/config/auth.php`. (Maybe we should just change it there, since we're only using Laravel for our API.)
