### ISSUE TITLE
Open Redirect security issue in the code detected by Snyk 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3656]
Issue Severity : Medium
Issue Type:  Code 
Issue Description : 
`Unsanitized input from browser storage flows into window.location, where it is used as an URL to redirect the user. This may result in an Open Redirect vulnerability.`
Reported By : snyk 
Issue Link:  https://app.snyk.io/org/gctc-ntgc-r4y/project/f850f54c-f7fa-4ae1-98b2-c8bf14a1cd90#issue-31b5ac33-65e5-47ba-8ad4-b5631934c663

Learn more about Open Redirect vulnerability
https://learn.snyk.io/lessons/open-redirect/javascript

https://github.com/GCTC-NTGC/gc-digital-talent/blob/8bd2645e82a15adcacb6edc1e8ac90671cce71c2/frontend/common/src/components/Auth/AuthenticationContainer.tsx#L65

https://github.com/GCTC-NTGC/gc-digital-talent/blob/8bd2645e82a15adcacb6edc1e8ac90671cce71c2/frontend/common/src/components/Auth/AuthenticationContainer.tsx#L68

**Comment by gobyrne** [comment]
@esizer do you think  building the URL using React Router tools will fix this?

**Comment by esizer** [comment]
> @esizer do you think building the URL using React Router tools will fix this?

Unfortunately, this sits outside of `react-router`. I think we should be using `URLSearchParams` as well as handling this on the backend since we are exposing this to the client. 

As it stands, we are exposing the URL to the client so it is easy for bad actors to see this and do something like:

Creating a similar URL to login and send users to a fake app for phishing.

## Example

`https://te-auth.id.tbs-stc.ca/oxauth/restv1/end_session?logoutUri=phishingsite.com`

## Proposed Solution

Maybe we should look into making a proxy in our `api` that does the login/logout so we do not need to expose a redirect uri in the client and instead only pass a `pathname`.

This way, we can pass the redirect as base64 to obfuscate and validate it on the backed against an allow list. Similar to [how Auth0 does it](https://auth0.com/docs/secure/attack-protection/state-parameters).

> **Note**
> Also, I hope sign-in Canada is forcing us to set an allowlist of redirect uris as well to prevent sending users to any website after login.

**Comment by gobyrne** [comment]
SIC whitelists redirects (says Peter after convos with SIC engineers) so we can close this. Not an issue.
