### ISSUE TITLE
Create the snapshot page where admin can see the application as submitted

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3690]
As an admin/pool owner reviewing the All Candidates Table , I would like to click on the View Application and get the applicant snapshot page, so that I can review the candidate profile at the time of application submission.

## Screenshot

<img width="881" alt="Screen Shot 2022-09-08 at 11 27 45 AM" src="https://user-images.githubusercontent.com/305339/189162896-14e749dd-dcd4-4703-82a5-b1b6237a257a.png">

A/C

1. When Admin click on the View Application link , he should be redirected to snapshot page as shown in the https://www.figma.com/proto/b6lDM86QCJQ6iaAh7qrTYH/Admin-v4-(Direct-Intake)?page-id=0%3A1&node-id=2501%3A3744&viewport=3469%2C7991%2C0.82&scaling=min-zoom&starting-point-node-id=1618%3A6064 
2. Applicant snapshot json should be retrieved from the DB, parsed and feed into the snapshot profile page 
3. If json is stale and not compatible with the component any more , the page should just load the json values.

**Comment by petertgiles** [comment]
Removed " Trigger snapshot functionality during Application submission" as blocker since we can manually trigger snapshots currently.

**Comment by Jerryescandon** [comment]
that sounds good. but im not sure if the last one should be .../application to differentiate from the .../profile maybe ?

**Comment by petertgiles** [comment]
This issue does not included the component on the left side of the page.

**Comment by petertgiles** [comment]
Hi @Jerryescandon I'm digging into this some more and have a few more questions about the design:
1. All of our pages have the breadcrumbs below the title.  Is it intentional to have them above on this page?
![image](https://user-images.githubusercontent.com/8978655/189372156-63108c1e-998e-405d-ad47-e705bc1f72f0.png)
2. Displaying the IDs in the breadcrumbs like in the design is pretty verbose in practice.  Is there a reason you don't want to simply display the names instead?
![image](https://user-images.githubusercontent.com/8978655/189372411-04f546c5-60b1-4bef-8dc5-1e57f8f3e053.png)
3. Should we standardize on "Title Caps" or "Initial caps" for designs?
![image](https://user-images.githubusercontent.com/8978655/189372702-aa06f3cb-b37b-49c9-a629-e7532ffd3d7f.png)
![image](https://user-images.githubusercontent.com/8978655/189373001-44ebf1a7-7510-4c4f-a58a-5fbd5fd7a441.png)
![image](https://user-images.githubusercontent.com/8978655/189373686-9143298f-743c-47b4-91cf-12aed9637ada.png)

**Comment by Jerryescandon** [comment]
1. Nope, I was trying stuff, but you are correct, we should keep the layout consistent. (if there is a push some other time to move breadcrumbs elsewhere it will be part of a different sprint.)
2. Yeah those are some lengthy strings, If it's easy titles would probably look better.
3. Initial caps should be the standard, I just have a bad habit of using Title Caps. but please keep Initial caps everywhere.
