### ISSUE TITLE
Disclaimer agreement checkbox unchecks itself

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#3709]
## Description
When editing a previously submitted "Personal experience" the checkbox regarding permission to share automatically uncheckes itself without user intervention.  Strictly speaking, it should only uncheck if ANY changes have been made to the actual information.

## Screenshot: Prototype
![image](https://user-images.githubusercontent.com/16977254/185479818-46455cb7-a4f4-4789-b370-d6a94eaafa02.png)

## Acceptance Criteria

- [ ] Make disclaimer checked if editing an existing experience
- [ ] Uncheck the disclaimer if form is edited

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by esizer** [comment]
Looks as though we are not storing this field in the database at all so we cannot assume they checked it even though it is required. I see three options,

## Proposed Solutions

### Database

We store this value as a `boolean` in the `personal_experiences` table so we know whether to check it on the frontend.

### Frontend

Since this is a required `input[type=checkbox]` we can assume it will always be `true`. If we can make this assumption, we can check the box by default if it is an existing experience.

### Leave as is

If you are editing an existing experience, it might be a good idea to always ask the user to agree to share the info. We may not want to assume since a user previously agreed that they continue to agree after editing the info.

**Comment by Jerryescandon** [comment]
From bug to feature. A true underdog story. I think I agree with you on that last point.
Strictly speaking, it should only uncheck if ANY changes have been made to the actual information. BUT I guess keeping as is is a good compromise. although a little janky. 😆

**Comment by esizer** [comment]
> Strictly speaking, it should only uncheck if ANY changes have been made to the actual information.

I agree with this, I'll update the AC 😺
