### ISSUE TITLE
Add inline details in feature flag config file

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3815]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description
It came up in the call that it's not clear the context of feature flags. The team agreed that putting this info in `frontend/.apache_env` could be helpful:

- WHY we are using a feature flag
- WHAT is the feature flag affecting

## Acceptance Criteria
- [ ] all three feature flags are described

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by patcon** [comment]
Another thing that might be helpful for someone like Josh who wants to flip the switch and see what's changed is:
- WHERE is the change affecting (the main path of the affected components)

**Comment by mnigh** [comment]
@patcon can the description be updated to reflect the change from Apache (ex. frontend/.apache_env) to Nginx?

**Comment by mnigh** [comment]
@patcon is this [description](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/documentation/environment-variables.md#run-time-variables) what you had in mind for "WHY we are using a feature flag" or does it not provide enough of a description for the feature flags?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/8ec1558d812ce37a818eff6d77e968869be031a3/documentation/environment-variables.md?plain=1#L19-L22

For "WHAT is the feature flag affecting" and "WHERE is the change affecting", this seems a bit more difficult since in theory, the scope of what the flag covers could change, but certainly possible to rewrite upon scope changing. I would say that for anyone who is actually toggling feature flags on and off, they would need to be developer in how they have been implemented, so a file search for the desired string would surface the places that the flag is used.

We currently have two feature flags in the codebase, though only one (`FEATURE_ONGOING_RECRUITMENTS`) has been implemented:
- `FEATURE_ONGOING_RECRUITMENTS`
- `FEATURE_APPLICANT_DASHBOARD`

Since `frontend/.apache_env` no longer exist, did you have another place in mind to write descriptions?

**Comment by mnigh** [comment]
This might be easier when #6375 is merged. @patcon or other @GCTC-NTGC/developers: did you have any idea on the copy for the details?

**Comment by petertgiles** [comment]
I guess coming up with documentation would be a big part of the scope of this issue.  Would we add the documentation to
- The config file? (this is where I started)
- The .env file?
- The graphql schema?

**Comment by esizer** [comment]
> * The config file? (this is where I started)

This would be the "laravel" thing to do. That is where they document different env vars.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/9a93c576b3fa9d1f1a29e86f027d6531691b72a3/api/config/app.php#L4-L15

**Comment by mnigh** [comment]
This has been done the Laravel way:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/27f7fbbe0f42c2c324514daa0ed0cc00ce058f5f/api/config/feature.php#L4-L50
