### ISSUE TITLE
Improve experience of viewing/testing localized strings (Google Translate or Deepl)

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3818]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

Related: https://github.com/GCTC-NTGC/gc-digital-talent/issues/3816

### Current Behaviour & Challenges
Currently, we have some non-ideal solutions in our translation process, related to the following:
1. strings in **database**: we seed database translations by **appending "EN" or "FR"** to english faker content to make strings like "Some string EN" and "Some string FR".
  - this is very confusing for user testers. not only are the words nonsense, but it's not clear what EN and FR mean.
2. strings in **codebase**: we have **no French strings at first**, and only see proper localization after translations come back (sometimes weeks later). Until then, we see English, which is indistinguishable from a string that hasn't been localized properly.
    - can't do realistic user testing until translated strings come back, which sometimes has a slow cycle time (weeks)
    - in the meantime untranslated strings look identical to strings we forgot to set up as localizable

### Proposed Solutions
Use a third party translation service (e.g. Google Translate or Deepl) to improve our translation process, to improve interim user testing and create more consistent expectations of toggling language.

This will ensure UAT server has more fidelity for user testing. It could also ensure our Storybook stories have more fidelity. This could be done with different approaches for each time:
1. strings in **database**: instead of auto-generating faker content as "foo EN" and "foo FR", translate the english values using a translation service
    - open questions
      - will this apply to programmatically generated content (from faker) or will it just apply to the hand-tuned seeders?
      - can this be done manually one time, or does it require scripting against an API
2. strings in **codebase**: for places where we've created an English string in the codebase itself, but haven't yet translated it "officially", we can use a translation service in the meantime
    - open questions
      - should we have a process to add french translation from Google Translate at the same time we add English?
      - If we want a process, how can we differentiate these from the later "official" translations? (custom keys in fr.json file entries?)
      - How does this affect our existing translation process and helper scripts?
      - Should this translation process be manual or scripted via Google Translate API? Should we start with a manual process?
      - what translation service should we use? Google Translate? Deepl? other?

I'm documenting this as a single issue, but would recommend these two things be done in separate PRs.

## To Do
- [ ] ...

## Acceptance Criteria
- [ ] we no longer use "Some string FR" format on UAT
- [ ] we no longer have any unchanged English strings in app when viewing FR localization (stories + UAT)

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by gobyrne** [comment]
@mnigh any thoughts?

**Comment by mnigh** [comment]
> 1. strings in database: instead of auto-generating faker content as "foo EN" and "foo FR", translate the english values using a translation service

Yes, for seeder data, this isn't a problem, but for real strings using a translation service online versus the "official" translation service could be trouble. In one of the seeder's cases, the manual French version of the string has not been translated and does not use a library to generate a value:

**Translated**
https://github.com/GCTC-NTGC/gc-digital-talent/blob/7e18afecb56ed823c5d8b4ea1d0111cc78746d9d/api/database/seeders/PoolSeeder.php#L22-L23
**Untranslated**
https://github.com/GCTC-NTGC/gc-digital-talent/blob/7e18afecb56ed823c5d8b4ea1d0111cc78746d9d/api/database/seeders/PoolSeeder.php#L38-L39

> 2. strings in codebase: for places where we've created an English string in the codebase itself, but haven't yet translated it "officially", we can use a translation service in the meantime

I'm not sure how this would work and echo the question: how would we distinguish between "official" and "non-official" translations in the codebase? This seems a bit risky in my opinion. As for Google Translate vs. Deepl, probably Deepl since it provides better context, though if the individual working on the code is unfamiliar with French, any translation tool will be tricky.
