### ISSUE TITLE
Better accesibilty for dates

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4041]
This is a placeholder issue to discuss, design, and make a decision on a more accessible way to input dates.

**Comment by petertgiles** [comment]
Related:  #3585

**Comment by gobyrne** [comment]
There are also a lot of places in our experiences profile pages that really only need Year & Month. It would be really helpful if that was an option. It's also a lot easier... we could create a custom component for it if needed.

**Comment by tristan-orourke** [comment]
Seems to me like this can be split into three issues:
1. Timezones cause some inconsistency in how dates/datetimes appear.
2. The default Date input is not accessible.
3. In some places, it doesn't make much sense to store/display a full date at all. Just a month and year might be preferred.

I think we've been overthinking problem 1. We're already doing a good job of saving dates to the API and database in a sensible way, as timezone-agnostic YYYY-mm-dd strings. We just need to be careful about how we present dates in the frontend. See https://github.com/GCTC-NTGC/gc-digital-talent/pull/4132 for the fix to one instance of this problem.

2. can be solved by building a custom Date component, with help from designers.

3. needs another custom component, and instructions from Design on where to use it.

**Comment by petertgiles** [comment]
I think you're right about splitting it into three and sending #2 and #3 over to the designers.  I'm not sure we have #1 totally figured out though.  Some dates, like a birthday, can happily exist without any kind of time zone or offset specified.  Some dates, like an expiry date, aren't really useful without it.  That issue already exists on the board as #3315 though.

**Comment by tristan-orourke** [comment]
@petertgiles I would argue that any date which needs a timezone, like an expiry date, are actually a _datetime_ object, and not a _date_ at all. I think we already have that distinction in the database, we just need to make sure we're aware of it in the frontend.

**Comment by petertgiles** [comment]
> I would argue that any date which needs a timezone, like an expiry date, are actually a _datetime_ object,

Yes, you're right, datetime.  I think the bottom line going forward (as I understand it?) - the database and API will always, always deal only in UTC for datetime and it will be up to the client to convert to and from.  If that's the decision then I think we should convert the pool expiry date over to datetime, totally remove datetimetz, and update the pool expiry form.

**Comment by petertgiles** [comment]
I do wish it were a little more explicit somehow.  Like if the values had the +00:00 offset or had a UTC suffix on the field and column name.

**Comment by esizer** [comment]
> **Warning**
> I actually checked our pool expiry and it is not great. We aren't even storing the UTC equivalent. It actually changes the timezone without shifting the time which is likely the root of **_most_** of our problems.

- **What we send to API:** 2023-01-26T00:00:00-05:00
- **What is stored:** 2023-01-26 00:00:00+00

> **Note**
> After realizing the database is actually storing the incorrect time, i'm not sure how relevant the remainder the rest of this comment is but I'm going to leave it since it may be useful info incase the above is not an issue.

---

So, I took a look at this for a little while and wrote a helper in `dateUtils` using `date-fns-tz` which formats all frontend dates in UTC. It solved the issue we had where dates were offset by one. However, this becomes problematic if we want something to deal in specific times, it only works if all we care about is the exact day.

## Example

### Submitted At

1. Application submitted at 4:00pm EST
2. Send to API and stored as `2022-09-30 20:00:00+00:00`
3. We get it back on the frontend and wrap the string in `new Date(submittedAt)`
4. It gets converted back into EST i.e `2022-09-30 16:00:00-04:00`
5. We trick it back into UTC so it is displayed as `2022-09-30 20:00:00+00:00`
6. User/Admins think they submitted at 8:00pm EST

## Expiry Dates

This becomes very troublesome when we are calculating expiry dates, do we compare against the users local time, UTC or another set timezone? If we normalize everything to UTC that puts users on the west coast at a disadvantage since they technically have less time to apply for a pool, sort of.

## Example

- Pool expires midnight UTC
- User in NS has until 9:30pm to apply
- User in BC only has until 5:00pm the same day

> **Warning**
> I noticed we have some columns as `timestamp` and some as `timestamptz` which is problematic. I think what is happening is that laravel is storing all of their generated fields (`$table->timestamps()`) as `timestamp` and we are doing the smart thing and storing our own columns as `timestamptz`.

**Comment by vd1992** [comment]
@esizer 
this issue is sorta being discussed in multiple places, please also see #4273 to see what else is going on

**Comment by esizer** [comment]
> this issue is sorta being discussed in multiple places, please also see #4273 to see what else is going on

Ahh, yeah we should maybe sort through all of our date related issues. Can we define how `lighthouse-php` stores the value? Because right now it is not doing it properly which will cause us problems no matter what we do to fix that.

**Comment by vd1992** [comment]
> > this issue is sorta being discussed in multiple places, please also see #4273 to see what else is going on
> 
> Ahh, yeah we should maybe sort through all of our date related issues. Can we define how `lighthouse-php` stores the value? Because right now it is not doing it properly which will cause us problems no matter what we do to fix that.

like I said, an issue for every timezone 😛
