### ISSUE TITLE
🐛 User profile conditional logic used inconsistent

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4075]
## Description
The logic surrounding the User profile keys and values currently does not render both the key AND value(s) if the value is `NULL`, meaning a user wouldn't necessarily know that the key even exists.

## Screenshot
![Screen Shot 2023-05-03 at 16 52 55](https://user-images.githubusercontent.com/3046459/236047238-9a02f5a2-8cf5-4c52-916a-32be255832de.png)

**Comment by petertgiles** [comment]
I guess this is related to https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1664201699347729 ?  Did you check with Jerbo on the correct behavior?

**Comment by mnigh** [comment]
> I guess this is related to https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1664201699347729 ? Did you check with Jerbo on the correct behavior?

Yes, related to that Slack discussion. @Jerryescandon said it would best to revisit, so I created this issue.

**Comment by gobyrne** [comment]
I just created an account to test this out. I see what you're talking about, but I think it's functioning as expected. You can't reach some of the states shown in the screenshot above either, because the required fields are enforced when you go to the page. In any case, the user is properly notified that there are required fields missing.

I think this is all ok. #wontfix
