### ISSUE TITLE
Talent search - Support form field model

### ISSUE THREAD

**Issue by JoshBeveridge** [GCTC-NTGC/gc-digital-talent#4127]
# 💡 Purpose

As a part of the Freshdesk integration, we need to develop a basic field model for the [form API](https://developers.freshdesk.com/api/#create_ticket).

# ✅ Requirements
For now, I'm proposing collecting a series of active and passive fields based on minimal needs for providing user support. 

**Active fields:**
- Name `text`
- Email `email`
- Subject `select`
  - Bug report `option`
  - Feedback `option`
  - I have a question `option`
- Details `textarea`
- Captcha

**Passive fields:**
- Current or previous page URL - because users will be directed to a support page, is it possible for us to collect the page they arrived from?
- Whether the user is logged in, and if they are, their account ID - is this a breach of privacy?
- Is it possible for us to collect any kind of error codes from the front-end?

**Comment by JoshBeveridge** [comment]
@Jerryescandon Can I get your eyes/thoughts on this? Am I missing anything mission critical for our initial release?

**Comment by tristan-orourke** [comment]
> Active fields:

Most of these active fields map nicely to the Freshdesk api parameters:
- Name input: `name`
- Email input: `email`
- Subject dropdown: `type`
   - the option values should be strings, eg `bug`, `feedback`, and `question`
- Details textarea: `description`
- @JoshBeveridge, what about a Title/Summary field, like the subject line of an email? That would be the `subject` parameter in the api.
- **Captcha**: not sure how we want to do this. Easiest thing might be to add a honeypot trap that we can process on our own api, before forwarding the request to freshdesk.

> Passive fields:

These can all be done, though with additional work. I might treat them as separate features with their own tickets.

- _Current or previous page URL - because users will be directed to a support page, is it possible for us to collect the page they arrived from?_ This seems like it should be a custom field in the freshdesk api. We can set up a way to get the previous url, at least when navigating to the support form. My first thought is for links to the support form to push the previous url into the [History state object](https://github.com/remix-run/history/blob/main/docs/api-reference.md). 
- _Whether the user is logged in, and if they are, their account ID - is this a breach of privacy?_ This doesn't seem like a breach of privacy to me, especially if we make it clear we're making use of their account, eg by pre-populating name and email for logged-in users. The `unique_external_id` api field might be appropriate for this, or another custom field - I'll ask Marc about it.
- _Is it possible for us to collect any kind of error codes from the front-end?_ I like this idea! Right now errors are ephemeral, we just show them in a toast and then they disappear. But it would be easy to log them to the session, and include that in another custom field!
