### ISSUE TITLE
Hide UUIDs by default in admin tables

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4154]
## Description
We have visible UUIDs in several places in the application.  I think they're ugly, long, and not very useful to a user.  I wouldn't be surprised if less technical users found them intimidating, too.  Can we replace them by the name of the entity or just hide them?

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/2fd803e6-496e-4289-a778-8bd95cd5d69f)

![Screen Shot 2023-07-19 at 13 20 57](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/7a27ea84-8173-411f-9a10-850f84e7ea14)

## Acceptance Criteria

- [ ] ID column in admin tables hidden by default (Classifications, Skills, Skill families)

**Comment by gobyrne** [comment]
Yeah, will pass to designers and we can clean this up.

**Comment by mnigh** [comment]
- "My hiring pools" section is not currently rendered anywhere and is [slated for removal from the codebase](https://github.com/GCTC-NTGC/gc-digital-talent/issues/5730#:~:text=Delete%20unused%20My%20Hiring%20Pools%20section%20in%20the%20code).

## Questions for @GCTC-NTGC/designers 
1. could the "ID: 601bf80a-dbc3-4372-b22e-789f058304b4" be removed altogether from the **My Applications** wells?
2. could the "Pool ID #12345" in the breadcrumbs for **View Pool Page** and **Edit Pool Page** be replaced with the Pool's name instead (ex. "CMO Digital Careers")?
3. could the admin tables (Classifications, Skills, Skill Families, Candidate Results (Legacy)) ID columns be hidden by default using the `hiddenCols` prop (`ClientManagedTable`) or `hiddenColumnIds` prop (`ApiManagedTable`), that way they could still be visible on-demand for a super user that really wants to see them?

**Comment by Jerryescandon** [comment]
Jerbo's opinions on ID

The main purpose for ID is troubleshooting, I agree they are long, ugly and intimidating, but is one of those this you dont need until you do. But maybe we can do something to alleviate their impact without removing them completely.

- My applications: We could hide them behind a toggable link "See pool ID" or similar?
- Definitely doesn't need to be an ID in breadcrumbs, we can replace with the name if we have it. But we may not always have it. Are there instances where we dont have a name yet? right after creation?
- (Jerbo and Josh are less sure about the need for breadcrumbs at all in amdin but thats a different thing altogether)
- Agree with Matt: Hide ID column  in admin tables by default.

**Comment by RM-1978** [comment]
Rosalie<s two cents: 

1. Agree with Matt: Hide ID column in admin tables by default. Folks using screen readers would definitely be subjected to a long readout of the ID, and our last fable tests revealed that this kind of readout can indeed be an irritant. 
2. Agree with Jerbo: Because these IDs serve an identification purpose,  using the name when available and hiding them behind an accessible, togglable link "See pool ID" or similar might avoid any usability challenges for man AT perspective. 
3. On the Breadcrumbs, though it is part of the GoC DS, wondering if that might also help team members who use text-to speech technologies to navigate quickly.   

I think that the solution Jerbo is proposing is a

**Comment by esizer** [comment]
> The main purpose for ID is troubleshooting, I agree they are long, ugly and intimidating, but is one of those things you don't need until you do. But maybe we can do something to alleviate their impact without removing them completely.

If we really need a UUID for troubleshooting, can we not just request the user send the URL/screenshot of the page causing problems? 🤔 Users don't and shouldn't need to care about UUIDs at all or see them anywhere imo and the URL contains it anyway so should be sufficient. I think this would be far easier than asking a user to toggle a "show ID" button to copy it and send to us.

Just seems odd we surface something we need for troubleshooting to the user unnecessarily. Also a URL would tell us far more about the issue than the ID itself (knowing exactly where they encountered the issue).

If someone says "I'm having X problem with [UUID]" that tells us far less than knowing the page since these can show up in many different places. I'm just not sold on the value of surfacing the UUID being there.

Though, if we must have it appear, maybe we could use a dropdown with an action item like "Copy ID" rather than actually showing it to a user and muck up the UI.

![Screenshot 2023-03-03 144938](https://user-images.githubusercontent.com/4127998/222813303-2ed12a2e-588d-450f-888d-c18c6202a7d1.png)

**Comment by RM-1978** [comment]
> > The main purpose for ID is troubleshooting, I agree they are long, ugly and intimidating, but is one of those things you don't need until you do. But maybe we can do something to alleviate their impact without removing them completely.
> 
> If we really need a UUID for troubleshooting, can we not just request the user send the URL/screenshot of the page causing problems? 🤔 Users don't and shouldn't need to care about UUIDs at all or see them anywhere imo and the URL contains it anyway so should be sufficient. I think this would be far easier than asking a user to toggle a "show ID" button to copy it and send to us.
> 
> Just seems odd we surface something we need for troubleshooting to the user unnecessarily. Also a URL would tell us far more about the issue than the ID itself (knowing exactly where they encountered the issue).
> 
> If someone says "I'm having X problem with [UUID]" that tells us far less than knowing the page since these can show up in many different places. I'm just not sold on the value of surfacing the UUID being there.
> 
> Though, if we must have it appear, maybe we could use a dropdown with an action item like "Copy ID" rather than actually showing it to a user and muck up the UI.
> 
> ![Screenshot 2023-03-03 144938](https://user-images.githubusercontent.com/4127998/222813303-2ed12a2e-588d-450f-888d-c18c6202a7d1.png)

This seems like a more elegant and user -friendly solution to me.

**Comment by Jerryescandon** [comment]
Yeah no problem with Erics proposal.

**Comment by mnigh** [comment]
> Yeah no problem with Erics proposal.

Which proposal?

1. "not sold on the value of surfacing the UUID being there."
2. "Though, if we must have it appear, maybe we could use a dropdown with an action item like "Copy ID" rather than actually showing it to a user and muck up the UI."

I am also not sold on the value of surfacing the UUID for a user and introducing a button with a value they won't even know what it means, what it refers to (is it an: application id, pool id, pool advertisement id, user id, etc.), or when they would ever require it. As Eric said before, the URL would be much more useful for troubleshooting and much easier for a user to find if asked.

**Comment by Jerryescandon** [comment]
I think the copy to clipboard would be the most useful in the case of "My applications" since the URL would not be specific to a pool on that page, and the copy to clipboard might 🤷

**Comment by substrae** [comment]
@esizer @mnigh @Jerryescandon 

The `copy id` button is the best path forward here, I think. While it's fine to refer to applications, pools, and other data models by name at our current scale, this logic quickly falls apart when we start having multiple entries with similar or exactly the same names (which is bound to happen). We need an efficient and unique identifier users can fall back to for reference if/when it comes down to it.

The new designs for application cards (coming with the new application updates) provide a "get support" link that triggers an email prompt - we can put the ID in the email body directly as step 1, and the cards also then have what Eric is suggesting, where you can copy the ID directly:

![image](https://user-images.githubusercontent.com/6960386/233453327-000d814d-9fc8-4918-9f46-8faefadb3ec5.png)

**Comment by gobyrne** [comment]
Has anyone actually ever used one of these IDs?

**Comment by esizer** [comment]
> Has anyone actually ever used one of these IDs?

Apparently they are there "just in case" for support but they do also appear in the URL which is probably more helpful that the ID itself. So if support asks for the URL, we will not just get the ID but also the page they encountered an issue.
