### ISSUE TITLE
 Admin Requests table actions position inconsistent with other tables

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4163]
## Description
Position of actions on Admin **Requests** table inconsistent with other Admin table that have actions as the last columns. Also, name of the column **Action** should probably be **View**.

## Screenshot
<img width="1393" alt="Screen Shot 2022-09-29 at 11 41 52" src="https://user-images.githubusercontent.com/3046459/193606502-7fed8a64-84e7-448b-80a2-412fde854031.png">

**Comment by mnigh** [comment]
did you have any opinions on this issue @Jerryescandon?

**Comment by mnigh** [comment]
> We could argue that we could have the same column on every table which should contain all possible actions always using iconography and buttons. and place this column Always on the right most side.

I would agree with this argument: consistency across tables is good for a variety of reasons. @esizer are there any a11y considerations with having buttons that do not have any visible text? Would hidden text or an `aria-label` be a suitable solution?

**Comment by esizer** [comment]
> @esizer are there any a11y considerations with having buttons that do not have any visible text? Would hidden text or an `aria-label` be a suitable solution?

As long as we have `aria-label` with contextual content we should be fine 👍

**Comment by Jerryescandon** [comment]
User tables could have something like these for `view-user`

![image](https://user-images.githubusercontent.com/16977254/193679251-b073bcac-d7c6-43c7-84b9-66a82ea83684.png)

Same for Requests. My take is that the right-chevron can be used for actions like `open` or `view`

**Comment by JoshBeveridge** [comment]
So a couple things to consider here:
- Not to be contradictory, but I'd argue that buttons should never just be an icon and always have accompanying text, because our choice in iconography isn't consistent enough to be reliably understood; for example, none of the icons in the above design tell me  what's going to happen when I click them, and sometimes chevrons are used for expansion instead of "go to", etc.
- If this column is always at the end of the table, there's a good chance that the column will always be hidden behind a horizontal scroll, and this is going to make taking action really frustrating for people (it might even cause people to miss the actions entirely)
- I'm not convinced icons are a better approach than short, actionable words like `view`, `delete`, `edit`, etc. but I DO agree that the actions should be consolidated in one spot like this for consistency

**Comment by Jerryescandon** [comment]
I feel like custom icons could address item number 1 if we spend the time on it
we can decide on the best placement for the column as long as it stays consistent (eg 1st column)
I got nothing for you on number 3 😆

**Comment by petertgiles** [comment]
> * If this column is always at the end of the table, there's a good chance that the column will always be hidden behind a horizontal scroll, and this is going to make taking action really frustrating for people (it might even cause people to miss the actions entirely)

Big +1 on this one, from personal experience.

**Comment by gobyrne** [comment]
Adding to the design backlog

**Comment by Jerryescandon** [comment]
I've been thinking about this, I do like the idea of an action dropdown. 
The windows image viewer has an example of this. 
![image](https://user-images.githubusercontent.com/16977254/195407307-a4f32c49-1e04-49cd-b3c4-0f3ca54894f9.png)

The main are with the text acts as a regular button, and pressing the down arrow reveals more options, clicking on one of these will immediately perform as pressing that button instead.

**Comment by mnigh** [comment]
@Jerryescandon has there been any more design consideration on this issue?

**Comment by esizer** [comment]
This specific table has been removed and we are planning an overhaul of our tables shortly. Is it safe to close this now?
