### ISSUE TITLE
view pool advertisement button/link dead

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4182]
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/e7d274d6-bc68-4fb5-9e3d-07001cd7cb88)

**Comment by vd1992** [comment]
what exactly should it link to? feels like the current page can be considered a "view pool advertisement" page since all the pool data is just below the link
or is it supposed to link to the direct intake pool posters `/en/browse/pools/:advertisement` ? would that be tricky attempting to link from `/admin` to `/talentsearch` ?

**Comment by petertgiles** [comment]
> or is it supposed to link to the direct intake pool posters `/en/browse/pools/:advertisement` ?

I think that's right.
