### ISSUE TITLE
Backend Rate Limiting

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4185]
In theory it would be possible for a bad actor to flood our backend and bring it down and/or cost us a lot of money.  Do we have a way of rate limiting excessive usage?  With graphql this might be a bit tricky since not all requests are comparably costly.

## Acceptance Criteria
- [ ] Any API request trying to hit our endpoint gets throttled after 100 requests in a minute.
- [ ] Error message that users gets in a toast after they are throttled is:
> Too many requests, please wait a minute and try again.
> Trop de demandes, veuillez patienter une minute et réessayer.

**Comment by tristan-orourke** [comment]
We can easily use Laravel to add blanket limits to all graphql requests, which all use a single url. It might make sense to add a limit of something like 100 requests per minute per IP. It should be fairly high, since we can have multiple graphql requests per page, but would at least stop arbitrarily excessive spamming.

https://laravel.com/docs/9.x/routing#defining-rate-limiters
https://laravel.com/docs/9.x/rate-limiting#introduction
