### ISSUE TITLE
Maintenance banner: Banner for instances where the app might go down for maintenance or is currently under maintenance

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#4235]
# ⚔️ Purpose

**Goal #1:** The goal of this design is to create a universal banner for the site that will help users understand that server maintenance is either:
- imminent
- happening

We want to ensure that people aren't doing data entry during these times to prevent accidental data loss. We're unsure how long maintenance lasts or if it can be scheduled, but this is something you might be able to check with the development team

Like all of our design work, this component should be reusable if possible, meet accessibility standards, and follow the general themes of the site.

# Wireframes
https://www.figma.com/file/QwUGs0rbZaw3gfINlRPjOt/Global-messages%2Ferrors?node-id=0%3A1

![Image](https://user-images.githubusercontent.com/1794660/196989651-b6e7395c-c1cb-4b3b-b606-2aec93cb4588.jpg)

# ✅ Requirements
In order for the design work to be complete, the following must be done:

- [x] A generic banner component has been created in Figma that can be reused for other purposes
- [x] The component uses styles based on the new homepage look and feel (reach out to Brooke if unsure)
- [x] Accessibility requirements for the banner are documented in Figma
- [ ] The component design has been reviewed with the design team
- [ ] Text has been translated in both languages
- [ ] The design has been presented to the development team for feedback
- [ ] A development issue has been created in Github

**Comment by gobyrne** [comment]
It's looking great. Is it ready to bring to design Critique?

**Comment by MaddyDaigle** [comment]
@gobyrne Yep - I can bring it up during the next design critique, for sure. :)

**Comment by MaddyDaigle** [comment]
Hey @JoshBeveridge, @Jerryescandon @BrookeCameron - I'd like to move this forward but I'm unsure if there's other work being done in this vein.  Please advise. :)

**Comment by substrae** [comment]
@tristan-orourke @gobyrne @Jerryescandon 

This relates to the conversations we had recently around having a flag for adding an alert to specific pages or sitewide. After chatting with Jerbo about it, we think it's easier to just reuse the alert component and place it below the navigation like such:

![image](https://user-images.githubusercontent.com/6960386/233456837-4f04a9a7-e688-4277-9aca-64b977d62818.png)

**Comment by petertgiles** [comment]
How do alerts get created and expired?
What happens when the alert is dismissed?  Does it ever come back?

**Comment by mnigh** [comment]
> How do alerts get created and expired? What happens when the alert is dismissed? Does it ever come back?

@GCTC-NTGC/designers is this issue still being worked on and if so, can someone answer peter's questions?

**Comment by substrae** [comment]
@mnigh @petertgiles 

So as I understand it, this whooooooole issue was proposed as a result of downtime, and then we realized it was also useful in contexts like the recent labour action. The more general idea being that when we have site-wide announcements, whether because of events, server maintenance, planned downtime, etc., we have an effective and easily toggled tool to communicate that information on the site.

I would see it acting as follows:
- There would be a way to trigger it on all pages or a handful of relevant pages
- There would be a way to specify the `type` of alert so that we could highlight urgency
- There would be a way to specify dates that the alert should show and subsequently hide
- There would be a way to specify the content inside of the alert

Given that my requirements sound an awful lot like a CMS 😉, @tristan-orourke probably has a much simpler and less invasive way to implement this behind a feature flag so that we can enable/disable it without the need for a full deploy. I'll let him wade in.
