### ISSUE TITLE
Pool Advertisement should look different for existing candidates.

### ISSUE THREAD

**Issue by JamesHuf** [GCTC-NTGC/gc-digital-talent#4300]
Currently there is no change in the appearance of the Pool Advertisement page if the user has an existing application in the pool. In addition if the user attempts to (re)apply to the pool it resets their status to DRAFT but they can't resubmit their application.
We should probably get some new copy and disable the "Apply for this process" buttons if the user already has a candidate in the pool.

**Comment by yonikid15** [comment]
I also ran into this issue during manual testing. I think instead of disabling the button we should change the "Apply to this process" link to "Continue my application" and link it back to the application. 

Also, if the application has been archived or completed, where should we redirect the user if they try returning to the application process (eg. clicking back, or manually entering url)? Since we don't have a view for a completed/archived application yet.
