### ISSUE TITLE
Replace Add Experience buttons with One Button + Modal

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4389]
One "Add Experience" button opens a modal, where selects what kind of Experience.

### Copy

```
Add a new experience to your resume
Get started by selecting the type of experience you would like to add.

Before you start describing your experience, first we would like to know what category it falls into. There are five options to choose from, you can add as many experiences to each category as you want.
```

```
Work experience
Share your experiences gained from full-time positions, part-time positions, self-employment, fellowships or internships. 
Add work experience
```

```
Education experience
Got credentials? Share your degree, certificates, online courses, trade apprenticeship, licences or alternative credentials. If you’ve learned something from a recognized educational provider, include your experiences here. 
Add education experience
```

```
Volunteer and community experience
Gained experience by being part of or giving back to a community? People learn skills from a wide range of experiences like volunteering or being part of non-profit organizations, Indigenous communities, or virtual collaborations. This could be anything from helping during events and ceremonies, DJ-ing at a friends wedding, to gaming and streaming.
Add community experience
```

```
Personal experience
People are more than just education and work experiences. We want to make space for you to share your learning from other experiences.
Add personal experience
```

```
Award
Did you get recognized for going above and beyond? There are many ways to get recognized, awards are just one of them. 
Add education experience
```

## EXP PAGE

![image](https://user-images.githubusercontent.com/16977254/216445164-d9a31522-9ef9-420c-8b4b-fa97367efda2.png)

## MODAL

![image](https://user-images.githubusercontent.com/16977254/217303458-1ed93f1b-fdbc-4c4c-a31b-4d995baf0467.png)

Acceptance Criteria:
- [ ] Replace series of five "add" buttons with single "add experience" button
- [ ] Button opens a modal with design shown up, also mobile view
- [ ] Clicking one of the "add" buttons in the dialog should navigate to the create page
- [ ] Cancel button closes dialog without navigation
- [ ] Use default behaviour of dialog initial focus on "X" in corner

**Comment by petertgiles** [comment]
@Jerryescandon 
- Any differences for mobile sizes?
- "add" buttons in dialog should functionally be links?
- Could you provide the copy of the dialog as text?

**Comment by Jerryescandon** [comment]
oh, I am unsure about this still being that relevant.

I would freeze this issue for now honestly, or ask @substrae if he has a different direction he wants to take Experience creation on the profile side.

**Comment by substrae** [comment]
So there are two paths we can take here:
- The [new application design](https://www.figma.com/proto/BXYVsu1fo9LS2IySJDUINY/Application-process?page-id=187%3A6627&node-id=187%3A6629&viewport=685%2C508%2C0.81&scaling=min-zoom&starting-point-node-id=187%3A6629) offers a solution to this problem in the sense that the "Add a new experience" button takes you to an experience page that asks you to select a type before revealing the rest of the form. This is going to be a lot of work to implement because the current experience categories each have their own page, and we'd have to merge them into one.
- Alternatively, I think @Jerryescandon has offered a pretty solid interim solution. My only suggestion would be to revisit the copy (I've attached a screenshot) to help make it extra clear that they can add many.

![image](https://user-images.githubusercontent.com/6960386/215215209-e1da520a-5ad1-4ace-9263-17fe2e175b1e.png)

**Comment by Jerryescandon** [comment]
Updated main issue with pics for the interim solution. Im removing the design tag.

**Comment by petertgiles** [comment]
@Jerryescandon

    Any differences for mobile sizes?
    "add" buttons in dialog should functionally be links?
    Could you provide the copy of the dialog as text?

**Comment by Jerryescandon** [comment]
![image](https://user-images.githubusercontent.com/16977254/217302381-b16c34a9-014a-4877-bf3d-6f4925c9dbf7.png)

**Comment by Jerryescandon** [comment]
Added copy to issue, added image with mobile.
