### ISSUE TITLE
Can't navigate back from 404

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4411]
If you end up at the 404 page you can't actually navigate back to the previous page.  If you click back you go to the URL that doesn't exist and are immediately redirected to the 404 again.  It's quite annoying!

**Comment by mnigh** [comment]
@petertgiles I guess you should have clicked the **Report a missing page** link 😉

**Comment by esizer** [comment]
Hmm, maybe instead of redirecting to `/404`, we should just render a generic `NotFound` component? I think that is what we were doing before the redirect was put in place.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/1484e37a428c51fd6764e744ecbcca543cf6e0f5/frontend/common/src/helpers/router.tsx#L196-L200
