### ISSUE TITLE
Refresh token doesn't work for the second tab 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4523]
### Problem 

Opened after testing #4297 
Refresh token that got in first tab is not effective on the second tab and logged out the user. Upon refreshing the second tab got the new access token without logging in  

### Steps to test

1. login to account /login on Production
2.  open 2 tabs
3.  wait 12 (maybe 15) minutes
4.  go to your profile in first tab and confirm that a access token refresh occurs
5.  go to your profile in second tab and confirm that a new access token appears  - `Failed` 

### Acceptance Criteria 
#5 above should pass

**Comment by tristan-orourke** [comment]
Judging from Brinda's description, I expect what happens is that when one tab uses a refresh token, it gets a new one. But the second tab still has the original refresh token in memory, which is no longer valid. The solution should to make sure that:
1. whenever we get a new refresh token, we immediately store it in localStorage
2. whenever we want to use a refresh token, we get it from localStorage instead of relying on what's in memory.

**Comment by brindasasi** [comment]
This might help .. to detect if there is a change in local storage 
https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event

**Comment by petertgiles** [comment]
> detect if there is a change in local storage

Yeah, I saw some pages about that too and I really the idea.  The PR I posted is a simple "2 point" fix but if we decide not to move to that other auth library I'd like to put in logic to sync up the auth state between tabs using storage events.
