### ISSUE TITLE
Webpack outputs asset size warnings

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4570]
## Description
Webpack outputs asset size warnings on every run.

## Screenshot
![Screen Shot 2023-03-07 at 10 46 46](https://user-images.githubusercontent.com/3046459/223476744-3ee26054-e24d-47a1-9c4e-384d98d1db7e.png)

## Questions
1. Should we increase the [maxAssetSize](https://webpack.js.org/configuration/performance/#performancemaxassetsize) and if so, to what value?
2. ~Should we attempt to decrease the asset sizes?~ (completed in https://github.com/GCTC-NTGC/gc-digital-talent/issues/5355)

## Acceptance Criteria
- warning threshold set to 500K

**Comment by esizer** [comment]
I did notice a lot of our image assets are `.png` and I'm wondering if this was done on purpose for some reason? I mention this because `.png` is a lossless format and can cause inflated image sizes. I think, if we can, we should be converting most image assets to either `.svg` or `.jpeg` where possible to save some bytes.

I think we should avoid `.png` unless we require transparency or the clarity is of utmost importance (text, icons) and an `.svg` will not work.

**Comment by mnigh** [comment]
@GCTC-NTGC/developers should we increase the [maxAssetSize](https://webpack.js.org/configuration/performance/#performancemaxassetsize) and if so, to what value? If not, this issue should be closed.

**Comment by petertgiles** [comment]
Let's do 500K
