### ISSUE TITLE
Admin sidemenu not collapsing

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#4678]
## Description
It hides text but doesn't actually collapse or close

## Video
https://recordit.co/oHh0s45DFu

## Acceptance Criteria
- [ ] Resolve bug

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by vd1992** [comment]
on small view the menu is just gone

![image](https://user-images.githubusercontent.com/40485260/200915337-23e6fc99-cdb5-4ae6-b58c-2b499c45178d.png)

**Comment by esizer** [comment]
So, I thought I broke this and fixed it in https://github.com/GCTC-NTGC/gc-digital-talent/pull/4597

The problem was our side menu buttons were missing the appropriate class name.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/83711f80f858fe08a3f6b1d2a34de5796a4cd973/frontend/common/src/components/SideMenu/SideMenuItem.tsx#L94-L107

**Comment by vd1992** [comment]
guess that PR of yours is closing another issue then

**Comment by esizer** [comment]
Closed by #4597
