### ISSUE TITLE
Add "Secure" attribute to all encrypted session (SSL) cookies

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5002]
See report in #5000 for details.

Questions: where are these cookies coming from? Is Laravel generating them?

## Acceptance Criteria
- [ ] All cookies on our site use the Secure attribute.

**Comment by mnigh** [comment]
I couldn't reproduce any cookies with **Secure** equal to `false` on the production site. Perhaps this issue is still since the security scan was done nearly a year ago? What do @GCTC-NTGC/developers think?

## Screenshots

![Screen Shot 2023-11-14 at 15 40 37](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/0c152ee3-61e6-4142-81d0-691f14e240c7)

![Screen Shot 2023-11-14 at 15 36 23](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/42cfcca5-1464-439c-8bd9-346512020d85)

**Comment by esizer** [comment]
> I couldn't reproduce any cookies with **Secure** equal to `false` on the production site. Perhaps this issue is still since the security scan was done nearly a year ago? What do @GCTC-NTGC/developers think?

Yeah, only cookies I could find that where `Secure` was not `true` were base canada.ca cookies most of which were related to google analytics 😅 .

**Comment by petertgiles** [comment]
They all look secure to me.  Let's close it.

**Comment by mnigh** [comment]
Can't reproduce cookies with `Secure` equal to false on the production site. Closing as **can't repro**.
