### ISSUE TITLE
🐜 Accessibility Bug: Additional Comments field - Search Request form

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#5488]
## ❌ Current behaviour (issue)
Additional Comments edit field does not seem to allow the screen reader user to switch from first letter navigation to text typing once their focus is inside the field.
###AT Configuration:
JAWS, Windows, Edge
### How to reproduce
1. Using JAWS, fill in all required fields in the Search Request form
2. Tab to the Additional comment box
3. Enter text  in the fiels using your keyboard.  
### Fable Video Clip
[Additional Comment Box Bug in Search Request Form](https://app.makeitfable.com/share/63d1e1a184cfb4002e8a3b30)
## ✔ Expected behaviour (fix)
JAWS screen reader user can type in the Additional Comments field without initiating an unintended context change 
### Acceptance Criteria
- [ ] JAWS screen reader user can type in the Additional Comments field without initiating an unintended context change

**Comment by petertgiles** [comment]
Thanks for this one, Rosalie.  I'm having trouble replicating this issue since I don't have access to JAWS.  With tab navigation the form seems OK and input is fine with backspace, enter, etc.

Do you have access to this tool?  Could you help me understand what need to change to make this form work better?

**Comment by esizer** [comment]
No longer applies.
