### ISSUE TITLE
♻️ Debt/Refactor - User.php has a relation to departments

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#5538]
## ♻️ Debt/Refactor

The User model has a relation to the Department model as seen here
https://github.com/GCTC-NTGC/gc-digital-talent/blob/524e68151c303ab925584c6d4a9d394856380e28/api/app/Models/User.php#L92-L94

Department model has no such relation to User
https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/api/app/Models/Department.php

Nor does a pivot appear to exist for user to department tables

## 🕵️ Details

Appears to be unused and possibly a mistake?

## 🙋‍♀️ Proposed Solution

Deletion

## ✅ Acceptance Criteria

- [ ] Resolve whether the relation is needed if so, make it functional

**Comment by petertgiles** [comment]
Do we build the inverse relationship, deleted the unused relationship, or leave it alone?

**Comment by vd1992** [comment]
@tristan-orourke 
Thoughts on the above?

**Comment by tristan-orourke** [comment]
Leave it alone or add the inverse relationship, but this is not a mistake.

Users have a relationship to departments because a user can belong to a department, if they are a gov employee. There is no pivot table because a user can only belong to one dept, meaning we can simply have a `department_id` column in the user table.

My perspective on the inverse relationship has been: we don't have any reason to query Users by Department yet, so why bother defining the relationship? But if you find it confusing that it is missing, we can add it. It may end up useful later this year anyway.
