### ISSUE TITLE
✨ Applicant Dashboard - Create Story book Hero Area Profile and Experience Components

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#5688]
## ✨ Feature

Hero area is the top part of Applicant Dashboard 

## 🕵️ Details

The hero area consists of two (eventually three) blocks that each summarize and provide access to the user's profile information and their skills and experience information. Each card's title should link to the respective pages, while in the case of the profile information, each section should link directly to the appropriate edit form. Sections that have errors or are missing required information are highlighted in red, while completed sections receive a checkmark. This creates a sense of completion as the user progresses through providing the information.

## 🎨 Design File

Figma file: https://www.figma.com/file/jHsXzqMfBtomLa1Gom94Y7/Profile-dashboard?node-id=310%3A4163

<details>
  <summary><strong>📸 Screenshot: full dashboard</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/217913070-4d3651c3-178a-44d4-a060-4ec67d874114.png" />
</details>

<details>
  <summary><strong>📸 Screenshot: hero area with data</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/217912756-0aae5d09-ad84-4fdd-a430-b9d8214d1d1b.png" />
</details>

<details>
  <summary><strong>📸 Screenshot: hero area without data</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/218117973-056fd7bc-ef0d-490f-8a2f-e66a7e7b7d43.png" />
</details>

## 🙋‍♀️ Proposed Implementation

A generic card component that can act as profile or experience component based on the props passed on 
OR 
A base card component and wrap it with a profile wrapper and experience wrapper 
OR 
may be something better :) 

## 🌎 Localization

Refer figma for the english copy 

## ✅ Acceptance Criteria

- [ ] Profile experience icons go with boolean value ( completed icon , not completed icon )
- [ ] Experience icons go with count of experiences ( 0 , 1 , 2 ..etc) 
- [ ] Each item in the component should be a link to the relevant section regardless whether they are empty or filled in 

From the design team:
- [ ] When viewing the page, the user's profile sections display whether they are complete or not
- [ ]  When viewing the page, the user's experiences are summarized by type
- [ ]  When clicking on the "My profile information"/"View" link, the user is taken to a modified profile UI where they can manage their profile information
- [ ]  When clicking on a profile section, the user is brought directly to that section's edit page.
- [ ]  When clicking on the "My resume and experiences"/"View" link, the user is taken to the Skills and experience UI

**Comment by petertgiles** [comment]
@substrae For mobile views should these two (eventually three) blocks stack up or stay side-by-side?

**Comment by petertgiles** [comment]
@substrae I followed the figma link and it looks like the resume block now has icons instead of numeric badges.  Also, each item has a subline.  Have the requirements for this issue changed?


![Image](https://user-images.githubusercontent.com/8978655/221665604-f9b048e7-f6dc-4c0e-a82c-cbeab35116fa.png)

**Comment by substrae** [comment]
@petertgiles Sorry for the delay!

Mobile view:
- Yep, you got it - stack them vertically (ideally we use a grid) and then have them adjust accordingly (likely `l-tablet`)

Card requirements:
- Sorry about the confusion on this one - we had a few post-issue debates about how to best communicate whether a section with optional info was considered "complete" while still being able to indicate to the user that there were optional questions they could answer
- The screenshot you've taken is my latest, and IMO best attempt, at communicating that information; as long as you make sure the pseudo-card components built for this page have that information in there, I will handle any further layout/visual changes as needed so that you aren't dealing with changing requirements
  - Profile card
    - Alert icon if a `required` section is missing information
    - Checkmark icon if the section is complete and valid or all `required` fields are complete and valid
    - Section titles should link to the edit form for that respective section
    - I think the three types of subtitle are literally self-describing, but feel free to reach out if I've missed something
  - Résumé card
    - Each of the types has an associated icon already (see the experience accordion component)
    - Subtitle should indicate number of that type in the user's profile (including handling of 0, singular, and plural formatting)
- @Jerryescandon @RM-1978 @gobyrne feel free to leave any comments, but I'll have things built this way for now and make changes myself if we decide there's a better layout

Copy inconsistencies:
- Keep the current order as is - a larger profile rework is on the way, and we can handle this rearrangement then
- In terms of title case - the [GoC content standards say we should be using sentence case exclusively](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-style-guide.html#wp4-1-1) (with the exception of proper nouns/names)
- I believe the "Role and salary" section is going away, though @gobyrne and @Jerryescandon can confirm that for us; in terms of this page build, removing it is out of scope, so include it as is
- Experience types are undergoing a name review - keep them as they currently are for now, and we'll lump the name changes in a separate ticket 
- In terms of résumé - if I had my way, it would be `résumé` everywhere, because that's technically the correct spelling; if you're telling me it's consistent everywhere else but here, go with the consistency for now
