### ISSUE TITLE
Get notified of jest warnings

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5846]
Jest warnings, like not using act, should notify us somehow.  Is there a Github Actions warning result?

![image](https://user-images.githubusercontent.com/40485260/222542974-d1b543ae-3856-47ac-99ef-4e4010c124a9.png)

_Originally posted by @vd1992 in https://github.com/GCTC-NTGC/gc-digital-talent/issues/5844#issuecomment-1452495114_

Acceptance Criteria:
- Warnings from Jest notify the PR author in some way

**Comment by vd1992** [comment]
one option is to make it fail on warning, this is something that could help with that
https://github.com/ValentinH/jest-fail-on-console

**Comment by petertgiles** [comment]
> one option is to make it fail on warning

Yeah, that's probably simplest.  I'm not sure if it's possible but I'd like to see the action go to the yellow warning dot if possible.  Let the author know but don't block merge.

**Comment by mnigh** [comment]
> I'm not sure if it's possible but I'd like to see the action go to the yellow warning dot if possible. Let the author know but don't block merge.

@petertgiles Not sure this makes sense since yellow indicates in progress. Or, is even possible since there are only success or failure [exit codes](https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions#about-exit-codes). At one point, [there was a neutral status in GitHub actions](https://github.com/actions/toolkit/issues/146) but that has been removed.
