### ISSUE TITLE
Missing translation - "Skip to main content"

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5991]
## 🐛 Bug

The IAP page is reporting a missing translation for "Skip to main content"

## 🦋 Expected Behaviour

All content should be translated.

## 🕵️ Details

- **Browser**: Firefox 111.0

We have a translation CI flow that should catch this.  How did it get missed?

## 📋 Steps to Reproduce

1. Navigate to http://localhost:8000/fr/indigenous-it-apprentice
2. Check your browser console
3. Check your browser a11y tree

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/8978655/225932016-aba73c2d-b04e-427a-b76f-da56d440dfde.png)
![image](https://user-images.githubusercontent.com/8978655/225932128-cb006325-6fa6-428a-bae4-56973443113e.png)

## 🙋‍♀️ Proposed Solution

This string is from packages/ui.  Perhaps this package isn't set up to be tracked by the translation CI?  There's no `lang` directory in that package.

Or is it thrown off by the nested intl context?

## ✅ Acceptance Criteria

- [ ] move string out of untranslated package
- [ ] Add the missing translation.
- [ ] Add to tc-report

**Comment by vd1992** [comment]
I think I got an idea of what is going on here, there is no translation for that package like you said.
Normally we don't seem to have translations in that folder, but import them from /i18n, like with these

![image](https://user-images.githubusercontent.com/40485260/225985670-f33aea2e-2b3d-437b-ac07-e09eba4d9dbb.png)

![image](https://user-images.githubusercontent.com/40485260/225985755-edf7c375-de8e-4ea3-9a77-eec050127866.png)

**Comment by vd1992** [comment]
gives two solutions

- add translations, lang folder, and intl workflow to additional packages
- never add messages directly into other packages, only to /web or /i18n

I like option two as that way we don't end up with potentially a dozen intl workflows to cover all packages

**Comment by mnigh** [comment]
Looks like the skip link copy made it in [here](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2528) but never got translated into French (and was before we had the translation check workflow).

This issue is actually a problem on the entire site rather than just IAP and is a problem in tc-report as well.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/4c00217b804e2aef089c8df53240a7e126009a81/packages/ui/src/components/Link/SkipLink.tsx#L25-L27

https://github.com/GCTC-NTGC/gc-digital-talent/blob/4c00217b804e2aef089c8df53240a7e126009a81/tc-report/_layouts/boilerplate.html#L5

## Screenshots


![Image](https://user-images.githubusercontent.com/3046459/226627547-6229ecb5-512f-4c2d-855a-bd25506cb602.png)
![Image](https://user-images.githubusercontent.com/3046459/226627548-aa6c1535-c79e-4c16-a433-6be73102ea27.png)
