### ISSUE TITLE
✨Application Revamp: Placeholder pages with urls and breadcrumbs and steps

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6027]
## ✨ Feature

Setup placeholder pages (with routing) for the Application steps.

## 🕵️ Details

The hero and stepper component are essentially the same on each step, with only minor changes to the breadcrumbs. This may be a good place to use the _Layout and <Outlet/> pattern enabled by React Router.

## 🎨 Design File

https://www.figma.com/file/BXYVsu1fo9LS2IySJDUINY/Applicants---Application?node-id=636-59839&t=kmjTtgdWWyX0ddZ9-0

## 📸 Screenshot

![Image](https://user-images.githubusercontent.com/89482910/225649515-6dd646ec-8a02-414d-b157-3531ca5acff7.png)

## 🙋‍♀️ Proposed Implementation

Proposed urls for the steps (open to suggested changes):
- applications/:id/welcome
- applications/:id/profile
- applications/:id/resume-introduction
- applications/:id/resume (or /experiences?)
- applications/:id/resume/add (or /experiences/create?)
- applications/:id/resume/:id (or /experiences/:id?)
- applications/:id/education
- applications/:id/skills-introduction
- applications/:id/skills
- applications/:id/questions-introduction
- applications/:id/questions
- applications/:id/review
- applications/:id/success

Note that the introduction pages show the same step (in the Stepper component) as the main page, all the resume/experience pages show the same step, and the success page shows no "current" step.

## 🌎 Localization

(optional) Provide any new copy along with translations available

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] All the application step pages exist under their own urls
- [ ] Pages are accessible only when the feature flag "Application Revamp" is ON 
- [ ] Stepper on each page shows the correct current page
- [ ] Each page displays the Hero, breadcrumbs, and Stepper component, with the main content left empty for future stories.

## :stop_sign: Blockers
Blocked by #5875

**Comment by tristan-orourke** [comment]
Made high priority because this will block other issues.

**Comment by esizer** [comment]
I'm wondering, the "Introduction" pages not being in the stepper is sort of complicating things. Since we aren't using loaders and doing all of the data fetching in the pages themselves for `react-router` we can't leverage `useMatches` to pass the step back up to the layout.

This is making it difficult to determine all of the steps required when some of the pages do not appear in the stepper.

Do they need to be separate pages or could we render different content based on a search param or some other value? 🤔 Or is that what https://github.com/gctc-ntgc/gc-digital-talent/issues/5985 is meant for? 

Is the intention that if the state is null for say skills, we render the intro and when the user clicks "Let's get to it!" we store a state and they no longer see the intro for that application?
