### ISSUE TITLE
❓ Investigate slow load times on production

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6071]
## ❓ Question

- How slow are page load times in production, especially first-time visits
- What are the bottlenecks on the slowest loads?

## 🕵️ Details

Add any additional details that could assist with answering the question posed.

Timebox: 2 hours

**Comment by petertgiles** [comment]
Similar on IAP:
![image](https://user-images.githubusercontent.com/8978655/229154340-8723631d-f2db-4b9c-a3ba-acb5ad42e59d.png)
1. Fonts loading multiple times
2. Long stall on favicon

**Comment by petertgiles** [comment]
Lighthouse check on homepage:
![image](https://user-images.githubusercontent.com/8978655/229155449-fb46451e-9c98-4715-aea6-79ad9ea28257.png)
Recommended improvements:
|Opportunity|Estimated Savings|
|---|---|
|Enable text compression|1.36s|
|Reduce unused JavaScript|0.8s|
|Serve images in next-gen formats|0.32s|
|Properly size images|0.24s|
|Use HTTP/2|0.24s|

|Diagnostics||
|---|----|
|Serve static assets with an efficient cache policy|15 resources found|
|Registers an unload listener||
|Avoid enormous network payloads|Total size was 3,156 KiB|

**Comment by petertgiles** [comment]
Some regular page loads.  Nothing too surprising here.
|url|time|notes|
|---|---|---|
|https://talent.canada.ca/en/|1700ms|
|https://talent.canada.ca/en/search|747ms|
|https://talent.canada.ca/en/browse/pools|985ms|
|https://talent.canada.ca/en/users/{:userId}/profile|2200ms|
|https://talent.canada.ca/en/users/{:userId}/profile/about-me/edit|905ms|
|https://talent.canada.ca/en/users/{:userId/profile/employment-equity/edit|868ms|
|https://talent.canada.ca/en/users/7a462fb0-a0ce-4392-b42f-3e43a788f07d/profile/language-info/edit|831ms|
|https://talent.canada.ca/en/users/7a462fb0-a0ce-4392-b42f-3e43a788f07d/profile/government-info/edit|1220ms|
|https://talent.canada.ca/en/users/7a462fb0-a0ce-4392-b42f-3e43a788f07d/profile/work-location/edit|1000ms|
|https://talent.canada.ca/en/users/7a462fb0-a0ce-4392-b42f-3e43a788f07d/profile/work-preferences/edit|898ms|
|https://talent.canada.ca/en/users/7a462fb0-a0ce-4392-b42f-3e43a788f07d/profile/role-salary-expectations/edit|4270ms|delay was waiting for .js bundle, was not reproducible on reload|
|https://talent.canada.ca/en/users/7a462fb0-a0ce-4392-b42f-3e43a788f07d/profile/experiences|825ms|

**Comment by petertgiles** [comment]
These are my recommendations:

- The slowest part of every page load is the downloading and running the first big .js bundle.  If we can reduce the size of that bundle it should make a big difference.
- The vast majority of our page loads is downloading static content, not API calls.  The size of these assets is large and download speed is quite variable.  We should see if we can get these cached or mirrored closer to the user so that they're rarely hitting our actual web server.
- Lighthouse is predicting a big improvement on enabling text compression.  This seems like it will be an easy win.
  - https://developer.chrome.com/docs/lighthouse/performance/uses-text-compression/?utm_source=lighthouse&utm_medium=devtools
- Lighthouse identified that we're not setting a cache policy on our assets.  This doesn't affect first-time visitors but should be an easy win for repeat visits.
  - https://developer.chrome.com/docs/lighthouse/performance/uses-long-cache-ttl/?utm_source=lighthouse&utm_medium=devtools
- Lighthouse recommends using AVIF and WebP instead of JPEG and PNG to further reduce image sizes.  It notes that compatibility is more limited but there are ways to serve fallbacks.
  - https://developer.chrome.com/docs/lighthouse/performance/uses-webp-images/?utm_source=lighthouse&utm_medium=devtools
- For pages with dark mode we're forcing every visitor to download both sets of images.  We should avoid this doubling of data.
- Lighthouse recommends switching to HTTP/2.  It doesn't predict a big time savings and this probably happens at a reverse-proxy upstream of us but we may want to investigate anyway.
  - https://developer.chrome.com/docs/lighthouse/best-practices/uses-http2/?utm_source=lighthouse&utm_medium=devtools
- Lighthouse recommends optimizing Largest Contentful Paint on IAP especially since it has a very large image (hero.jpg) and could save 1.37s.  This would probably require serving a custom index.html to preload it for that path but this is something we would like to do to serve English and French titles anyway.
  - https://web.dev/optimize-lcp/?utm_source=lighthouse&utm_medium=devtools#preload-important-resources

**Comment by vd1992** [comment]
attempted text compression in #6151

**Comment by petertgiles** [comment]
That perf improvement looks yuge!  :laughing: :clap: 

We'd probably only want to gzip it on prod builds to keep dev speedy.  We'd also need to test in Azure to make sure it works well deployed, too.

**Comment by vd1992** [comment]
playing around on the /api front locally, not exhaustive
the queries generally took 0.5 - 1.5 seconds, but the `allPools` one took the longest consistently at almost 3 seconds
not slowed down by generating a large response, but slowest server side of things

merits keeping an eye on, especially if further query changes happen or when more pools exist, things could get real slow

![image](https://user-images.githubusercontent.com/40485260/229220423-d95a6ca5-64c7-406f-bc7b-0e4c03aca7f6.png)

**Comment by petertgiles** [comment]
> Out of curiosity, was there simulation of CPU throttling here?
No, I didn't go that deeply into it - the timebox was only two hours.  I'm not sure that it would reveal anything extra - just exaggerate the slow points.  Though I'm sure that audience would appreciate even more any improvements that we could make.  :smile:

**Comment by esizer** [comment]
> * The slowest part of every page load is the downloading and running the first big .js bundle.  If we can reduce the size of that bundle it should make a big difference.

I wonder if we could try and split off more code than just the pages themselves 🤔 We could also run[ `webpack-bundle-analyzer`](https://www.npmjs.com/package/webpack-bundle-analyzer) to see if anything can be shaken out more or split off into its own bundle.

Or push for SSR 😜.

> * The vast majority of our page loads is downloading static content, not API calls.  The size of these assets is large and download speed is quite variable.  We should see if we can get these cached or mirrored closer to the user so that they're rarely hitting our actual web server.

Do we have any options for CDNs with azure? Might be worth loading at least images from the CDN where they are hopefully cached on the edge.

> * Lighthouse recommends using AVIF and WebP instead of JPEG and PNG to further reduce image sizes.  It notes that compatibility is more limited but there are ways to serve fallbacks.

Yeah, these formats are just so much better than the alternatives. I wonder if we could create an incredibly rudimentary `Image` component that takes a file name with available extensions and spits out the `<picture>` element with the appropriate source sets and fallbacks.

> * For pages with dark mode we're forcing every visitor to download both sets of images.  We should avoid this doubling of data.

Yeah, I'm pretty sure right now we are just hiding them with CSS but instead we should unmount it depending on the current mode.

> * Lighthouse recommends switching to HTTP/2.  It doesn't predict a big time savings and this probably happens at a reverse-proxy upstream of us but we may want to investigate anyway.

WOAH, we aren't using HTTP/2 yet? 😅 This is actually [super important for code splitting](https://www.smashingmagazine.com/2022/02/javascript-bundle-performance-code-splitting/#:~:text=Overzealous%20code%2Dsplitting%20can%20even%20harm%20performance%20in%20cases%20where%20the%20bundles%20are%20served%20via%20HTTP%201.1%20which%20lacks%20multiplexing.) and I would say it is fairly high priority if we are concerned about performance.

**Comment by petertgiles** [comment]
#6161
#6162
#6163
#6164
#6165
#6166
#6167
#6168
