### ISSUE TITLE
🐛 Edit Team Fails on UAT and local

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#6115]
## 🐛 Bug
Editing team description throws error in release [2.7.2](https://github.com/GCTC-NTGC/gc-digital-talent/releases/tag/v2.7.2)

## 🦋 Expected Behaviour

User should be able to edit team successfully
## 🕵️ Details

Found on UAT testing but can be reproduced in local as well. 
I wonder if this has anything to do with the roles. 
Our Admin user and it has platform administrator and request responder roles. 
Query that fails :  `updateTeam`

## 📋 Steps to Reproduce

1. Navigate to admin/teams page
2. Click on any team and open the edit page
3. Update description 

## 📸 Screenshot

[Screenshot 2023-03-29 at 4.20.31 PM.png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/966ce418-8456-4194-a05b-e09abf86ce6c)?
## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] User should be able to update all fields on the teams page 

## 🛑 Blockers

Blocked by {issue numbers}

**Comment by vd1992** [comment]
error message makes me guess authorization
admin has platform_admin, pool_operator, and request_responder

what team does this pool belong to?
platform admin enables viewing the edit pool page for all pools (to publish, not update)
pool operator enables updating pools that share a team with you

if this pool does not belong to test-team or dcm-team, then this is failing as it should

**Comment by vd1992** [comment]
ugh, I can't read 😵

**Comment by vd1992** [comment]
replicated locally

![image](https://user-images.githubusercontent.com/40485260/228956603-cfe12b27-6d95-49ed-9ff7-3c5e9f324bd1.png)

likely due to passing in roleAssignments in the dataToFormValues function, this is an empty array that gets passed along and appears again, secretly, in formValuesToSubmitData 

![image](https://user-images.githubusercontent.com/40485260/228959951-58a80d42-5a5b-44e6-809a-7610d6f9bd8d.png)

![image](https://user-images.githubusercontent.com/40485260/228960046-88680334-b686-498f-a0a0-c443145fc37c.png)
