### ISSUE TITLE
Perf - serve images as AVIF and WebP

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#6165]
## ♻️ Debt/Refactor

Lighthouse recommends using AVIF and WebP instead of JPEG and PNG to further reduce image sizes. It notes that compatibility is more limited but there are ways to serve fallbacks. 

## 🕵️ Details

https://developer.chrome.com/docs/lighthouse/performance/uses-webp-images/?utm_source=lighthouse&utm_medium=devtools

## 🙋‍♀️ Proposed Solution

Eric's note:
> Yeah, these formats are just so much better than the alternatives. I wonder if we could create an incredibly rudimentary Image component that takes a file name with available extensions and spits out the <picture> element with the appropriate source sets and fallbacks.

## ✅ Acceptance Criteria

- [ ] Images, especially large ones service in AVIF and/or WebP
- [ ] Fallback to older formats for clients who can't accept newer ones

**Comment by esizer** [comment]
Happened to stumble across a hook, [mbrevda/react-image](https://github.com/mbrevda/react-image), that seems to do what we are looking for. Looks like it is getting regular updates and is fairly popular with:

- 1.1K GitHub stars
- 90K weekly npm downloads

I'm wondering if this is something we could use rather than rolling our own? 🤔
