### ISSUE TITLE
✨ Change default column and move column

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6315]
## ✨ Feature

DCM wants preferred language of communication to **show up by default** on the View Candidates page inside the Pool flow

They would also like this column to show after the name.

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/232868991-6e5f112e-59cb-4bd6-a010-2550d41696cb.png)

![image](https://user-images.githubusercontent.com/16977254/232869211-7d8ed1cf-fcbf-4ea1-a29e-0adcf8294ce9.png)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Preferred communication language visible by default
- [ ] Preferred communication language after name in table

**Comment by mnigh** [comment]
@Jerryescandon is this change intended for both the **Candidates** table and the **Candidate Results** table within the **View Request** page? I ask because they use the same underlying component, `PoolCandidatesTable`.

## Screenshots
![Screen Shot 2023-04-25 at 16 10 08](https://user-images.githubusercontent.com/3046459/234391635-8297a937-3f1c-41c1-9b3f-97068bcd5dc2.png)

![Screen Shot 2023-04-25 at 16 12 26](https://user-images.githubusercontent.com/3046459/234392028-94d09e78-5e3c-4fe3-90e7-7c07dac0bad0.png)

**Comment by Jerryescandon** [comment]
It was only meant for the table inside the view candidates in a pool, not in the request. 
BUT
I would say lets do the easy fix, if doing it once updates both then let's do that. And if they find they want it removed from the other table, we will do that at a later date if they request it.
