### ISSUE TITLE
✨ Improve copy on request page Notes

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6464]
## ✨ Feature

Change the subtitle and add a description to better represent what the notes are about.

## 🎨 Design File

[Link to figma
](https://www.figma.com/file/dDo0sUzYFyplp7DvlLHKYJ/Admin---Requests-details?type=design&node-id=202%3A2252&mode=design&t=VstzTe4cZr2CXvXD-1)

## 📸 Screenshots

<details><summary>Old design</summary>
<p>

![image](https://user-images.githubusercontent.com/16977254/235516194-20dd9115-ebc7-4b0c-987c-ca441967fe98.png)

</p>
</details> 

<details><summary>New design</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/0b9506a6-ecbe-4d6a-aa71-efb210f6236b)

</p>
</details>

## 🙋‍♀️ Proposed Implementation

- [ ]  Update title 
- [ ]  Add sentence between title and form field
- [ ]  Update form field label to sentence case
- [ ]  Update button copy to sentence case

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] title uses new copy 
- [ ]  description sentence appears between title and `textarea` field
- [ ]  `textarea` label appears in sentence case
- [ ]  `button` label appears in sentence case

**Comment by mnigh** [comment]
@Jerryescandon since we use [sentence case for titles, headings, and subheadings](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-style-guide.html#wp4-1-1), would you mind updating the figma file and the screenshot in this issue to reflect that? Also, we have stopped using placeholder text for `input` and `textarea` fields: could you remove that as well?

## Screenshot
![235516166-784000c2-4bd8-41f8-9572-e816ffc556f5](https://user-images.githubusercontent.com/3046459/235940055-954847df-3e7a-4758-9ebd-211150f421ef.png)

**Comment by mnigh** [comment]
@Jerryescandon a few requests:

1. Can we change the word **visible** to **available** in "These notes are visible to all request responders, but not to candidates" to avoid using non-inclusive language?
2. The figma link in the description seems to be 💀: could you update it to a working link?

**Comment by Jerryescandon** [comment]
Fixed and updated. 👍

**Comment by brindasasi** [comment]
@Jerryescandon we don't show `optional` word any more for optional fields. 
Could you update the figma accordingly ?
