### ISSUE TITLE
Application - Review Resume - Experience sort confusing

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#6471]
## :wave: Introduction
I don't think anything is actionable here but I'm a little confused as to how sorting by type works unless I read the code. As a user, I don't think this is useful, how is a user meant to know how this will function and in what scenario would it be used? 🤔 

Date is still less confusing but is it created, update, start or end? I think we just need to add some more context to these options so it is clear to users what they are sorting on and have an understanding of the expected outcome.

_Originally posted by @esizer in https://github.com/GCTC-NTGC/gc-digital-talent/pull/6457#discussion_r1182541369_
            
## :camera_flash: Screenshot
![image](https://user-images.githubusercontent.com/8978655/235727730-424dfaa5-8292-4910-9c15-426e0fc6cca9.png)

## :spiral_notepad: Acceptance Criteria
- [ ] Criteria 1

**Comment by mnigh** [comment]
I would suggest:
- Start date (latest to oldest)
- Type (A to Z)

**Comment by petertgiles** [comment]
Maybe relevant, maybe not, but awards only have an "award date".  They don't have start and end dates.

**Comment by mnigh** [comment]
> Maybe relevant, maybe not, but awards only have an "award date". They don't have start and end dates.

😢 Completely correct. Because even though we call an award an experience, it is not really an experience. It is the recognition of an experience. Words matter!

**Comment by vd1992** [comment]
> > Maybe relevant, maybe not, but awards only have an "award date". They don't have start and end dates.
> 
> 😢 Completely correct. Because even though we call an award an experience, it is not really an experience. It is the recognition of an experience. Words matter!

I don't know, award shows are quite the experience I'd contend

**Comment by tristan-orourke** [comment]
@substrae could you make the figma changes we talked about and link them here?

**Comment by substrae** [comment]
So because this was a stop-gap measure to simplify the design at the time, here's where I think we should move:

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/c0494cea-ed72-404d-8c80-eb1e7abe40df)

Basically, sorting the list and filtering the list are two different actions. Sorting should reorder the list of filtered items.

Sort by:
- Date (recent first)
- Date (oldest first)
- Title (A-Z)
- Title (Z-A)
- Last modified (for future iterations)
- Date created (for future iterations)

Filter by type:
- All types
- Awards and recognition
- Community participation
- Education and certifications
- Personal learning
- Work experience

**Comment by mnigh** [comment]
Completed as part of #7001, thanks @petertgiles.
