### ISSUE TITLE
✨ Update education requirements on IAP Application

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6483]
## ✨ Feature

Change the text of the Education requirements if on the IAP Application

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🎨 Design File

https://www.figma.com/file/8piNhFaBjcxssBB8LAGxEY/IAP-User-flows?node-id=269-76867&t=FM1b6mI8HeHY19YM-0

## 📸 Screenshot

![Experience and education requirements.jpg](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/3139fb68-1d39-4193-bc12-e3708e05f068)

## 🙋‍♀️ Proposed Implementation

The switch can happen based on whatever we decide in #6461, or it can use the hydrogen theme to hide/show elements.

The fields saved to the application are the same as an original application. EducationRequirmentOption.EDUCATION can be interpreted as High School instead of Post Secondary

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

- [ ] On an IAP application, text on the Education step matches the design

**Comment by substrae** [comment]
@vd1992 

Great question! The edu requirement should look like the screenshot you've posted, so for this specific issue, all you're doing is updating the copy. The IAP iteration of the application was put together before the final changes to the actual application y'all are building (so that we could test with enough time), meaning some of the UIs were slightly out of date compared to final product we handed off.

Feel free to reach out if you have any other questions!

**Comment by vd1992** [comment]
Thank you! Makes sense to me!
