### ISSUE TITLE
🐛 Using back button after switching locales triggers not found

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#6611]
## 🐛 Bug

Using the back button after switching locales triggers a not found page.

## 🦋 Expected Behaviour

The back button should navigate to the previous page in the correct locale.

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: macOS 12.6.5 (21G531)
- **Browser**: Chrome 113.0.5672.92 (Official Build) (x86_64)

## 📋 Steps to Reproduce

1. Navigate to https://talent.canada.ca/
2. Click **Search** link
3. Click **Login** link
4. Click **Français** link
5. Click back in browser
6. Observe 404 Not found page

## 📸 Screen Recording

https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/e07eb888-c652-4629-8be6-f37e2b687e3e

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] back button navigates to the previous page in the correct locale

**Comment by vd1992** [comment]
I cannot get an error page to show up, but it does appear to not back/forward as expected. From my perspective, if you imagine the locale switcher overwrites the page you are on in the history stack things make sense. 

en/search -> /en/browse/pools -> /fr/browse/pools
if you attempt to go backwards it becomes
/fr/browse/pools ->/en/search

The /fr overwrites the /en in the history stack rather than become a separate entity. 

https://recordit.co/ISK7EnFADY
