### ISSUE TITLE
✨ Add 'Download All' state to tables with downloadable data

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#7021]
## ✨ Feature

Based on https://github.com/GCTC-NTGC/gc-digital-talent/issues/7018

DCM has pools with over 1500 applicants. They wish to download the entire list of applicants (CSV spreadsheet) for assessment tracking.

We have so far avoided implementing this out of fear of how much load this would put on the server.

This feature would aim to add a button option to the table that allows users to download an entire data set regardless of selections, pages or page-size.

Since this action might increase the wait time before the download can commence, we should also include a Toast notification that can set the right expectations for our users and instruct them not to navigate away.

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

<details><summary>Current design</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/f86cc9e1-3776-40b9-acd4-1c5db588167d)

</p>
</details> 

<details><summary>Proposed design</summary>
<p>

### OLD TABLE
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/f2b2ffef-1249-48c2-ae98-2f82dbb62588)

### NEW TABLE
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/010a2504-7d91-47b1-adb9-d6ca1375a53e)

</p>
</details> 

<details><summary>Toast notification</summary>
<p>

Throw up the same toast we use for triggering the other backend file downloads.

</p>
</details> 

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

1. Create mutations which accept the same args as poolCandidatesPaginated and usersPaginated but trigger file downloads.
2. The mutations create a queud job, passing the args and userId (of the requestor) to the job.
3. The job, when it runs, replicates the query. This will be the most annoying part of this ticket, since we need to replicate queries otherwise handled by Lighthouse directives. 
4. The job then creates saves the results in a CSV file and creates a notification for the user with a link to the file.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Button added to Candidate and User tables which triggers server-side generation of a CSV file which includes all items which match current filters.
- [ ] Use the same toast as in the #9693 
- [ ] Separate api that downloads all data without taking in any ids or pagination offset 
- [ ] Stress-test this on UAT with tens of thousands of candidates.

## Blocked By
```[tasklist]
### Blocked by
- [ ] #9683 
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/11144
```

**Comment by brindasasi** [comment]
This should be discussed with the team on how do we want to implement async download

**Comment by tristan-orourke** [comment]
Assuming #9683 is complete, this becomes mostly about adding the button to the tables, and making sure the generated report includes all users/applicants matching the filters.

**Comment by brindasasi** [comment]
This is not doable right now .. This should be done after the server side report generation epic has been completed.

**Comment by brindasasi** [comment]
@Jerryescandon/ @gobyrne  could you update the UI in here ?

**Comment by tristan-orourke** [comment]
Talking further with the designers, the design is okay as is! "Download full dataset" will download the dataset as CSV. We are avoiding a "Download all profiles" button for now.

**Comment by esizer** [comment]
I just realized, since we do not actually run this via lighthouse and are building our own query, we will lose the magic of the `@scope` directive. Also, right now we scope in the mutation since `can` does not seem to work on a plain user object. The first part will be annoying but not too difficult I think:

```php
public function buildQuery($query, $filters)
{
   foreach($filters as $key => $value) {
     if($value) {
        $method = 'scope'.ucfirst($key);
         $query->$method($value);
      }
   }
}
```

Though, the auth might be trickier to pull off 🤔

**Comment by tristan-orourke** [comment]
Okay, here are my thoughts:
- We decided last time that the "business logic" and authorization should happen in the mutation. That approach means running a query in the mutation which returns all ids, passing that list to the job, and then producing the _files_ in the job.
- Turns out we can start the query with `User::select('id')` to select only the ids. I was wrong about eloquent always running `select *`. That reduces the initial query at least a little bit.
- The worst case for complexity of a query is that it includes a lot of different filters and scopes, but I'm pretty sure the server handles these just fine. I think its number of results which have been a problem, not complexity of the query.
- The worst case in terms of number of results is that a Platform Admin removes all filters and tries to download a list of _all candidates_. How big can the list of id's get before its too big to store in memory / for the job?
- What is the intended use case here. Are we even okay with someone trying to download a list of all candidates on the platform? If not, we should about how to limit this ie to a specific pool. That would be easy to do on the backend (require a pool id in the mutation) but how do we communicate that in the UI if this button is in an otherwise very flexible table?

**Comment by tristan-orourke** [comment]
Question for designers @Jerryescandon: are we okay with someone downloading ALL candidates on the platform (or ALL candidates in a single Community) in a single CSV?

**Comment by gobyrne** [comment]
I see no reason to block that
