### ISSUE TITLE
✨ Create inline version of `SkillDialog` component

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#7112]
We want the list of skills that appears on the Search page to **NOT appear by default**, we want it to appear only if:

A) The two dropdowns have have been filled out first, or
B) The user targets the list (dropdown, searchable) and starts typing

There has been some work done around this in issue #5054 but it's not there yet. Additionally, #5054 is meant to be a dialog, while this would include all 3 fields as part of the form.

### CURRRENT

<details><summary>Screenshot of current implementation</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/c5f6b52f-00ff-40e5-a701-01f5699d0184)

</p>
</details> 

### IDEAL 

<details><summary>Screenshot of ideal implementation</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/d1f55fce-c368-414e-a946-22314516aff9)

</p>
</details> 

## Acceptance Criteria

- [ ] rename `SkillDialog` component to `SkillBrowserDialog`
- [ ] create new inline version of component `SkillBrowserDialog` outside of a Dialog
- [ ] form not updated in current `SkillDialog` component, factor out contents
- [ ] create new storybook story for inline component

**Comment by Jerryescandon** [comment]
This issue probably benefits from some more input by @esizer and @substrae before passing it on

**Comment by substrae** [comment]
@Jerryescandon @esizer 

So Eric and I talked about having results appear on focus/click and it sounded mildly more complicated than we were originally hoping for. We're going to have to do some research into the component we've chosen so that we can make an informed decision about options and how we move forward. I've made it clear that this is kind of integral functionality to this element, and without it, the combobox component is providing a subpar (and potentially task restricting) experience,
