### ISSUE TITLE
🐛 React has detected a change in the order of hooks called by `CareerTimelineSection`

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#7397]
## 🐛 Bug

React has detected a change in the order of hooks called by `CareerTimelineSection`.

## 🦋 Expected Behaviour

No console errors should appear.

## 📋 Steps to Reproduce

1. `npm run dev`
2. Navigate to **Profile > Career timeline and recruitment** page
3. Select **Sort experience by** field option
4. Select a different **Sort experience by** field option
5. Observe console error

## 📸 Screenshot

![Screen Shot 2023-07-26 at 10 30 32](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/eeb5b653-d8dc-4d62-8384-11f8ad5db85e)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] `console.error` no longer appears

**Comment by esizer** [comment]
I'm pretty sure this is being caused by using a hook in a non-hook. Not sure why eslint never caught it but I'd start looking here:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/d4b51206d6460516d3220cb2f82d60ec64cb95a2/apps/web/src/components/ExperienceSortAndFilter/sortAndFilterUtil.ts#L69-L70
