### ISSUE TITLE
✨ Differentiate header item of active page

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7739]
## ✨ Feature

The header link for the current page needs to be styled more strongly to help the user recognize that it is different.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/990d9936-4a47-4ab6-80d7-9320c0917125)

## ✅ Acceptance Criteria

- [ ] Active link uses `secondary.darker` colour
- [ ] Active link is bolded
- [ ] Active link has no underline
- [ ] Active link is marked with `aria-current=page`

**Comment by esizer** [comment]
We already did this and had to revert the change for a11y. When navigating a `nav` element, it is better to mark the link as active through the `aria-current` attribute and style it for visual users.

If we remove the link, it will lead to some dodgy HTML and could cause more confusion for visually impaired users.

If users are confused by the active link, we may need to just change how we style them rather than removing the link.

REFS: 

 - [Using the aria-current attribute](https://tink.uk/using-the-aria-current-attribute/)
 - [Better (more accessible) active link styling](https://gomakethings.com/better-more-accessible-active-link-styling/)

**Comment by petertgiles** [comment]
> We already did this and had to revert the change for a11y.

Thanks!  I was pretty sure we tried this already.

**Comment by vd1992** [comment]
Seems not so good an idea

**Comment by vd1992** [comment]
@esizer 
Please give some suggestions for improvement

**Comment by RM-1978** [comment]
@gobyrne, is there any way that @esizer and I could get a bit more context?
This request may cause an accessibility issue because we might introduce limits for users to navigate the Browse Jobs page. This way, we can be sure that we explore the proper accessibility solutions. See @esizer's comments above.

**Comment by substrae** [comment]
@esizer @petertgiles 

The nav designs for active links should appear like this:
- They should use `secondary.darker`
- They should be bolded
- The underline should be removed

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/990d9936-4a47-4ab6-80d7-9320c0917125)
