### ISSUE TITLE
♻️ Polish New Table Components

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7752]
## ♻️ Debt/Refactor

We were rushing a bit to merge [the new table components](https://github.com/GCTC-NTGC/gc-digital-talent/pull/7588).  Now that they're in and the team can start building the dependent features we should go back and polish the base components.

Chromatic link: https://www.chromatic.com/component?appId=61e099a1bb1465003a73d3ce&csfId=tables-responsive-table&buildNumber=5556&k=64ecaeb96e6fc4f8630f355e-1200px-interactive-true&h=7&b=-1

## ✅ Acceptance Criteria

- [x] Update pagination (discussion: https://github.com/GCTC-NTGC/gc-digital-talent/pull/7588#discussion_r1302054232 solution: https://github.com/GCTC-NTGC/gc-digital-talent/issues/7752#issuecomment-1697695961)
- [x] [design review items](https://github.com/GCTC-NTGC/gc-digital-talent/issues/7752#issuecomment-1710190388)
  - [x] Font size on this checkbox group is different from our other checkbox inputs
  - [x] Font size on the "Show" select element should match the label next to it, and not be bolded
  - [x] change the label to `Filter by keyword`, and I'm not sure we need the icon in this context
  - [x] Column header bolding doesn't match the design - no need to bold unless an item is selected for sorting, in which case the underline should disappear
  - [x] The footer element's content should align with the first column's content
  - [x] Mobile row padding is a bit tight, designs had it set to `x1` by default, but if this is causing issues on smaller screens, we can reduce it before it increases to `x1` for larger mobile devices
  - [x] Bolding used in mobile content is using `800` instead of `700`
  - [x] Footer elements should centre on mobile
  - [x] The ability to select all objects is missing on mobile
  - [x] Padding between the two pagination rows is a bit tight compared to the design - I'm a bit worried about tap targets here
- [ ] [Mobile view has a "Sort by value" function](https://github.com/GCTC-NTGC/gc-digital-talent/pull/7831#discussion_r1317880531)
- [ ] mobile viewport story for Chomatic to snapshot

**Comment by vd1992** [comment]
@substrae 
There was also one other question that needs resolution please
https://github.com/GCTC-NTGC/gc-digital-talent/pull/7588#discussion_r1302098709

**Comment by substrae** [comment]
@petertgiles @vd1992 

I think this is good to go based on Vachan's edit! 🥳

**Comment by substrae** [comment]
Okay first and foremost, massive freaking shout-out to @esizer for tackling this component. Responsive tables are easily one of the most complicated elements you can build for a web app, and so you deserve a huge 👏 for this work. Not only does it work well, it looks fantastic and is buttery smooth.

My review list looks long, but I promise it's mostly small font stuff. I've omitted a few things given that some functionality was deliberately spun out to help move the component forward. Gimme a shout if you have any questions!

<details>
  <summary>Generally, the font sizes all seem weird in the Chromatic snapshot (everything is base `16px` instead of `18px`); I assume this is because it's missing Hydrogen's `html` font-size element application</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2ef0c396-56bc-42e7-8f78-b430b2287670" />
</details>

<details>
  <summary>Font size on this checkbox group is different from our other checkbox inputs</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/c97ae802-28e2-4471-a0a3-eaeb68cbc592" />
</details> 

<details>
  <summary>Font size on the "Show" select element should match the label next to it, and not be bolded (underline is actually good to keep here, I'll update the Figma)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/66df0cbb-d41b-405f-9cdf-3c74a8953988" />
</details> 

<details>
  <summary>The search implementation feels really repetitive right now - a label, a select with "Search", and a magnifying glass icon; we can change the label to `Filter by keyword`, and I'm not sure we need the icon in this context</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/411c2301-7e26-433a-b88a-7026d99c22d9" />
</details> 

<details>
  <summary>The empty table refers to an "Add an item" button that doesn't exit; are empty messages customizable for the table's context?</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/497c658a-2cc1-41b3-ab8a-8c7586c9d62b" />
</details> 

<details>
  <summary>Column header bolding doesn't match the design - no need to bold unless an item is selected for sorting, in which case the underline should disappear; I like the positioning of the icons, so I'll update Figma to match</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/1bebab5b-3ab9-437c-a12f-149446dac823" />
</details> 

<details>
  <summary>The footer element's content should align with the first column's content</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/adb05600-aef8-4341-815b-e98f796f5af9" />
</details>

<details>
  <summary>Mobile row padding is a bit tight, designs had it set to `x1` by default, but if this is causing issues on smaller screens, we can reduce it before it increases to `x1` for larger mobile devices</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/d45d123f-f5f6-41cd-81d4-6254a2d61a79" />
</details>

<details>
  <summary>Bolding used in mobile content is using `800` instead of `700`</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/990c1a5c-d7bb-424d-ae50-1b5f15e4b3e8" />
</details>

<details>
  <summary>Footer elements should centre on mobile</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/32e3ccd4-724c-42c8-9716-84493b1dd4e2" />
</details>

<details>
  <summary>The ability to select all objects is missing on mobile; I'm assuming this is one of those things that had to be cut for time</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/54d0517e-02d3-414d-b5a4-7f04442951b4" />
</details>

<details>
  <summary>Padding between the two pagination rows is a bit tight compared to the design - I'm a bit worried about tap targets here</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/bdc90093-a7bd-492c-a231-2bc47880967e" />
</details>

**Comment by esizer** [comment]
> I assume this is because it's missing Hydrogen's `html` font-size element application

I think you are correct about this but we should add it to the AC to be sure 👌 If that is the case, maybe we can look into getting this into storybook? Seems like it would be important for reviews.

> are empty messages customizable for the table's context?

Thankfully they are, we have a `nullMessage` prop where you can control it. This is just the default. However, if we aren't guaranteed to have an add button, should we update the default message to be more generic?

> Bolding used in mobile content is using `800` instead of `700`

I have no idea where I got the 800 from but it has shown up in a few PRs now 🤦‍♀️

**Comment by substrae** [comment]
@esizer 

> I think you are correct about this but we should add it to the AC to be sure 👌 If that is the case, maybe we can look into getting this into storybook? Seems like it would be important for reviews.

It's not a huge deal for me, but it might be for other designers doing reviews. Maybe a separate ticket and then look at it if/when y'all have the time.

> Thankfully they are, we have a nullMessage prop where you can control it. This is just the default. However, if we aren't guaranteed to have an add button, should we update the default message to be more generic?

Oh awesome! Hmm, I'm not sure which occurs more frequently - I have a weird feeling the button is present more often than not...

> I have no idea where I got the 800 from but it has shown up in a few PRs now 🤦‍♀️

No worries about this 😂

**Comment by petertgiles** [comment]
> Okay first and foremost, massive freaking shout-out to @esizer for tackling this component. Responsive tables are easily one of the most complicated elements you can build for a web app, and so you deserve a huge 👏 for this work. Not only does it work well, it looks fantastic and is buttery smooth.
> 
> My review list looks long, but I promise it's mostly small font stuff. I've omitted a few things given that some functionality was deliberately spun out to help move the component forward. Gimme a shout if you have any questions!
> Generally, the font sizes all seem weird in the Chromatic snapshot (everything is base `16px` instead of `18px`); I assume this is because it's missing Hydrogen's `html` font-size element application
> Font size on this checkbox group is different from our other checkbox inputs
> Font size on the "Show" select element should match the label next to it, and not be bolded (underline is actually good to keep here, I'll update the Figma)
> The search implementation feels really repetitive right now - a label, a select with "Search", and a magnifying glass icon; we can change the label to `Filter by keyword`, and I'm not sure we need the icon in this context
> The empty table refers to an "Add an item" button that doesn't exit; are empty messages customizable for the table's context?
> Column header bolding doesn't match the design - no need to bold unless an item is selected for sorting, in which case the underline should disappear; I like the positioning of the icons, so I'll update Figma to match
> The footer element's content should align with the first column's content
> Mobile row padding is a bit tight, designs had it set to `x1` by default, but if this is causing issues on smaller screens, we can reduce it before it increases to `x1` for larger mobile devices
> Bolding used in mobile content is using `800` instead of `700`
> Footer elements should centre on mobile
> The ability to select all objects is missing on mobile; I'm assuming this is one of those things that had to be cut for time
> Padding between the two pagination rows is a bit tight compared to the design - I'm a bit worried about tap targets here



> Maybe a separate ticket and then look at it if/when y'all have the time.

I opened #7877 for this.
