### ISSUE TITLE
🐛 Unclear when Skills connected to Experiences are actually saved to database

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7825]
## 🐛 Bug

When adding skills to an experience, it looks like the skill has been saved, but it actually requires an additional click before the connection is saved to database. A user might easily misunderstand and leave without submitting.

## 🦋 Expected Behaviour

I'm not sure. Should we _actually_ save the skill earlier? (If we do, we'll have to contend with Experience-Skills without justifications.) Should we change the UI to make the current flow clearer? Or is this less of a problem than I think and can be left alone?

## 🕵️ Details

I think this is mainly confusing because we show a success toast when closing the modal. I think we added this for accessibility reasons. My only concern is that the majority of our toasts indicate successful interaction with the server, and this does not.

Noticed this on the Create Experience / Edit Experience pages.

http://localhost:8000/en/users/:userId/profile/career-timeline-and-recruitment/create

## 📋 Steps to Reproduce

1. Log in
2. Go to career timeline page
3. Click to edit an experience
4. Click "Add a skill"
5. Select a skill in the modal and submit
6. Note the success toast
7. Click "cancel and go back" (or back in the browser or via breadcrumbs)
8. Go back to edit the same experience
9. Skills weren't saved!

## 📸 Screenshot

First "save" button:
![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/2ed4b032-58a5-4269-ae17-d7b24efa5691)

Misleading toast (we haven't saved anything to server yet):
![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/0ca3c237-4bc8-4e7a-8490-57f17435f777)

If user leaves without clicking this submit button, new skills will be lost
![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/4b361a6b-35f9-4a17-b4ec-d94732a28380)

## 🙋‍♀️ Proposed Solution

Need designer feedback

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by substrae** [comment]
@tristan-orourke 

Couple of things here:
- I'm not necessarily worried about this interaction, because in order to submit the rest of the page, they have to use the save button either way; they've come here by choosing to edit an experience, so the skill flow hopefully doesn't detract from that mental model
- I agree that the toast makes things more confusing than they need to be - I wonder if we could say something along the lines of `"Enterprise software" was added to this experience's featured skills. Don't forget to describe how this skill featured in the role using the text box provided.`
- The alternative to this interaction would be to ask for the skill justification within the skill browser dialog; this isn't something I'm opposed to necessarily, but it does complicate the dialog further and forces the user to contemplate their reasoning before they can continue

**Comment by gobyrne** [comment]
I don't really find it confusing, that's how I'd expect a "cancel" to function. If we saved anything before that, it would just be skill attached to the experience with no justification? I guess that would also be ok, but I'd still expect the cancel button to delete it.

Anyway, I would defer to the designers, but I would suggest it's ok as-is.

**Comment by tristan-orourke** [comment]
Alright, I'll close this issue then.
