### ISSUE TITLE
♻️ General solution for firewall'd user input 

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#7929]
## ♻️ Debt/Refactor

Resolve the core problem of #7812 more thoroughly. 

## 🕵️ Details

The above issue was more a fix an immediate issue quick but not solve the root of the problem.
Now the goal is to ensure user input can handle troublesome character input in general

## 🙋‍♀️ Proposed Solution

- Ask IMTD for a firewall blocking list and update filtering/trimming appropriately
- Plain text pasting into input https://stackoverflow.com/questions/12027137/javascript-trick-for-paste-as-plain-text-in-execcommand

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

- [ ] The problem is solved in a general way and not specific to a certain character like the other issue

**Comment by petertgiles** [comment]
Another case to handle: The firewall doesn't like "javascript:".  It seems like it's using a regex because it will catch if in titlecase and if there are spaces between the word and colon.  Irritating and common if someone is trying to submit an application that asks about javascript experience.  
https://talent-cloud.slack.com/archives/CB424V61J/p1697208177991189

**Comment by petertgiles** [comment]
Submitted AZ-17825 on Jira.

**Comment by petertgiles** [comment]
IMTD confirmed that this blocking is happening from the F5 Web Application Firewall (WAF).  Is reviewing now.

**Comment by petertgiles** [comment]
IMTD has tweaked the F5 firewall to just run only JSON-specific rules on the /graphql path.  It fixes the cases that I know of when I tested on the prod site.
