### ISSUE TITLE
Pool operators should have permissions to view & edit Notes for candidates in their team's pools

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#8002]
## Details
Pool operators should have permissions to view/edit the notes section for candidates in their pools.

Right now it seems that only Request Responders have access to the notes section for Candidates.

While Request Responders may use the notes to help with matching, they are also used/written by Pool Operators during the assessment process.

For now I think almost all our Pool Operators also have the Request Responder role, so it hasn't impacted us yet. But we intend to change this going forward, so we should fix this.

## Acceptance Criteria
- [ ] Pool operators have view & edit permissions for the Notes section for all candidates in pools owned by their team.

**Comment by petertgiles** [comment]
Right now the policy is called `updateAsAdmin` and uses the `update-any|team-applicationStatus` permissions.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/649b9b7a-a69e-4e8b-994f-ba3f6dd4535f)

This permission is not named well since there are more fields than just status that this mutation can update:

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/88186582-8d15-4732-8018-5e9ecbc4987d)

If pool operators should be able to update these fields we should be able to just grant that role the `update-team-applicationStatus` permission, right?

The relevant section of the Sheets document:

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/526387bc-449c-40e0-b5be-e5bcdac90567)

**Comment by petertgiles** [comment]
@gobyrne I confirmed (I think) that Pool Operators can update the status and notes for their team's pools.

https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/9b407188-94b3-4d74-bff8-105049263727
