### ISSUE TITLE
🐛 Sign in, Sign up pages have inconsistent French translations

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#8599]
## 🐛 Bug

The sign in and sign up pages have identical English copy in the FAQ section but the French translations are inconsistent on nearly every question and answer.

## 🦋 Expected Behaviour

Strings that are identical and serve an identical purpose should be the same on the FAQ section of the sign in and sign up pages in English and in French.

## 📋 Steps to Reproduce

1. Navigate to `/en/login-info`
2. Observe FAQ section
3. Switch to French
4. Navigate to `/en/register-info`
5. Repeat steps 2-3
6. Observe different copy for same questions and answers

#### English
![Screen Shot 2023-11-24 at 13 14 05](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/d1a7305e-d111-4da3-b0c2-c3c58894bd1f)

#### French
![Screen Shot 2023-11-24 at 13 14 51](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/1be257c5-33d4-4e42-8700-6e2c66f717f3)

## 🙋‍♀️ Proposed Solution

1. Consolidate strings used so that there is a single string for both pages instead of the current two
2. Just pick a single translation for now (translation will be updated later)

## ✅ Acceptance Criteria

- [ ] consolidate the English strings together
- [ ] update with new, better, French translations

**Comment by RM-1978** [comment]
Just recording the proposed solution: 
Dasha: I will wait to sent it back… please let me know when you are ready and what the final instructions are ;)
Matt
: thanks 
Dasha, in my opinion, the first step is to consolidate all of the English strings in the codebase so there is only source of truth for both pages. after that, send them again for translation as part of the same issue. does anyone disagree with that approach?

**Comment by RM-1978** [comment]
@mnigh you are right these texts are not part of the translations we are treating as part of [♻️ Make translations consistent #8463.](https://github.com/GCTC-NTGC/gc-digital-talent/issues/8463).  

That said, @petertgiles,  let's deal with this translation now rather than later. Id @mnigh likes my suggestion, let's move ahead with updating it with a single translation for both. I am not a fan of either translation option, so i suggest that we use: 

> " Que se passe-t-il si je ne dispose pas de mes codes de récupération après les avoir perdus ou avoir supprimé l'application ?" 
It is more succinct and accurate. 

Best, 

-Rosalie

**Comment by petertgiles** [comment]
> That said, @petertgiles, let's deal with this translation now rather than later. Id @mnigh likes my suggestion, let's move ahead with updating it with a single translation for both.

Sure, I'm fine with that.  I'll update this AC of the issue.

**Comment by RM-1978** [comment]
📯 Thoughts
@gobyrne, As we said, I verified these FAQ translations for these pages against the document for issue #8463.  Because the questions were ordered differently and sent to different translators, they were translated differently.

📷 Screenshots
English Sample:  [**Sign in**](https://talent.canada.ca/en/login-info) vs [**Sign up**](https://talent.canada.ca/en/register-info)
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/101275838/2e7c2559-e9e5-4830-a300-079cbed85b88)

French Sample: [**Se connecter**](https://talent.canada.ca/fr/login-info) vs [**S'enregistrer**](https://talent.canada.ca/fr/register-info)
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/101275838/5066f817-8485-453d-af3b-fb0d5e82637e)


🙋‍♀️ Proposed solution 
1. Update the French FAQ Q+As with the texts in the this confirmed list:  [FAQ_Translation consistency verification_12202023.xlsx](https://github.com/GCTC-NTGC/gc-digital-talent/files/13733315/FAQ_Translation.consistency.verification_12202023.xlsx)
2. I suggest that we keep the question order as they are in the two UIs because they seem to be ordered based on user concerns within two specific contexts (whether they are registering or signing in).

**Comment by RM-1978** [comment]
Thanks @petertgiles, at the moment I don't think I am requesting further changes beyond those @mnigh mnigh suggested that we adjust. :)
