### ISSUE TITLE
✨ New support email at talent.canada.ca

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#8674]
## ✨ Feature

We have a new support email that we have more control over and shares the same domain as our site :)

Let's replace the current support email everywhere it appears with: support-soutien@talent.canada.ca

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [x] support-soutien@talent.canada.ca is used with the support form
- [ ] ~support-soutien@talent.canada.ca is provided on job posters~
- [x] support-soutien@talent.canada.ca replaces the existing support email everywhere else as well
- [x] Update `AccessbilityStatementPage` to reference constant
- [ ] Deployment env change

**Comment by mnigh** [comment]
Most of this should be pretty simple, though will require a change to an environment variable, `TALENTSEARCH_SUPPORT_EMAIL`, on the different environments as well. I would also like to suggest that as part of the scope of this issue, we change the `AccessibilityStatementPage` component to use the constant `TALENTSEARCH_SUPPORT_EMAIL` instead of being hardcoded.

References in codebase: https://github.com/search?q=repo%3AGCTC-NTGC%2Fgc-digital-talent%20gctalent-talentgc%40support-soutien.gc.ca&type=code

> ## ✅ Acceptance Criteria
> * [ ]  [support-soutien@talent.canada.ca](mailto:support-soutien@talent.canada.ca) is provided on job posters

The aforementioned item seems more like a content management change.
