### ISSUE TITLE
✨ Link the talent request "Require Diploma" field to application Education Requirments in Search

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#8821]
## ✨ Feature

Talent seekers may submit that they require candidates with a diploma. However, this field has no affect on the candidate count they see when changing filters. (See #5976.)

Similarly, Request Responders can see that a request included a diploma requirement, but it is impossible for them to search or filter candidates based on this requirement.

If we want, it would now be possible to filter candidates based on how they fulfilled the education requirement.

## 🕵️ Details

We could make it possible to filter applicants based on how they fulfilled the education requirement of a poster (diploma or experience). We could then tie this to the diploma requirement on the Talent Seeker live count, and on the corresponding filters on the admin side.

However, we should consider carefully whether this is desirable. First, if we are filtering applicants out based on lack of a diploma, we should indicate to users that a diploma justification is preferred to experience. Second, its possible users could justify their education requirement with experience, but have a diploma in an unrelated field - would this matter to the talent seeker? Third, do we take the position that if a user can meet an education requirement, it does not matter how they do?

If we don't want to go ahead with this filtering, can we consider removing the option entirely for Talent Seekers? (Note to devs: If we don't do that either, we should consider a debt ticket instead, refactoring how this option is implemented. Its confusing having a field in `ApplicantFilter` which doesn't and _can't_ filter applicants.)

### 🧑‍🎨 Designer

Over to you @substrae and @gobyrne 

## 📸 Screenshot

Talent seeker education requirement:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/eed209c1-1df0-4cf5-88d1-2e6bc85c634a)

Education requirement visible to Request Responders:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/28d7e090-d03f-42e4-98f7-062e1e20ad53)

Candidates may claim a diploma when justifying education requirements:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/86356a90-701f-432e-bf26-63de047264a4)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

Might need a tiny bit of copy if this gets added to Pool Candidate table filters.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Talent seeker live count takes education requirement into consideration, based on application `educationRequirementOption`
- [ ] Pool Candidate tables on /admin have a filter option for `educationRequirementOption`
- [ ] Pool Candidate table education filters have default value based on request hasDiploma value

**Comment by vd1992** [comment]
I think it is unfair as it is information that an applicant cannot easily add. As well, the application education section retroactively making one option strictly superior would be also be unfair to everyone who already applied and may have chosen differently if they knew one option was the better choice. 
I recall back when the application process was being built we also had confusion about which option people should select.

**Comment by esizer** [comment]
> I recall back when the application process was being built we also had confusion about which option people should select.

Good point @vd1992 

I also remember we discussed not tracking this due to us explicitly telling users it doesn't matter which option they select. 

> Feel free to to select the option that best reflects your qualifications.

But by nature of us tracking this type of request, users who select the post-secondary option will be prioritized 😕 

So, even if I do meet the post-secondary requirement but I deem my work experience more relevant and select that option, I may have unknowingly de-prioritized myself in the search results 👎 It seems confusing and disingenuos

**Comment by substrae** [comment]
Allowing managers to select an education requirement in the talent request UI is redundant. People can't be qualified in a pool without meeting the education requirement in that pool, and because they're qualified at a classification level in said pool, if the manager asks for a classification, they will only ever get qualified talent who have met the education requirement regardless of which option they used. 

Because education requirements are directly tied to classification, I don't see any value in allowing managers to have this filter when they already filter by classification anyway.

**Comment by gobyrne** [comment]
This needs to wait for record of decision. We can try and tackle it after that.

**Comment by mnigh** [comment]
@tristan-orourke Does [Will not complete](https://github.com/GCTC-NTGC/gc-digital-talent/issues/8821#event-c5764453-7e02-5ebb-9a9a-29ef20166b11) mean this issue should be closed?

**Comment by tristan-orourke** [comment]
I don't know what it means :/ Gonna wait for @gobyrne to get back to ask him.

**Comment by gobyrne** [comment]
I'll create a new issue to link this field to the education assessments that we capture in record of decision.
