### ISSUE TITLE
✨ Remove columns "Edit" and "Candidates" from Processes table 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#8850]
## Feature

We want to remove the columns "Edit" and "Candidates". These sections change states and may not always be editable, or users might not have certain permissions, it's more desirable to force users to navigate into each pool first and then find their way through there.

## 🕵️ Details

Remove the following columns from the "Processes" table:

- Edit
- Candidates

## 🎨 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/8acb9efe-a49a-40de-abc3-fb55cfd94455)

## ✅ Acceptance Criteria

- [ ] The column "Edit" no longer appears on the "Processes" table
- [ ] The column "Candidates" no longer appears on the "Processes" table

**Comment by brindasasi** [comment]
@GCTC-NTGC/designers  please review this issue.

**Comment by Jerryescandon** [comment]
short answer: I'm ok with the proposed change.

Long rant: I personally would vote to remove this column entirely, and remove the "view candidates" column as well, and force users to navigate into each pool first and then find their way through there. Specially because these sections change states and may not always be editable, or users might not have certain permissions. I'm in no rush to make this change without consulting with more designers though.

**Comment by gobyrne** [comment]
I like the long rant. My impression from using the Admin portal is that the links on the tables are a bit clumsy. They often don't bring me to where I expect. A standardized path through the new (and improved) pool page to get to the sub pages might actually just make things simpler (though possibly less convenient for super-users).

@Jerryescandon let's float a design for your long rant by Recruitment team. We can say: "We have this new and improved  Process Information page, we want to use it!"

**Comment by Jerryescandon** [comment]
For @GCTC-NTGC/designers "Please dont get rid nof this until we have process number somewhere else."

**Comment by Jerryescandon** [comment]
I updated the ticket to simply remove the columns instead of making copy updates.
