### ISSUE TITLE
Code view of snapshot - only for platform admins

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#8926]
### Details
We originally left a "code view" of the application snapshot because we were afraid the snapshot view would break easily with new changes to the application.

In practice though, it seems to be holding up well. We do not have a documented case of needing to use the "code view".

On top of that, the code view of the application snapshot is a little confusing to everyday users.

Can we give the "code-view" option to platform admins only?

### Acceptance criteria
- [ ] Code-view of application snapshot is visible only to platform admins

**Comment by tristan-orourke** [comment]
How about, we remove the manual "switch to code-view" button, but we set it up so that if there's an error in the normal snapshot view we show the code view instead.

We can use a React [Error Boundary](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary) for this.

**Comment by tristan-orourke** [comment]
This may already be done with the changes as part of Record of Decision.

**Comment by tristan-orourke** [comment]
We also have the download as a backup
