### ISSUE TITLE
🐛 Get the images working for link previews

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9134]
## 🐛 Bug

Link previews are not showing the images we created for our site.

## 🦋 Expected Behaviour

When the link to our site is shared on other platforms it should present the image we created for link sharing.

## 🕵️ Details

Tested in Slack and Teams, others confirmed that nobody has seen the preview image on any platform

This slack conversation has some additional insights :
https://talent-cloud.slack.com/archives/CB424V61J/p1704906621493589

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Image preview shows up when link is shared

**Comment by tristan-orourke** [comment]
We have to track down why the env variable isn't available at build time, and how to make it so. Will need to be tested in azure, in dev env, likely during development

**Comment by mnigh** [comment]
@tristan-orourke Is `azure-pipelines.yml` being used or just an old reference file?

1. Do we even need `ADMIN_APP_DIR: /admin`?
2. What if we add `APP_URL: "https://talent.canada.ca"`, will that fix the opengraph path issues?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/f8a7767ed2c75328284c0e26fb828b2a0af8ecd4/infrastructure/azure-pipelines.yml#L34-L39

**Comment by mnigh** [comment]
So, adding an env item `APP_URL: "https://talent.canada.ca"` in azure-pipelines.yml I think would work, but it would mean that the production URL would be used in other server environments as well and therefore, not a true representation of what the app should use. 

After some help wading through the murky waters of Azure with @petertgiles and @esizer, I haven't been able to come up with a good way to get the appservice or keyvault value for `APP_URL` into the pipeline in a good way. 

# Options
## Option 1
hardcode `APP_URL: "https://talent.canada.ca"` in azure-pipelines.yml. not a great solution as it forces production values that shouldn't be on non-prod verticals.

## Option 2 
make each one of the three URLs (https://dev-talentcloud.tbs-sct.gc.ca/, https://uat-talentcloud.tbs-sct.gc.ca/, https://talent.canada.ca/) a [pipeline parameter ](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/parameters-parameter?view=azure-pipelines) value and then having to choose each one when building. not a great solution since the values would not be coupled with their intended vertical.

Any @GCTC-NTGC/developers have any better ideas?

**Comment by petertgiles** [comment]
To make something distinct between the verticals it must be set during runtime or post-deploy, not build time.  We currently [use `envsubst` in the post-deployment.sh script](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/infrastructure/bin/substitute_file.sh) to fill in the config.js file and Nginx config with runtime variables.  I was toying with the idea of moving the config.js variables into index.html to remove a startup server request.  Filling in some head values like this URL is another good reason to run `envsubst` on the index.html file.

**Comment by tristan-orourke** [comment]
Go with fallback url for now!

**Comment by petertgiles** [comment]
Created #9206 for a possible long-term solution
