### ISSUE TITLE
Remove bookmark column from Candidates table

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9216]
## ✨ Feature

Recruitment team has pointed out that Bookmarked candidates only make sense in context of their pool. They've asked that on the admin Candidate Search page (http://localhost:8000/en/admin/pool-candidates) the Bookmarked column not appear at all, and not be involved in sorting.

### 🧑‍🎨 Designer

@Jerryescandon 

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/0e94e55d-6528-4353-b3a9-db29cc6f9025)

## 🙋‍♀️ Proposed Implementation

We use the same table for Pool Candidates on a pool page, and in general. Seems like we need to add a prop to the table component which can hide/show the bookmarks "column" and optionally bookmarks in the locked sorting order.

Default state of the table is that it can show multiple pools. It should accept a flag that indicates its only dealing with one pool.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] At http://localhost:8000/en/admin/pool-candidates, the table doesn't show bookmarked status and does not use it to order candidates
- [ ] When looking at all candidates of a pool, admins still see the bookmark status, and bookmarked candidates still float to the top.

**Comment by tristan-orourke** [comment]
Actually, I think this is already the case. I'll follow up with recruitment team to understand where their confusion is.

**Comment by JamesHuf** [comment]
@Jerryescandon We also use this table on the single search request page `/en/admin/talent-requests/{requestId}`. Do we want bookmarks being displayed/used for sorting there?

**Comment by Jerryescandon** [comment]
Debatable.

As per their request, bookmarks should NOT be global, and should be contained to only be applicable inside a specific pool. e.g. a Candidate that has qualified in 3 different pools and bookmarked in one, should not give it a bookmark when they are being looked at from outside the context of that pool. 

Would "Request results" count as being within the context of a pool is possibly true, since they are showing up because of their qualification in certain pool made them meet the criteria of the request.

I am unsure to what the recruitment team would consider best at that point.

If we are already using bookmarks in the request page then I would suggest to keep it until we receive specific instructions to remove it.

And if we don't, then let's not add it until we are requested to add it.

**Comment by JamesHuf** [comment]
Ok, sounds good. I'll keep it in on that page for now then.
