### ISSUE TITLE
🐛 If filters change, and current page is higher than max page, table appears to be empty

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9312]
## 🐛 Bug

Changing the filters of the table doesn't reset which "page" you're on. Its possible to end up on a higher page than exists, and the table thinks there are no results when there should be some.

## 🦋 Expected Behaviour

If the filters change, table should be reset to the first page.

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Log is as admin
2. Go to a PoolCandidate table
3. Add some filters which decrease the number of results (and the number of pages) but still have some results.
4. Reset the filters
5. Go to the last page of the table
6. Add the same filters from before
7. Table appears empty

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

Reset the table page when filters are updated

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] When search or filters are updated, always go back to the first page of the table

**Comment by esizer** [comment]
Oof, yeah. So some more info to make this possibly easier for someone to solve. I believe this is because we control the pagination through the API. Typeically, we would reset the page to the first page when the filtering changes. You will notice on client managed tables, searching forces you back to page one.

The issue here is, since pagination is controlled outside of the table it cannot reset it. All it really does now is emit an event so we know when the user changes the page but we have no way of changing it ourselves outside of the initial load.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/28934c348a0c4aba98a24f45f7e220974b900da2/apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx#L727-L734

I think we just need to also allow passing in pagination state so it can be controlled outside of the component. Take a look at how filters work for this.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/28934c348a0c4aba98a24f45f7e220974b900da2/apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx#L660-L662
