### ISSUE TITLE
✨ [Spike] What performance improvements can we work on now that `client-preset` adoption is complete?

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9535]
## ❓ Question

Now that https://github.com/GCTC-NTGC/gc-digital-talent/issues/8681 is complete, what does that unlock? What are our next steps, in terms of performance improvements and/or other refactoring?

## 🕙 Timebox

???

**Comment by esizer** [comment]
Not directly related to performance but in an attempt to speed up the migration to `client-preset` we avoided using fragments since that would require a larger refactor to the components that consume the results of the API. We could go back and start introducing more fragments where possible so we can take advantage of fragment masking.

We do have some examples to help with the process.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/03b1ab9130b2d8174590c121ec07705cde1e2697/apps/web/src/pages/Applications/ApplicationLayout.tsx#L37-L47

**Comment by tristan-orourke** [comment]
We can work on #9543, #9545 and #9546
