### ISSUE TITLE
♻️ Bump Mock Auth to set refresh token rotation

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9538]
## ♻️ Debt/Refactor

The Mock Auth team has added an option to rotate refresh tokens.  When it is added to a release let's get it and set the option.

## 🕵️ Details

https://github.com/navikt/mock-oauth2-server/pull/645

## ✅ Acceptance Criteria

- [ ] Mock Auth is bumped to the version including the token rotation option
- [ ] Our container config sets the option

Blocked until Mock Auth creates a release with the PR included and the docker container is available.

**Comment by esizer** [comment]
When I tried this, it was our playwright auth making this not possible. We are almost there, we just need to not use the fixtures and I think we are good 👍 

I'm not aware of any tests that require two different roles. I think we were using this so we could access admin in setup and then use applicant in the tests but if we merge in the auth refactor this should not be necessary.

We will just need to remove the fixtures and login during tests rather than in global setup.
