### ISSUE TITLE
♻️ Update the skill browser dialog

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#9623]
## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=97-31278&mode=design&t=q0CnoXe0a8womMfK-4) • Contact @substrae with design questions

The goal of this ticket is to simplify the action of finding a skill by removing the need to select a skill family by defaulting to "all skills". The positioning of the filter has also been moved, alongside a new label. We've also removed the `details` element that explained what to do if you can't find a skill in favor of a new `inline` button at the bottom of the dialog that will open the new skills page created in #9540 in a new tab.

```[tasklist]
### ✅ Requirements
- [ ] Update the skill family and skill search layout
- [ ] Update the skill family input label to "Filter by skill family"
- [ ] Ensure that the skill family filter defaults to "All skills"
- [ ] Remove the skill count from the skill family options (I'm recommending this because the skill search provides a count of the results, rendering it redundant)
- [ ] Remove the logic and null states referring to "selecting a skill family to continue"
- [ ] ~Update the "Save and add skill" button to the disabled display style and change its label to "Choose a skill" when no skill has been selected~
- [ ] If the submit button is clicked before all required fields are completed, focus is pulled to first missing field
- [ ] Remove the "Show information on what to do if you can't find a skill" accordion
- [ ] Add a new "Can't find a skill?" button with the `secondary` `inline` style that opens the new public skills page in a new tab
- [ ] Ensure the different contexts still function as expected but have the changes above applied
- [ ] Triple check dark mode
``` 

```[tasklist]
### 🔗 Related
- [ ] #9624
- [ ] #9625
``` 

```[tasklist]
### ⛔ Blocked by
- [ ] #9614 
``` 

## 🔍 Details

<details>
  <summary>📸 Skill form null state</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/a77591a9-3831-4ec8-8293-310d9cf00111" />
</details> 

<details>
  <summary>📸 Skill form with skill selected</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/f83cddb4-ca7d-4850-831b-e08ba247a232" />
</details>

**Comment by esizer** [comment]
> Update the "Save and add skill" button to the disabled display style and change its label to "Choose a skill" when no skill has been selected

During the ROD testing we received more feedback that AT testers were confused by disabled buttons. Should we instead make the input required and show an error message if a user tries to submit without selecting a skill?

**Comment by substrae** [comment]
@esizer did they specify why it was confusing? Was it because they could focus it and weren't getting feedback when they tried to submit? Was the label not being read? Was the label the same as it would have been when enabled?

**Comment by esizer** [comment]
> @esizer did they specify why it was confusing? Was it because they could focus it and weren't getting feedback when they tried to submit? Was the label not being read? Was the label the same as it would have been when enabled?

The label was being read but they had no clue why it was disabled and were struggling what to do and assumed they made a mistake but were not sure how to remediate the mistake. Some go as far as to say it is an outright bug and they exit the task without completing it assuming something is broken and they cannot fix the issue.

I think just by changing the text to be "Choose a skill" users may assume that is the default action and once again wonder how to remediate the mistake. We keep getting this feedback from AT testers every time we introduce disabled buttons.

I think if we disable buttons, we need to supply a clearly stated reason for why the button is disabled and how to fix it. But this also just seems like a crutch. We could just follow the existing pattern of letting them try to submit the form and just show an error when it fails. The added benefit of this is we can pull focus right to the input so the user can immediately remediate the error instead of having to navigate back to the input as well.

**Comment by tristan-orourke** [comment]
Yes, @substrae we've consistently found that disabling buttons leads to a sub-par user experience - especially, but not exclusively for AT users. They don't provide any in-built context for why the button is disabled and what can be done to change that. (Even myself, a couple times I've been thrown off by a disabled button, not understanding why it wouldn't click.)

In general, it seems like a better pattern is to allow the button to be clicked, and rely on form validation to explain what goes wrong.

**Comment by tristan-orourke** [comment]
Let's move ahead on this without disabling the button - all fields are required, so form validation should work easily enough. When @substrae gets back we can take another look at this if necessary.
