### ISSUE TITLE
🔤 Questions about use of "Recruitment"

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9756]
## 🔤 Copy

A few places where the word "Recruitment" is used, where I wonder if it should be changed.

## 🕵️ Details

Add any additional details that could assist with the implementation of the new or existing copy.

<details>
<summary>Manage recruitment</summary>
<p>Should this instead say "Manage availability" ? It links to the Qualified Recruitments on the Account Settings page, but the only thing you can manage _to_ manage is your availability.</p>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/ea962b2a-c065-42ce-9aee-ebdf346a33e3"/>
</details>

<details><summary>Availability dialog</summary>
<p>
According to the there <a href="https://github.com/GCTC-NTGC/gc-digital-talent/issues/9643#issuecomment-1981481988">here</a>, I wonder if this dialog should about it as a "pool" instead of a "recruitment process"? Though maybe the inconsistency would just cause more confusion.
</p>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/21d22881-d3fd-4dac-ad6e-76e6e92d63a3"/>
</details>

**Comment by mnigh** [comment]
@gobyrne are these questions you are able to answer or if not, one of the @GCTC-NTGC/designers?

**Comment by substrae** [comment]
@mnigh @tristan-orourke 

- RE the application card - technically this link takes you to your recruitment process cards, that's why it says "Manage recruitment" as opposed to availability, which would open a dialog instead. If there aren't any other actions on the recruitment cards, we could change it to "View recruitment" instead. 
- RE the dialog - I thought we were avoiding the use of the word "pool" in favor of "recruitment process" everywhere? If this has changed again, we can change it here, but it needs to be consistent.

**Comment by tristan-orourke** [comment]
@substrae 
- RE the application card - okay, sounds like it can be left as is
- RE the dialog - according to [this comment](https://github.com/GCTC-NTGC/gc-digital-talent/issues/9643#issuecomment-1981481988) from @Jerryescandon, there are some contexts where we do still want to use the word "pool". Like when we're talking about a pool of talent to be drawn from. I thought it was ambiguous which context applied here. But on second thought, maybe "pool" makes more sense from a hiring manager's perspective, not the applicant's. This can be left as is as well.
