### ISSUE TITLE
🐛 Application Screening step on Draft pool can't be edited 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#9762]
## 🐛 Bug
I've 3 skills that were missing on the application screening step. 
Most likely this draft has been created before ROD roll out. 
Now I can't edit this step to fix the error. 
Currently the only alternative  is to discard this pool and create from the scratch. 
![Screenshot 2024-03-14 144925](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/df5d1163-1cbe-44f6-844a-626383a7a3bb)

## 🦋 Expected Behaviour

I don't remember why we decided to make this application screening step to be non-editable even in draft state. 
I believe it should be allowed to edit but not delete.
@Jerryescandon  ? 

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. ...
2. ...

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by Jerryescandon** [comment]
Are the skills "behavioural"?

The application SHOULD auto-populate with ALL technical skills. But behavioural  skills CANNOT be assessed through the application. If this is what is happening then it is not a bug. It is working as intended. 

If the skills ARE technical and they are not showing up, then that is a bug, since they should get automatically added. Additionally NO editing should be necessary, this should be automatic.

**Comment by yonikid15** [comment]
Leave this as is. Not planned to fix.
