### ISSUE TITLE
Government of Canada email on request page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9906]
## Details
We've been asked to change the label from "Government e-mail" to "Government of Canada e-mail" on the request page.

EN: Government of Canada email
FR: Courriel du gouvernement du Canada

### OLD
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/e8545cd5-f434-4046-a748-91ae45d2ee48)

### NEW
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/8fa5233e-f991-408b-bbcd-e009e65a477c)

## Acceptance criteria
- [ ] Text updated to "Government of Canada email"

**Comment by mnigh** [comment]
@gobyrne Can the label be changed to Government of Canada **email** since the word email isn't hyphenated anywhere else in the codebase? There is even a label without the hyphen already, HR advisor email, on the same form (see this issue's description for screenshots).

## Screenshot
<img width="336" alt="Screen Shot 2024-03-26 at 16 18 12" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/61f40502-879f-4566-b58d-408892d0453e">
